// The CUDA runtime, cuBLAS and cuBLASLt on Metal (declared in lfcuda.h).
//
// Memory: every allocation is one shared MTLBuffer and its device pointer is the buffer's GPU address, so the
// ports' pointer arithmetic, structs of pointers and arrays of pointers all hold as they are. Unified memory
// makes the same bytes the host's, through the buffer's contents.
//
// Order: every stream is the one queue, and every dispatch goes into the current compute encoder, which runs its
// dispatches serially - CUDA's stream order. A device-to-host copy waits for the queue; a host-to-device copy
// writes in place when the queue is idle and otherwise stages its bytes and copies them in order on the GPU.
//
// Kernels: the port's translated source (cu2metal.py) compiled from source, one explicit instantiation per
// specialisation a launch asks for. Specialisations seen before (a cache beside the weights) are compiled together
// up front; a new one costs a compile of its own and is remembered.
#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#include "lfcuda.h"
#include <algorithm>
#include <atomic>
#include <chrono>
#include <fstream>
#include <map>
#include <mutex>
#include <set>
#include <sstream>
#include <sys/stat.h>
#include <sys/sysctl.h>
#include <thread>
#include <unordered_map>

namespace lf {
// (the port's translation: lfport.mm, generated by metal/build.sh)
extern const KernelInfo PORT_KERNELS[];
extern const int PORT_KERNEL_COUNT;
extern const char* PORT_SOURCE;
extern const char* PORT_NAME;
extern const char* SHIM_SOURCE;
}

namespace {
[[noreturn]] void die(const std::string& what) {
  fprintf(stderr, "localfold-metal: %s\n", what.c_str());
  fflush(stderr);
  std::exit(1);
}

struct Alloc { id<MTLBuffer> buf; uint64_t addr; size_t size; };

struct Op {        // a captured graph's step
  int kind;        // 0 dispatch, 1 copy, 2 fill
  id<MTLComputePipelineState> pso; std::vector<unsigned char> args; MTLSize grid, block; size_t smem;
  uint64_t dst, src; size_t bytes; int value;
  std::vector<id<MTLBuffer>> keep;
};

struct Runtime {
  std::recursive_mutex mu;
  id<MTLDevice> dev;
  id<MTLCommandQueue> queue;
  id<MTLLibrary> shimLib;
  std::map<uint64_t, Alloc> allocs;
  size_t allocated = 0, peak = 0;
  id<MTLCommandBuffer> cb = nil;
  id<MTLComputeCommandEncoder> enc = nil;
  std::vector<id<MTLBuffer>> cbKeep;           // released when the command buffer is done
  id<MTLCommandBuffer> lastCommitted = nil;
  int encoded = 0;
  bool capturing = false;
  std::vector<Op>* capture = nullptr;
  std::unordered_map<std::string, id<MTLComputePipelineState>> pipelines;
  std::map<std::string, id<MTLComputePipelineState>> shimPipelines;
  std::set<std::string> knownSpecs;
  std::string specsPath;
  bool specsLoaded = false;
  // profiling: GPU time per kernel name
  bool profiling = false;
  std::map<std::string, std::pair<double, int>> profile;
  std::vector<std::pair<std::string, id<MTLCommandBuffer>>> profiled;

  Runtime() {
    @autoreleasepool {
      NSArray<id<MTLDevice>>* devices = MTLCopyAllDevices();
      if (devices.count == 0) die("no Metal device");
      dev = devices[0];
      if (![dev supportsFamily:MTLGPUFamilyMetal3] || ![dev supportsFamily:MTLGPUFamilyApple7])
        die(std::string("this GPU (") + dev.name.UTF8String + ") is not an Apple-silicon GPU with Metal 3; LocalFold needs an M1 or later");
      queue = [dev newCommandQueueWithMaxCommandBufferCount:64];
      shimLib = compile(lf::SHIM_SOURCE, "the runtime's kernels");
    }
  }

  id<MTLLibrary> compile(const std::string& source, const std::string& what) {
    MTLCompileOptions* o = [MTLCompileOptions new];
    o.languageVersion = MTLLanguageVersion3_0;
    o.fastMathEnabled = NO;
    NSError* e = nil;
    id<MTLLibrary> lib = [dev newLibraryWithSource:[NSString stringWithUTF8String:source.c_str()] options:o error:&e];
    if (!lib) die("compiling " + what + ":\n" + (e ? e.localizedDescription.UTF8String : "?"));
    return lib;
  }

  // ---- memory
  const Alloc* find(uint64_t addr) {
    auto it = allocs.upper_bound(addr);
    if (it == allocs.begin()) return nullptr;
    --it;
    if (addr >= it->second.addr && addr < it->second.addr + std::max<size_t>(it->second.size, 1)) return &it->second;
    return nullptr;
  }
  void* host(const void* device) {
    const Alloc* a = find((uint64_t)device);
    if (!a) return nullptr;
    return (char*)a->buf.contents + ((uint64_t)device - a->addr);
  }
  void* host(const void* device, size_t bytes, const char* what) {
    const Alloc* a = find((uint64_t)device);
    if (!a) die(std::string(what) + ": not a device pointer");
    if ((uint64_t)device + bytes > a->addr + a->size) die(std::string(what) + ": past the end of its allocation");
    return (char*)a->buf.contents + ((uint64_t)device - a->addr);
  }
  void* malloc_(size_t bytes) {
    std::lock_guard<std::recursive_mutex> l(mu);
    size_t n = std::max<size_t>((bytes + 255) & ~(size_t)255, 256);
    id<MTLBuffer> b = [dev newBufferWithLength:n options:MTLResourceStorageModeShared];
    if (!b) return nullptr;
    uint64_t addr = b.gpuAddress;
    allocs[addr] = {b, addr, bytes};
    allocated += n; peak = std::max(peak, allocated);
    if (enc) [enc useResource:b usage:MTLResourceUsageRead | MTLResourceUsageWrite];
    return (void*)addr;
  }
  void free_(void* p) {
    if (!p) return;
    std::lock_guard<std::recursive_mutex> l(mu);
    auto it = allocs.find((uint64_t)p);
    if (it == allocs.end()) return;
    allocated -= std::max<size_t>((it->second.size + 255) & ~(size_t)255, 256);
    cbKeep.push_back(it->second.buf);           // (alive until the work that may use it is done)
    allocs.erase(it);
  }

  // ---- the queue
  void ensureEncoder() {
    if (enc) return;
    if (!cb) cb = [queue commandBufferWithUnretainedReferences];
    enc = [cb computeCommandEncoderWithDispatchType:MTLDispatchTypeSerial];
    std::vector<id<MTLResource>> all;
    all.reserve(allocs.size());
    for (auto& [_, a] : allocs) all.push_back(a.buf);
    if (!all.empty()) [enc useResources:all.data() count:all.size() usage:MTLResourceUsageRead | MTLResourceUsageWrite];
  }
  void commit() {
    if (enc) { [enc endEncoding]; enc = nil; }
    if (!cb) return;
    if (!cbKeep.empty()) {
      __block std::vector<id<MTLBuffer>> keep = std::move(cbKeep);
      cbKeep.clear();
      [cb addCompletedHandler:^(id<MTLCommandBuffer>) { keep.clear(); }];
    }
    [cb commit];
    lastCommitted = cb;
    cb = nil;
    encoded = 0;
  }
  void sync() {
    std::lock_guard<std::recursive_mutex> l(mu);
    commit();
    if (lastCommitted) {
      [lastCommitted waitUntilCompleted];
      if (lastCommitted.error) die(std::string("the GPU failed: ") + lastCommitted.error.localizedDescription.UTF8String);
      lastCommitted = nil;
    }
  }
  bool idle() { return !cb && (!lastCommitted || lastCommitted.status >= MTLCommandBufferStatusCompleted); }

  id<MTLComputePipelineState> shimPipeline(const std::string& name) {
    auto it = shimPipelines.find(name);
    if (it != shimPipelines.end()) return it->second;
    id<MTLFunction> f = [shimLib newFunctionWithName:[NSString stringWithUTF8String:name.c_str()]];
    if (!f) die("no runtime kernel " + name);
    NSError* e = nil;
    id<MTLComputePipelineState> p = [dev newComputePipelineStateWithFunction:f error:&e];
    if (!p) die("runtime kernel " + name + ": " + e.localizedDescription.UTF8String);
    shimPipelines[name] = p;
    return p;
  }
  void dispatch(id<MTLComputePipelineState> pso, const void* args, size_t argBytes, MTLSize grid, MTLSize block,
                size_t smem, const std::string& label = "") {
    if (grid.width == 0 || grid.height == 0 || grid.depth == 0) return;
    if (capturing) {
      Op op{}; op.kind = 0; op.pso = pso; op.args.assign((const unsigned char*)args, (const unsigned char*)args + argBytes);
      op.grid = grid; op.block = block; op.smem = smem;
      capture->push_back(std::move(op));
      return;
    }
    ensureEncoder();
    [enc setComputePipelineState:pso];
    if (argBytes <= 4096) [enc setBytes:args length:std::max<size_t>(argBytes, 4) atIndex:0];
    else {
      id<MTLBuffer> b = [dev newBufferWithBytes:args length:argBytes options:MTLResourceStorageModeShared];
      cbKeep.push_back(b);
      [enc setBuffer:b offset:0 atIndex:0];
    }
    [enc setThreadgroupMemoryLength:std::max<size_t>((smem + 15) & ~(size_t)15, 16) atIndex:0];
    [enc dispatchThreadgroups:grid threadsPerThreadgroup:block];
    if (profiling && !label.empty()) {      // (a command buffer a dispatch: its GPU time is the kernel's)
      id<MTLCommandBuffer> mine = cb;
      commit();
      profiled.push_back({label, mine});
    } else if (++encoded >= 256) {
      commit();                             // (let the GPU start while the host encodes the rest)
    }
  }
  void copy(uint64_t dst, uint64_t src, size_t bytes) {
    struct { uint64_t dst, src, bytes; } a = {dst, src, bytes};
    size_t threads = ((dst | src) & 15) == 0 ? std::max<size_t>(bytes / 16, 16) : bytes;
    size_t groups = (threads + 255) / 256;
    MTLSize grid = groups > 65535 ? MTLSizeMake(65535, (groups + 65534) / 65535, 1) : MTLSizeMake(groups, 1, 1);
    if (capturing) {
      Op op{}; op.kind = 1; op.dst = dst; op.src = src; op.bytes = bytes; capture->push_back(op); return;
    }
    dispatch(shimPipeline("lf_copy"), &a, sizeof a, grid, MTLSizeMake(256, 1, 1), 0);
  }
  void fill(uint64_t dst, int value, size_t bytes) {
    struct { uint64_t dst, bytes; uint32_t value; uint32_t pad; } a = {dst, bytes, (uint32_t)value, 0};
    size_t threads = (dst & 15) == 0 ? std::max<size_t>(bytes / 16, 16) : bytes;
    size_t groups = (threads + 255) / 256;
    MTLSize grid = groups > 65535 ? MTLSizeMake(65535, (groups + 65534) / 65535, 1) : MTLSizeMake(groups, 1, 1);
    if (capturing) {
      Op op{}; op.kind = 2; op.dst = dst; op.bytes = bytes; op.value = value; capture->push_back(op); return;
    }
    dispatch(shimPipeline("lf_fill"), &a, sizeof a, grid, MTLSizeMake(256, 1, 1), 0);
  }

  // ---- the port's kernels
  void loadSpecs() {
    if (specsLoaded) return;
    specsLoaded = true;
    const char* home = getenv("HOME");
    std::string dir = std::string(home ? home : "/tmp") + "/.cache/localfold/metal";
    mkdir((std::string(home ? home : "/tmp") + "/.cache").c_str(), 0755);
    mkdir((std::string(home ? home : "/tmp") + "/.cache/localfold").c_str(), 0755);
    mkdir(dir.c_str(), 0755);
    size_t h = std::hash<std::string>()(lf::PORT_SOURCE);
    char name[64]; snprintf(name, sizeof name, "/%s-%016zx.specs", lf::PORT_NAME, h);
    specsPath = dir + name;
    std::ifstream in(specsPath);
    std::string line, inst;
    std::vector<std::string> names;
    while (std::getline(in, line)) {
      size_t tab = line.find('\t');
      if (tab == std::string::npos) continue;
      knownSpecs.insert(line.substr(0, tab));
      names.push_back(line.substr(0, tab));
      inst += line.substr(tab + 1) + "\n";
    }
    if (names.empty()) return;
    // every specialisation a previous run used, in one library (and in parallel chunks: the compiler is single-threaded)
    size_t chunks = std::min<size_t>(8, (names.size() + 15) / 16);
    std::vector<std::string> parts(chunks);
    std::vector<std::vector<std::string>> partNames(chunks);
    {
      std::istringstream lines(inst);
      size_t k = 0;
      while (std::getline(lines, line)) { parts[k % chunks] += line + "\n"; partNames[k % chunks].push_back(names[k]); ++k; }
    }
    std::vector<id<MTLLibrary>> libs(chunks);
    std::vector<std::thread> threads;
    for (size_t c = 0; c < chunks; ++c)
      threads.emplace_back([&, c] { @autoreleasepool { libs[c] = compile(std::string(lf::PORT_SOURCE) + parts[c], "the cached kernels"); } });
    for (auto& t : threads) t.join();
    for (size_t c = 0; c < chunks; ++c)
      for (auto& n : partNames[c]) pipelines[n] = pipelineOf(libs[c], n);
  }
  id<MTLComputePipelineState> pipelineOf(id<MTLLibrary> lib, const std::string& host) {
    id<MTLFunction> f = [lib newFunctionWithName:[NSString stringWithUTF8String:host.c_str()]];
    if (!f) die("no compiled kernel " + host);
    NSError* e = nil;
    id<MTLComputePipelineState> p = [dev newComputePipelineStateWithFunction:f error:&e];
    if (!p) die(host + ": " + (e ? e.localizedDescription.UTF8String : "?"));
    return p;
  }
  id<MTLComputePipelineState> kernel(int index, const std::string& targs) {
    const lf::KernelInfo& k = lf::PORT_KERNELS[index];
    std::string host = k.structName;
    host += "__" + targs;
    for (char& c : host) if (!isalnum((unsigned char)c) && c != '_') c = '_';
    auto it = pipelines.find(host);
    if (it != pipelines.end()) return it->second;
    loadSpecs();
    it = pipelines.find(host);
    if (it != pipelines.end()) return it->second;
    if (k.status == 2) die(std::string("kernel ") + k.name + " has no Metal translation yet (it is " +
                           "inline PTX or uses a construct cu2metal.py cannot translate) and nothing overrides it");
    std::string inst = std::string("template [[host_name(\"") + host + "\")]] kernel void " + k.name + "<" + targs +
                       ">(constant " + k.structName + "<" + targs + ">&, threadgroup char*, uint3, uint3, uint3, uint3, uint, uint, uint);";
    auto t0 = std::chrono::steady_clock::now();
    id<MTLLibrary> lib = compile(std::string(lf::PORT_SOURCE) + "\n" + inst + "\n", std::string("kernel ") + k.name + "<" + targs + ">");
    id<MTLComputePipelineState> p = pipelineOf(lib, host);
    if (getenv("LOCALFOLD_METAL_VERBOSE"))
      fprintf(stderr, "metal: compiled %s<%s> in %.0f ms\n", k.name, targs.c_str(),
              std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - t0).count());
    pipelines[host] = p;
    if (!knownSpecs.count(host)) {
      knownSpecs.insert(host);
      std::ofstream out(specsPath, std::ios::app);
      out << host << "\t" << inst << "\n";
    }
    return p;
  }
};

Runtime& R() {
  static Runtime* r = new Runtime();
  return *r;
}
thread_local lf::Launch CURRENT;
thread_local cudaError_t LAST_ERROR = cudaSuccess;
}  // namespace

namespace lf {
void setLaunchRaw(dim3 grid, dim3 block, size_t smem) { CURRENT = {grid, block, smem}; }
void launch(int index, std::initializer_list<std::string> targs, KArgs& args) {
  Runtime& r = R();
  std::lock_guard<std::recursive_mutex> l(r.mu);
  std::string ta;
  for (auto& t : targs) ta += (ta.empty() ? "" : ", ") + t;
  if (ta.empty()) ta = "0";
  id<MTLComputePipelineState> pso = r.kernel(index, ta);
  Launch L = CURRENT;
  // (an overridden kernel lays out its own threadgroup memory within the device's: the host asked for the CUDA layout)
  if (PORT_KERNELS[index].status == 1) L.smem = std::min<size_t>(L.smem, r.dev.maxThreadgroupMemoryLength - pso.staticThreadgroupMemoryLength);
  size_t threads = (size_t)L.block.x * L.block.y * L.block.z;
  if (threads > pso.maxTotalThreadsPerThreadgroup)
    die(std::string("kernel ") + PORT_KERNELS[index].name + "<" + ta + "> launched with " + std::to_string(threads) +
        " threads a block; this GPU runs it with at most " + std::to_string(pso.maxTotalThreadsPerThreadgroup));
  if (pso.staticThreadgroupMemoryLength + L.smem > r.dev.maxThreadgroupMemoryLength)
    die(std::string("kernel ") + PORT_KERNELS[index].name + "<" + ta + "> needs " +
        std::to_string(pso.staticThreadgroupMemoryLength + L.smem) + " bytes of threadgroup memory; this GPU has " +
        std::to_string(r.dev.maxThreadgroupMemoryLength));
  r.dispatch(pso, args.bytes.data(), args.bytes.size(), MTLSizeMake(L.grid.x, L.grid.y, L.grid.z),
             MTLSizeMake(L.block.x, L.block.y, L.block.z), L.smem, r.profiling ? std::string(PORT_KERNELS[index].name) : "");
}
void* hostView(const void* device) { return R().host(device); }
void profileStart() {
  Runtime& r = R(); r.sync(); r.profile.clear(); r.profiled.clear(); r.profiling = true;
}
void profileStop(int top) {
  Runtime& r = R(); r.sync(); r.profiling = false;
  double total = 0;
  for (auto& [name, c] : r.profiled) {
    double ms = (c.GPUEndTime - c.GPUStartTime) * 1e3;
    r.profile[name].first += ms; r.profile[name].second += 1; total += ms;
  }
  std::vector<std::pair<std::string, std::pair<double, int>>> rows(r.profile.begin(), r.profile.end());
  std::sort(rows.begin(), rows.end(), [](auto& a, auto& b) { return a.second.first > b.second.first; });
  printf("profile: %.1f ms of GPU time in %zu dispatches (each its own command buffer: an upper bound)\n", total, r.profiled.size());
  for (int i = 0; i < (int)rows.size() && i < top; ++i)
    printf("  %8.2f ms %5.1f%% %6d  %s\n", rows[i].second.first, 100 * rows[i].second.first / std::max(total, 1e-9),
           rows[i].second.second, rows[i].first.c_str());
  r.profiled.clear();
}
}  // namespace lf

// ---------------------------------------------------------------- the runtime API
cudaError_t cudaMalloc(void** p, size_t bytes) {
  *p = R().malloc_(bytes);
  return *p ? cudaSuccess : (LAST_ERROR = cudaErrorMemoryAllocation);
}
cudaError_t cudaFree(void* p) { R().free_(p); return cudaSuccess; }
cudaError_t cudaMallocAsync(void** p, size_t bytes, cudaStream_t) { return cudaMalloc(p, bytes); }
cudaError_t cudaMallocFromPoolAsync(void** p, size_t bytes, cudaMemPool_t, cudaStream_t) { return cudaMalloc(p, bytes); }
cudaError_t cudaFreeAsync(void* p, cudaStream_t) { return cudaFree(p); }
cudaError_t cudaMallocHost(void** p, size_t bytes) {
  *p = nullptr;
  return posix_memalign(p, 16384, std::max<size_t>(bytes, 1)) == 0 ? cudaSuccess : cudaErrorMemoryAllocation;
}
cudaError_t cudaHostAlloc(void** p, size_t bytes, unsigned) { return cudaMallocHost(p, bytes); }
cudaError_t cudaFreeHost(void* p) { free(p); return cudaSuccess; }

static cudaMemcpyKind resolveKind(void* dst, const void* src, cudaMemcpyKind kind) {
  if (kind != cudaMemcpyDefault) return kind;
  bool d = R().find((uint64_t)dst), s = R().find((uint64_t)src);
  return d ? (s ? cudaMemcpyDeviceToDevice : cudaMemcpyHostToDevice) : (s ? cudaMemcpyDeviceToHost : cudaMemcpyHostToHost);
}
cudaError_t cudaMemcpyAsync(void* dst, const void* src, size_t bytes, cudaMemcpyKind kind, cudaStream_t) {
  if (bytes == 0) return cudaSuccess;
  Runtime& r = R();
  std::lock_guard<std::recursive_mutex> l(r.mu);
  kind = resolveKind(dst, src, kind);
  switch (kind) {
    case cudaMemcpyHostToHost: memcpy(dst, src, bytes); break;
    case cudaMemcpyDeviceToHost:
      if (r.capturing) die("a device-to-host copy inside a captured graph");
      r.sync();
      memcpy(dst, r.host(src, bytes, "cudaMemcpy source"), bytes);
      break;
    case cudaMemcpyHostToDevice:
      if (!r.capturing && r.idle()) { memcpy(r.host(dst, bytes, "cudaMemcpy destination"), src, bytes); break; }
      {   // staged: the bytes now, the copy in stream order
        id<MTLBuffer> stage = [r.dev newBufferWithBytes:src length:bytes options:MTLResourceStorageModeShared];
        r.host(dst, bytes, "cudaMemcpy destination");
        if (r.capturing) {
          Op op{}; op.kind = 1; op.dst = (uint64_t)dst; op.src = stage.gpuAddress; op.bytes = bytes; op.keep.push_back(stage);
          r.capture->push_back(op);
        } else {
          r.ensureEncoder();
          [r.enc useResource:stage usage:MTLResourceUsageRead];
          r.cbKeep.push_back(stage);
          r.copy((uint64_t)dst, stage.gpuAddress, bytes);
        }
      }
      break;
    default:
      r.host(dst, bytes, "cudaMemcpy destination"); r.host(src, bytes, "cudaMemcpy source");
      r.copy((uint64_t)dst, (uint64_t)src, bytes);
  }
  return cudaSuccess;
}
cudaError_t cudaMemcpy(void* dst, const void* src, size_t bytes, cudaMemcpyKind kind) {
  cudaMemcpyAsync(dst, src, bytes, kind, nullptr);
  kind = resolveKind(dst, src, kind);
  if (kind == cudaMemcpyHostToDevice || kind == cudaMemcpyDeviceToDevice) {}   // (ordered; nothing on the host waits)
  return cudaSuccess;
}
cudaError_t cudaMemcpy2DAsync(void* dst, size_t dpitch, const void* src, size_t spitch, size_t width, size_t height,
                              cudaMemcpyKind kind, cudaStream_t s) {
  for (size_t r = 0; r < height; ++r)
    cudaMemcpyAsync((char*)dst + r * dpitch, (const char*)src + r * spitch, width, kind, s);
  return cudaSuccess;
}
cudaError_t cudaMemsetAsync(void* p, int value, size_t bytes, cudaStream_t) {
  if (bytes == 0) return cudaSuccess;
  Runtime& r = R();
  std::lock_guard<std::recursive_mutex> l(r.mu);
  void* h = r.host(p, bytes, "cudaMemset");
  if (!r.capturing && r.idle()) { memset(h, value, bytes); return cudaSuccess; }
  r.fill((uint64_t)p, value, bytes);
  return cudaSuccess;
}
cudaError_t cudaMemset(void* p, int value, size_t bytes) { return cudaMemsetAsync(p, value, bytes, nullptr); }
cudaError_t cudaMemset2DAsync(void* p, size_t pitch, int value, size_t width, size_t height, cudaStream_t s) {
  for (size_t r = 0; r < height; ++r) cudaMemsetAsync((char*)p + r * pitch, value, width, s);
  return cudaSuccess;
}
cudaError_t cudaMemGetInfo(size_t* free, size_t* total) {
  Runtime& r = R();
  size_t t = r.dev.recommendedMaxWorkingSetSize, used = r.dev.currentAllocatedSize;
  *total = t; *free = used < t ? t - used : 0;
  return cudaSuccess;
}
cudaError_t cudaGetDevice(int* d) { *d = 0; return cudaSuccess; }
cudaError_t cudaSetDevice(int) { return cudaSuccess; }
cudaError_t cudaGetDeviceCount(int* n) { *n = 1; return cudaSuccess; }
static int gpuCores() {
  // (the number of GPU cores: IOKit's gpu-core-count; an estimate from the working set where it is not readable)
  static int cores = [] {
    int c = 0;
    if (const char* e = getenv("LOCALFOLD_GPU_CORES")) c = atoi(e);
    if (!c) {
      FILE* p = popen("ioreg -rc AGXAccelerator -d1 2>/dev/null | grep -o '\"gpu-core-count\" = [0-9]*' | grep -o '[0-9]*$'", "r");
      if (p) { if (fscanf(p, "%d", &c) != 1) c = 0; pclose(p); }
    }
    return c > 0 ? c : 8;
  }();
  return cores;
}
cudaError_t cudaDeviceGetAttribute(int* v, cudaDeviceAttr a, int) {
  switch (a) {
    case cudaDevAttrMultiProcessorCount: *v = gpuCores(); break;
    // (a T4's - sm_75: the ports' register-staged paths, no cp.async, no bf16 tensor-core GEMMs)
    case cudaDevAttrComputeCapabilityMajor: *v = 7; break;
    case cudaDevAttrComputeCapabilityMinor: *v = 5; break;
    case cudaDevAttrMaxSharedMemoryPerBlockOptin:
    case cudaDevAttrMaxSharedMemoryPerBlock: *v = (int)R().dev.maxThreadgroupMemoryLength; break;
    case cudaDevAttrMaxSharedMemoryPerMultiprocessor: *v = 65536; break;
    case cudaDevAttrMaxThreadsPerBlock: *v = 1024; break;
    case cudaDevAttrL2CacheSize: *v = 8 << 20; break;
    default: *v = 0;
  }
  return cudaSuccess;
}
cudaError_t cudaDeviceSynchronize() { R().sync(); return cudaSuccess; }
cudaError_t cudaDeviceReset() { R().sync(); return cudaSuccess; }
cudaError_t cudaStreamSynchronize(cudaStream_t) { R().sync(); return cudaSuccess; }
cudaError_t cudaStreamCreate(cudaStream_t* s) { *s = (cudaStream_t)0x10; return cudaSuccess; }
cudaError_t cudaStreamCreateWithFlags(cudaStream_t* s, unsigned) { *s = (cudaStream_t)0x10; return cudaSuccess; }
cudaError_t cudaStreamDestroy(cudaStream_t) { return cudaSuccess; }
cudaError_t cudaStreamWaitEvent(cudaStream_t, cudaEvent_t, unsigned) { return cudaSuccess; }
cudaError_t cudaStreamQuery(cudaStream_t) { return R().idle() ? cudaSuccess : cudaErrorNotReady; }

struct LfEvent_ { id<MTLCommandBuffer> cb = nil; double host = 0; };
cudaError_t cudaEventCreate(cudaEvent_t* e) { *e = new LfEvent_(); return cudaSuccess; }
cudaError_t cudaEventCreateWithFlags(cudaEvent_t* e, unsigned) { return cudaEventCreate(e); }
cudaError_t cudaEventRecord(cudaEvent_t e, cudaStream_t) {
  Runtime& r = R();
  std::lock_guard<std::recursive_mutex> l(r.mu);
  if (r.capturing) return cudaSuccess;
  r.commit();
  e->cb = r.lastCommitted;
  e->host = std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count();
  return cudaSuccess;
}
cudaError_t cudaEventSynchronize(cudaEvent_t e) {
  if (e->cb) [e->cb waitUntilCompleted];
  return cudaSuccess;
}
cudaError_t cudaEventQuery(cudaEvent_t e) {
  return !e->cb || e->cb.status >= MTLCommandBufferStatusCompleted ? cudaSuccess : cudaErrorNotReady;
}
cudaError_t cudaEventElapsedTime(float* ms, cudaEvent_t a, cudaEvent_t b) {
  cudaEventSynchronize(a); cudaEventSynchronize(b);
  // (the GPU's end of the work before each: the time the queue took between them)
  double ta = a->cb ? a->cb.GPUEndTime : a->host, tb = b->cb ? b->cb.GPUEndTime : b->host;
  if (!a->cb || !b->cb) { ta = a->host; tb = b->host; }
  *ms = (float)((tb - ta) * 1e3);
  if (*ms < 0) *ms = 0;
  return cudaSuccess;
}
cudaError_t cudaEventDestroy(cudaEvent_t e) { delete e; return cudaSuccess; }
cudaError_t cudaGetLastError() { cudaError_t e = LAST_ERROR; LAST_ERROR = cudaSuccess; return e; }
cudaError_t cudaPeekAtLastError() { return LAST_ERROR; }
const char* cudaGetErrorString(cudaError_t e) {
  switch (e) {
    case cudaSuccess: return "no error";
    case cudaErrorMemoryAllocation: return "out of memory";
    case cudaErrorNotReady: return "not ready";
    default: return "invalid value";
  }
}
const char* cudaGetErrorName(cudaError_t e) { return cudaGetErrorString(e); }

struct LfGraph_ { std::vector<Op> ops; };
cudaError_t cudaStreamBeginCapture(cudaStream_t, cudaStreamCaptureMode) {
  Runtime& r = R();
  std::lock_guard<std::recursive_mutex> l(r.mu);
  r.capturing = true;
  r.capture = new std::vector<Op>();
  return cudaSuccess;
}
cudaError_t cudaStreamEndCapture(cudaStream_t, cudaGraph_t* g) {
  Runtime& r = R();
  std::lock_guard<std::recursive_mutex> l(r.mu);
  r.capturing = false;
  *g = new LfGraph_{std::move(*r.capture)};
  delete r.capture; r.capture = nullptr;
  return cudaSuccess;
}
cudaError_t cudaStreamIsCapturing(cudaStream_t, cudaStreamCaptureStatus* s) {
  *s = R().capturing ? cudaStreamCaptureStatusActive : cudaStreamCaptureStatusNone;
  return cudaSuccess;
}
// (an executable graph is its own copy: the ports destroy the graph once it is instantiated)
cudaError_t cudaGraphInstantiate(cudaGraphExec_t* exec, cudaGraph_t g, unsigned long long) { *exec = new LfGraph_(*g); return cudaSuccess; }
cudaError_t cudaGraphInstantiate(cudaGraphExec_t* exec, cudaGraph_t g, cudaGraphNode_t*, char*, size_t) { *exec = new LfGraph_(*g); return cudaSuccess; }
cudaError_t cudaGraphLaunch(cudaGraphExec_t exec, cudaStream_t) {
  Runtime& r = R();
  std::lock_guard<std::recursive_mutex> l(r.mu);
  for (auto& op : exec->ops) {
    if (op.kind == 0) r.dispatch(op.pso, op.args.data(), op.args.size(), op.grid, op.block, op.smem);
    else if (op.kind == 1) {
      if (!op.keep.empty()) { r.ensureEncoder(); for (auto& k : op.keep) [r.enc useResource:k usage:MTLResourceUsageRead]; }
      r.copy(op.dst, op.src, op.bytes);
    } else r.fill(op.dst, op.value, op.bytes);
  }
  return cudaSuccess;
}
cudaError_t cudaGraphExecDestroy(cudaGraphExec_t e) { delete e; return cudaSuccess; }
cudaError_t cudaGraphDestroy(cudaGraph_t g) { delete g; return cudaSuccess; }

struct LfMemPool_ { int unused; };
cudaError_t cudaMemPoolCreate(cudaMemPool_t* p, const cudaMemPoolProps*) { *p = new LfMemPool_(); return cudaSuccess; }
cudaError_t cudaDeviceGetDefaultMemPool(cudaMemPool_t* p, int) { static LfMemPool_ pool; *p = &pool; return cudaSuccess; }
cudaError_t cudaMemPoolSetAttribute(cudaMemPool_t, cudaMemPoolAttr, void*) { return cudaSuccess; }
cudaError_t cudaMemPoolGetAttribute(cudaMemPool_t, cudaMemPoolAttr a, void* v) {
  // (nothing is held idle: an allocation is freed when the port frees it)
  *(uint64_t*)v = (a == cudaMemPoolAttrReservedMemCurrent || a == cudaMemPoolAttrUsedMemCurrent) ? R().allocated : 0;
  return cudaSuccess;
}
cudaError_t cudaMemPoolTrimTo(cudaMemPool_t, size_t) { return cudaSuccess; }
cudaError_t lfSymbolAddress(void** p, const void* host, size_t bytes) {
  static std::map<const void*, void*> copies;
  Runtime& r = R();
  std::lock_guard<std::recursive_mutex> l(r.mu);
  auto it = copies.find(host);
  if (it == copies.end()) {
    void* d = r.malloc_(bytes);
    r.sync();
    memcpy(r.host(d), host, bytes);
    it = copies.emplace(host, d).first;
  }
  *p = it->second;
  return cudaSuccess;
}

// ---------------------------------------------------------------- cuBLAS
struct LfBlas_ { int unused; };
cublasStatus_t cublasCreate(cublasHandle_t* h) { *h = new LfBlas_(); return CUBLAS_STATUS_SUCCESS; }
cublasStatus_t cublasDestroy(cublasHandle_t h) { delete h; return CUBLAS_STATUS_SUCCESS; }
cublasStatus_t cublasSetStream(cublasHandle_t, cudaStream_t) { return CUBLAS_STATUS_SUCCESS; }
cublasStatus_t cublasSetWorkspace(cublasHandle_t, void*, size_t) { return CUBLAS_STATUS_SUCCESS; }
cublasStatus_t cublasSetMathMode(cublasHandle_t, cublasMath_t) { return CUBLAS_STATUS_SUCCESS; }

namespace {
const char* typeTag(cudaDataType t) {
  switch (t) {
    case CUDA_R_32F: return "f32";
    case CUDA_R_16F: return "f16";
    case CUDA_R_16BF: return "bf16";
    default: die("a GEMM of an unsupported data type " + std::to_string((int)t));
  }
}
struct GemmArgs {
  uint64_t A, B, C, D, bias;
  int64_t sa, sb, sc, sd;
  int32_t m, n, k, lda, ldb, ldc, ldd;
  int32_t ta, tb, ptrs, epilogue, biasType;
  float alpha, beta;
};
void gemm(cudaDataType ta_, cudaDataType tb_, cudaDataType tc_, GemmArgs a, int batch) {
  if (a.m <= 0 || a.n <= 0 || batch <= 0) return;
  Runtime& r = R();
  std::lock_guard<std::recursive_mutex> l(r.mu);
  std::string name = std::string("lf_gemm_") + typeTag(ta_) + "_" + typeTag(tb_) + "_" + typeTag(tc_);
  MTLSize grid = MTLSizeMake((a.m + 63) / 64, (a.n + 63) / 64, batch);
  r.dispatch(r.shimPipeline(name), &a, sizeof a, grid, MTLSizeMake(128, 1, 1), 0, r.profiling ? "gemm" : "");
}
float scalar(const void* p, cublasComputeType_t compute) {
  if (compute == CUBLAS_COMPUTE_16F) return (float)*(const __half*)p;
  return *(const float*)p;
}
}  // namespace

cublasStatus_t cublasSgemm(cublasHandle_t, cublasOperation_t ta, cublasOperation_t tb, int m, int n, int k,
                           const float* alpha, const float* A, int lda, const float* B, int ldb, const float* beta, float* C, int ldc) {
  GemmArgs a{(uint64_t)A, (uint64_t)B, (uint64_t)C, (uint64_t)C, 0, 0, 0, 0, 0, m, n, k, lda, ldb, ldc, ldc,
             ta != CUBLAS_OP_N, tb != CUBLAS_OP_N, 0, 0, 0, *alpha, *beta};
  gemm(CUDA_R_32F, CUDA_R_32F, CUDA_R_32F, a, 1);
  return CUBLAS_STATUS_SUCCESS;
}
cublasStatus_t cublasSgemmStridedBatched(cublasHandle_t, cublasOperation_t ta, cublasOperation_t tb, int m, int n, int k,
                                         const float* alpha, const float* A, int lda, long long sa, const float* B, int ldb,
                                         long long sb, const float* beta, float* C, int ldc, long long sc, int batch) {
  GemmArgs a{(uint64_t)A, (uint64_t)B, (uint64_t)C, (uint64_t)C, 0, sa, sb, sc, sc, m, n, k, lda, ldb, ldc, ldc,
             ta != CUBLAS_OP_N, tb != CUBLAS_OP_N, 0, 0, 0, *alpha, *beta};
  gemm(CUDA_R_32F, CUDA_R_32F, CUDA_R_32F, a, batch);
  return CUBLAS_STATUS_SUCCESS;
}
cublasStatus_t cublasGemmEx(cublasHandle_t, cublasOperation_t ta, cublasOperation_t tb, int m, int n, int k,
                            const void* alpha, const void* A, cudaDataType ta_, int lda, const void* B, cudaDataType tb_, int ldb,
                            const void* beta, void* C, cudaDataType tc_, int ldc, cublasComputeType_t compute, cublasGemmAlgo_t) {
  GemmArgs a{(uint64_t)A, (uint64_t)B, (uint64_t)C, (uint64_t)C, 0, 0, 0, 0, 0, m, n, k, lda, ldb, ldc, ldc,
             ta != CUBLAS_OP_N, tb != CUBLAS_OP_N, 0, 0, 0, scalar(alpha, compute), scalar(beta, compute)};
  gemm(ta_, tb_, tc_, a, 1);
  return CUBLAS_STATUS_SUCCESS;
}
cublasStatus_t cublasGemmStridedBatchedEx(cublasHandle_t, cublasOperation_t ta, cublasOperation_t tb, int m, int n, int k,
                                          const void* alpha, const void* A, cudaDataType ta_, int lda, long long sa,
                                          const void* B, cudaDataType tb_, int ldb, long long sb, const void* beta,
                                          void* C, cudaDataType tc_, int ldc, long long sc, int batch,
                                          cublasComputeType_t compute, cublasGemmAlgo_t) {
  GemmArgs a{(uint64_t)A, (uint64_t)B, (uint64_t)C, (uint64_t)C, 0, sa, sb, sc, sc, m, n, k, lda, ldb, ldc, ldc,
             ta != CUBLAS_OP_N, tb != CUBLAS_OP_N, 0, 0, 0, scalar(alpha, compute), scalar(beta, compute)};
  gemm(ta_, tb_, tc_, a, batch);
  return CUBLAS_STATUS_SUCCESS;
}
cublasStatus_t cublasGemmBatchedEx(cublasHandle_t, cublasOperation_t ta, cublasOperation_t tb, int m, int n, int k,
                                   const void* alpha, const void* const A[], cudaDataType ta_, int lda,
                                   const void* const B[], cudaDataType tb_, int ldb, const void* beta,
                                   void* const C[], cudaDataType tc_, int ldc, int batch,
                                   cublasComputeType_t compute, cublasGemmAlgo_t) {
  GemmArgs a{(uint64_t)A, (uint64_t)B, (uint64_t)C, (uint64_t)C, 0, 0, 0, 0, 0, m, n, k, lda, ldb, ldc, ldc,
             ta != CUBLAS_OP_N, tb != CUBLAS_OP_N, 1, 0, 0, scalar(alpha, compute), scalar(beta, compute)};
  gemm(ta_, tb_, tc_, a, batch);
  return CUBLAS_STATUS_SUCCESS;
}
cublasStatus_t cublasSscal(cublasHandle_t, int n, const float* alpha, float* x, int incx) {
  Runtime& r = R();
  std::lock_guard<std::recursive_mutex> l(r.mu);
  struct { uint64_t x; int32_t n, inc; float alpha; } a = {(uint64_t)x, n, incx, *alpha};
  r.dispatch(r.shimPipeline("lf_scal"), &a, sizeof a, MTLSizeMake((n + 255) / 256, 1, 1), MTLSizeMake(256, 1, 1), 0);
  return CUBLAS_STATUS_SUCCESS;
}

// ---------------------------------------------------------------- cuBLASLt
struct LfLt_ { int unused; };
struct LfLtPref_ { int unused; };
cublasStatus_t cublasLtCreate(cublasLtHandle_t* h) { *h = new LfLt_(); return CUBLAS_STATUS_SUCCESS; }
cublasStatus_t cublasLtDestroy(cublasLtHandle_t h) { delete h; return CUBLAS_STATUS_SUCCESS; }
cublasStatus_t cublasLtMatmulDescCreate(cublasLtMatmulDesc_t* d, cublasComputeType_t compute, cudaDataType scale) {
  *d = new LfLtDesc(); (*d)->compute = compute; (*d)->scale = scale; return CUBLAS_STATUS_SUCCESS;
}
cublasStatus_t cublasLtMatmulDescDestroy(cublasLtMatmulDesc_t d) { delete d; return CUBLAS_STATUS_SUCCESS; }
cublasStatus_t cublasLtMatmulDescSetAttribute(cublasLtMatmulDesc_t d, cublasLtMatmulDescAttributes_t a, const void* v, size_t) {
  switch (a) {
    case CUBLASLT_MATMUL_DESC_TRANSA: d->ta = *(const int*)v; break;
    case CUBLASLT_MATMUL_DESC_TRANSB: d->tb = *(const int*)v; break;
    case CUBLASLT_MATMUL_DESC_EPILOGUE: d->epilogue = *(const int*)v; break;
    case CUBLASLT_MATMUL_DESC_BIAS_POINTER: d->bias = *(const void* const*)v; break;
    case CUBLASLT_MATMUL_DESC_BIAS_DATA_TYPE: d->biasType = *(const int*)v; break;
    default: break;
  }
  return CUBLAS_STATUS_SUCCESS;
}
cublasStatus_t cublasLtMatrixLayoutCreate(cublasLtMatrixLayout_t* l, cudaDataType type, uint64_t rows, uint64_t cols, int64_t ld) {
  *l = new LfLtLayout(); (*l)->type = type; (*l)->rows = rows; (*l)->cols = cols; (*l)->ld = ld;
  return CUBLAS_STATUS_SUCCESS;
}
cublasStatus_t cublasLtMatrixLayoutDestroy(cublasLtMatrixLayout_t l) { delete l; return CUBLAS_STATUS_SUCCESS; }
cublasStatus_t cublasLtMatrixLayoutSetAttribute(cublasLtMatrixLayout_t l, cublasLtMatrixLayoutAttribute_t a, const void* v, size_t) {
  switch (a) {
    case CUBLASLT_MATRIX_LAYOUT_BATCH_COUNT: l->batch = *(const int*)v; break;
    case CUBLASLT_MATRIX_LAYOUT_STRIDED_BATCH_OFFSET: l->stride = *(const long long*)v; break;
    case CUBLASLT_MATRIX_LAYOUT_ORDER: l->order = *(const int*)v; break;
    case CUBLASLT_MATRIX_LAYOUT_LD: l->ld = *(const long long*)v; break;
    default: break;
  }
  return CUBLAS_STATUS_SUCCESS;
}
cublasStatus_t cublasLtMatmulPreferenceCreate(cublasLtMatmulPreference_t* p) { *p = new LfLtPref_(); return CUBLAS_STATUS_SUCCESS; }
cublasStatus_t cublasLtMatmulPreferenceDestroy(cublasLtMatmulPreference_t p) { delete p; return CUBLAS_STATUS_SUCCESS; }
cublasStatus_t cublasLtMatmulPreferenceSetAttribute(cublasLtMatmulPreference_t, cublasLtMatmulPreferenceAttributes_t, const void*, size_t) {
  return CUBLAS_STATUS_SUCCESS;
}
cublasStatus_t cublasLtMatmulAlgoGetHeuristic(cublasLtHandle_t, cublasLtMatmulDesc_t, cublasLtMatrixLayout_t, cublasLtMatrixLayout_t,
                                              cublasLtMatrixLayout_t, cublasLtMatrixLayout_t, cublasLtMatmulPreference_t,
                                              int requested, cublasLtMatmulHeuristicResult_t* out, int* got) {
  if (requested > 0) { memset(out, 0, sizeof *out); out[0].state = CUBLAS_STATUS_SUCCESS; *got = 1; } else *got = 0;
  return CUBLAS_STATUS_SUCCESS;
}
cublasStatus_t cublasLtMatmulAlgoConfigGetAttribute(const cublasLtMatmulAlgo_t*, cublasLtMatmulAlgoConfigAttributes_t a,
                                                    void* v, size_t n, size_t* written) {
  memset(v, 0, n);
  if (a == CUBLASLT_ALGO_CONFIG_TILE_ID && n >= 4) *(int*)v = CUBLASLT_MATMUL_TILE_128x128;
  if (written) *written = n;
  return CUBLAS_STATUS_SUCCESS;
}
cublasStatus_t cublasLtMatmul(cublasLtHandle_t, cublasLtMatmulDesc_t d, const void* alpha, const void* A, cublasLtMatrixLayout_t la,
                              const void* B, cublasLtMatrixLayout_t lb, const void* beta, const void* C, cublasLtMatrixLayout_t lc,
                              void* D, cublasLtMatrixLayout_t ld, const cublasLtMatmulAlgo_t*, void*, size_t, cudaStream_t) {
  if (la->order || lb->order || lc->order || ld->order) die("cuBLASLt with a row-major layout");
  int m = (int)ld->rows, n = (int)ld->cols, k = d->ta ? (int)la->rows : (int)la->cols;
  int epi = d->epilogue == CUBLASLT_EPILOGUE_RELU ? 2 : d->epilogue == CUBLASLT_EPILOGUE_BIAS ? 4
          : d->epilogue == CUBLASLT_EPILOGUE_RELU_BIAS ? 6 : d->epilogue == CUBLASLT_EPILOGUE_GELU ? 32
          : d->epilogue == CUBLASLT_EPILOGUE_GELU_BIAS ? 36 : 0;
  int biasType = d->biasType ? d->biasType : ld->type;
  GemmArgs a{(uint64_t)A, (uint64_t)B, (uint64_t)C, (uint64_t)D, (uint64_t)d->bias, la->stride, lb->stride, lc->stride, ld->stride,
             m, n, k, (int)la->ld, (int)lb->ld, (int)lc->ld, (int)ld->ld, d->ta != 0, d->tb != 0, 0, epi, biasType,
             scalar(alpha, (cublasComputeType_t)d->compute), scalar(beta, (cublasComputeType_t)d->compute)};
  if ((cudaDataType)lc->type != (cudaDataType)ld->type && *(const float*)beta != 0.f) die("cuBLASLt with C and D of different types");
  gemm((cudaDataType)la->type, (cudaDataType)lb->type, (cudaDataType)ld->type, a, std::max(ld->batch, 1));
  return CUBLAS_STATUS_SUCCESS;
}
