#!/usr/bin/env bash
# Build the Metal ports for this Mac - the CUDA ports (cuda/*/src) translated, compiled against metal/shim:
#
#   bash metal/build.sh [af3] [af2] [ef2]       ->  metal/<port>/localfold-<port>   (all three when none is named)
#   bash metal/build.sh check                   ->  metal/check/check-kernels
#
# Each port is cuda/<port>/src translated by metal/tools/cu2metal.py into metal/build/<port> (host code as
# Objective-C++, device code as one Metal source), then linked with metal/shim (the CUDA runtime and cuBLAS on
# Metal) and cuda/featurise's standalone object (the native featuriser, built by clang here). Only the
# command-line tools are needed: the Metal source is compiled at run time.
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
repo="$(dirname "$here")"
ports=("$@"); [ ${#ports[@]} -gt 0 ] || ports=(af3 af2 ef2)
flags=(-std=c++17 -fobjc-arc -Wno-deprecated-declarations -Wno-unused-result -framework Metal -framework Foundation)
opt="${LOCALFOLD_METAL_OPT:--O2}"

# the Metal source as a C++ string, with its prelude inlined (the runtime compiler has no include path)
embed() {   # embed <metal file> <prelude dir> <symbol>
  python3 - "$1" "$2" "$3" <<'EOF'
import sys
src = open(sys.argv[1]).read()
pre = open(sys.argv[2] + "/prelude.metal").read()
src = src.replace('#include "prelude.metal"', pre)
# (a raw string literal in pieces: one literal is limited in length by some compilers)
parts = [src[i:i + 60000] for i in range(0, len(src), 60000)]
print(f"const char* {sys.argv[3]} = " + "\n".join(f'R"LFSRC({p})LFSRC"' for p in parts) + ";")
EOF
}

for port in "${ports[@]}"; do
  if [ "$port" = check ]; then
    inc="$here/kernels.inc"
    { echo '// GENERATED by metal/build.sh - do not edit'
      for source in "$here"/kernels/*.metal; do echo "R\"LOCALFOLDMETAL(// --- $(basename "$source")"; cat "$source"; echo ')LOCALFOLDMETAL"'; done
    } > "$inc.tmp" && mv "$inc.tmp" "$inc"
    clang++ "${flags[@]}" -O2 "$here/check/check-kernels.mm" -o "$here/check/check-kernels"
    echo "built metal/check/check-kernels"
    continue
  fi
  case "$port" in af3|af2|ef2) ;; *) echo "unknown port $port (af3, af2, ef2, check)" >&2; exit 1 ;; esac
  out="$here/build/$port"
  mkdir -p "$out"
  overrides="$here/$port/overrides.txt"
  python3 "$here/tools/cu2metal.py" --root="$repo/cuda/$port/src/$port.cu" --out="$out" --overrides="$overrides" | grep -v "^  untranslated" || true
  # the port's kernel table and source, and the runtime's own kernels
  {
    echo '// GENERATED by metal/build.sh - do not edit'
    echo '#include "lfcuda.h"'
    echo 'namespace lf {'
    echo 'extern const KernelInfo PORT_KERNELS[] = {'
    cat "$out/gen/lf_kernels.inc"
    echo '};'
    echo "extern const int PORT_KERNEL_COUNT = sizeof(PORT_KERNELS) / sizeof(PORT_KERNELS[0]);"
    echo "extern const char* PORT_NAME = \"$port\";"
    # (the port's hand-written Metal kernels, appended to the translation)
    cat "$out/kernels.metal" > "$out/kernels.all.metal"
    for extra in "$here/$port"/*.metal; do [ -f "$extra" ] && cat "$extra" >> "$out/kernels.all.metal"; done
    embed "$out/kernels.all.metal" "$here/shim" "PORT_SOURCE_" | sed 's/^const char\* /extern const char* /'
    echo "extern const char* PORT_SOURCE = PORT_SOURCE_;"
    embed "$here/shim/shim.metal" "$here/shim" "SHIM_SOURCE" | sed 's/^const char\* /extern const char* /'
    echo '}'
  } > "$out/lfport.mm"
  # the featuriser's standalone object, by clang (cuda/build.sh featurise builds it the same way)
  sobj="$repo/cuda/featurise/standalone.o"
  if [ ! -f "$sobj" ] || [ -n "$(find "$repo/cuda/featurise" -newer "$sobj" \( -name '*.h' -o -name '*.inc' -o -name '*.cpp' \) | head -1)" ]; then
    clang++ -std=c++17 -O2 -ffp-contract=off -pthread -c "$repo/cuda/featurise/standalone.cpp" -o "$sobj"
  fi
  mkdir -p "$here/$port"
  clang++ "${flags[@]}" $opt -I "$here/shim/include" -I "$here/shim" -I "$out/gen" -x objective-c++ \
    "$out/gen/$port/src/$port.cu" "$out/lfport.mm" "$here/shim/lfcuda.mm" -x none "$sobj" \
    -o "$here/$port/localfold-$port.building"
  mv "$here/$port/localfold-$port.building" "$here/$port/localfold-$port"
  echo "built metal/$port/localfold-$port"
done
