#!/usr/bin/env bash
# Build the Metal port's binaries for this Mac:
#
#   bash metal/build.sh            ->  metal/check/check-kernels
#
# Every metal/kernels/*.metal is embedded in the binary as one source string
# (metal/kernels.inc, generated here and not checked in) and compiled at
# start-up - the offline `metal` compiler needs a full Xcode, and this needs
# only the command-line tools (clang++ and the system frameworks).
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"

inc="$here/kernels.inc"
{
  echo '// GENERATED by metal/build.sh from metal/kernels/*.metal - do not edit.'
  for source in "$here"/kernels/*.metal; do
    echo "R\"LOCALFOLDMETAL(// --- $(basename "$source")"
    cat "$source"
    echo ')LOCALFOLDMETAL"'
  done
} > "$inc.tmp"
mv "$inc.tmp" "$inc"

flags=(-std=c++17 -O2 -fobjc-arc -Wall -Wno-unused-function -framework Metal -framework Foundation)
clang++ "${flags[@]}" "$here/check/check-kernels.mm" -o "$here/check/check-kernels.tmp"
mv "$here/check/check-kernels.tmp" "$here/check/check-kernels"
echo "built metal/check/check-kernels"
