// The Metal port's host runtime: one device, one queue, one library compiled
// from the kernel sources embedded in the binary (kernels.inc, generated by
// metal/build.sh), and pipelines by name.
//
// Objective-C++ rather than Swift, deliberately: the native featuriser
// (cuda/featurise) and the CUDA port's host logic are C++, and a .mm links
// them as they are. No metal-cpp download either - the system frameworks only.
//
// 🔴 THE KERNELS ARE COMPILED AT START-UP FROM SOURCE, because the offline
// `metal` compiler ships with Xcode and not with the command-line tools this
// box has. `compileMs` in Runtime says what that costs; a .metallib built
// offline is the fix if it ever matters.
#pragma once
#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <string>
#include <unordered_map>

namespace lfmetal {

[[noreturn]] inline void fail(const std::string& message) {
  std::fprintf(stderr, "localfold-metal: %s\n", message.c_str());
  std::exit(1);
}

struct Runtime {
  id<MTLDevice> device = nil;
  id<MTLCommandQueue> queue = nil;
  id<MTLLibrary> library = nil;
  double compileMs = 0;
  std::unordered_map<std::string, id<MTLComputePipelineState>> pipelines;

  explicit Runtime(const std::string& source) {
    // MTLCreateSystemDefaultDevice returns nil to a command-line process with
    // no window server session (it says so on stderr), so take the first device.
    NSArray<id<MTLDevice>>* devices = MTLCopyAllDevices();
    if (devices.count == 0) fail("no Metal device");
    device = devices[0];
    queue = [device newCommandQueue];
    MTLCompileOptions* options = [MTLCompileOptions new];
    options.fastMathEnabled = YES;
    auto start = std::chrono::steady_clock::now();
    NSError* error = nil;
    library = [device newLibraryWithSource:[NSString stringWithUTF8String:source.c_str()] options:options error:&error];
    compileMs = std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - start).count();
    if (!library) fail(std::string("kernel compile: ") + error.localizedDescription.UTF8String);
  }

  std::string name() const { return device.name.UTF8String; }

  // 🔴 A PIPELINE THAT CANNOT LAUNCH THE THREADS ASKED FOR IS REFUSED HERE.
  // maxTotalThreadsPerThreadgroup falls with register use, and a dispatch past
  // it does not run - no error, an unchanged output, and a GPU time so short it
  // read as a 2x win in the prototype (a 64-row transition tile, relRMS 1.0).
  id<MTLComputePipelineState> pipeline(const std::string& entry, NSUInteger threads) {
    auto found = pipelines.find(entry);
    if (found == pipelines.end()) {
      id<MTLFunction> function = [library newFunctionWithName:[NSString stringWithUTF8String:entry.c_str()]];
      if (!function) fail("no kernel named " + entry);
      NSError* error = nil;
      id<MTLComputePipelineState> state = [device newComputePipelineStateWithFunction:function error:&error];
      if (!state) fail(entry + ": " + error.localizedDescription.UTF8String);
      found = pipelines.emplace(entry, state).first;
    }
    if (found->second.maxTotalThreadsPerThreadgroup < threads) {
      fail(entry + " needs " + std::to_string(threads) + " threads a threadgroup and this device allows "
           + std::to_string(found->second.maxTotalThreadsPerThreadgroup));
    }
    return found->second;
  }

  // Shared storage: on unified memory the host writes and reads the same bytes
  // the GPU does, with no upload.
  id<MTLBuffer> buffer(size_t bytes, const void* contents = nullptr) {
    id<MTLBuffer> made = contents
        ? [device newBufferWithBytes:contents length:bytes options:MTLResourceStorageModeShared]
        : [device newBufferWithLength:bytes options:MTLResourceStorageModeShared];
    if (!made) fail("could not allocate " + std::to_string(bytes) + " bytes");
    return made;
  }

  // Encodes `encode` into one command buffer, runs it, and returns the GPU
  // time in milliseconds. A command buffer error is fatal: a kernel that faulted
  // has not computed anything worth timing.
  template <typename Encode>
  double run(Encode encode) {
    id<MTLCommandBuffer> commands = [queue commandBuffer];
    id<MTLComputeCommandEncoder> encoder = [commands computeCommandEncoder];
    encode(encoder);
    [encoder endEncoding];
    [commands commit];
    [commands waitUntilCompleted];
    if (commands.error) fail(std::string("command buffer: ") + commands.error.localizedDescription.UTF8String);
    return (commands.GPUEndTime - commands.GPUStartTime) * 1e3;
  }
};

}  // namespace lfmetal
