// metal/core/core.h's implementation: the device, memory, the queue, kernels, the GEMM's dispatch.
#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#include "core.h"
#include "model.h"
#include <fcntl.h>
#include <sys/mman.h>
#include <unistd.h>
#include <mach-o/dyld.h>
#include <sys/stat.h>
#include <algorithm>
#include <atomic>
#include <chrono>
#include <climits>
#include <condition_variable>
#include <cstdarg>
#include <cstring>
#include <fstream>
#include <future>
#include <mutex>
#include <set>
#include <sstream>
#include <thread>
#include <unordered_map>

namespace mt {
extern const char* GEMM_SOURCE;             // args.h + gemm.metal (generated by metal/build.sh)
extern const char* TENSOR_SOURCE;           // args.h + gemm.metal + gemm_tensor.metal: the matrix units' GEMM (MSL 4.0)

void die(const char* fmt, ...) {
  va_list ap; va_start(ap, fmt);
  fprintf(stderr, "localfold-metal: ");
  vfprintf(stderr, fmt, ap);
  fprintf(stderr, "\n");
  va_end(ap);
  fflush(stderr);
  std::exit(1);
}

namespace {
struct Alloc { id<MTLBuffer> buf; uint64_t addr; size_t size; };
struct Stats { double syncMs = 0, compileMs = 0; long dispatches = 0, commits = 0, syncs = 0, staged = 0, allocs = 0, gemms = 0; };

struct Device {
  std::recursive_mutex mu;
  id<MTLDevice> dev;
  id<MTLCommandQueue> queue;
  std::map<uint64_t, Alloc> allocs;
  size_t held = 0, peak = 0, buried = 0, peakLive = 0;     // (live: held and the graveyard's, still resident)
  id<MTLCommandBuffer> cb = nil;
  id<MTLComputeCommandEncoder> enc = nil;
  std::vector<id<MTLBuffer>> keep;           // staged and argument buffers, alive until this command buffer is done
  // released buffers, each alive until every command buffer committed up to its tag is done (Metal may complete a
  // later command buffer before an earlier one it sees no dependency on)
  std::vector<std::pair<long, id<MTLBuffer>>> graveyard;
  int encoded = 0;
  std::mutex inflightMu; std::condition_variable inflightDone; std::set<long> pending; long committedSeq = 0;
  std::mutex errorMu; std::string gpuError;
  // kernels
  std::string portName = "core";
  const char* portSource = nullptr;
  id<MTLLibrary> lib = nil;
  std::mutex libMu;
  std::unordered_map<std::string, id<MTLComputePipelineState>> pipelines;
  std::set<std::string> knownSpecs; std::string specsPath; bool specsLoaded = false;
  std::map<std::string, std::string> specDecls;
  // the matrix units through Metal 4's tensor operations (gemm_tensor.metal): an Apple10 GPU (M5) on macOS 26
  bool tensorOps = false;
  // profiling
  bool profileOn = false;
  std::vector<std::pair<std::string, id<MTLCommandBuffer>>> profiled;
  Stats stats;
  // scratch
  std::map<std::string, std::pair<void*, size_t>> scratch;

  Device() {
    @autoreleasepool {
      NSArray<id<MTLDevice>>* devices = MTLCopyAllDevices();
      if (devices.count == 0) die("no Metal device");
      dev = devices[0];
      if (![dev supportsFamily:MTLGPUFamilyMetal3] || ![dev supportsFamily:MTLGPUFamilyApple7])
        die("this GPU (%s) is not an Apple-silicon GPU with Metal 3; LocalFold needs an M1 or later", dev.name.UTF8String);
      queue = [dev newCommandQueueWithMaxCommandBufferCount:64];
      if (@available(macOS 26.0, *)) tensorOps = [dev supportsFamily:MTLGPUFamilyApple10];
    }
  }

  // ---- memory
  const Alloc* find(uint64_t addr) {
    auto it = allocs.upper_bound(addr);
    if (it == allocs.begin()) return nullptr;
    --it;
    if (addr >= it->second.addr && addr < it->second.addr + std::max<size_t>(it->second.size, 1)) return &it->second;
    return nullptr;
  }
  void* alloc(size_t bytes) {
    std::lock_guard<std::recursive_mutex> l(mu);
    size_t n = std::max<size_t>((bytes + 255) & ~(size_t)255, 256);
    // released buffers the work in flight may still read are kept until it is done; past a bound, wait for it rather
    // than hold both (a 522-token trunk pass held 0.9 GB of them beside its own 1.9). LOCALFOLD_BURIED_MB: the bound
    static const size_t bound = (size_t)(getenv("LOCALFOLD_BURIED_MB") ? atof(getenv("LOCALFOLD_BURIED_MB")) : 128) << 20;
    if (buried >= bound) sync();
    id<MTLBuffer> b = [dev newBufferWithLength:n options:MTLResourceStorageModeShared];
    if (!b) die("out of memory: %.2f GB asked for with %.2f GB held", bytes / 1e9, held / 1e9);
    ++stats.allocs;
    uint64_t addr = b.gpuAddress;
    allocs[addr] = {b, addr, n};
    held += n; peak = std::max(peak, held); peakLive = std::max(peakLive, held + buried);
    if (enc) [enc useResource:b usage:MTLResourceUsageRead | MTLResourceUsageWrite];
    return (void*)addr;
  }
  void release(const void* p) {
    if (!p) return;
    std::lock_guard<std::recursive_mutex> l(mu);
    static const bool syncRelease = getenv("LOCALFOLD_SYNC_RELEASE") != nullptr;    // (debugging: lifetimes)
    if (syncRelease) sync();
    auto it = allocs.find((uint64_t)p);
    if (it == allocs.end()) die("release of a pointer that is not an allocation's start");
    held -= it->second.size;
    if (!idle()) { graveyard.push_back({committedSeq + (cb ? 1 : 0), it->second.buf}); buried += it->second.size; }   // (work issued may read it)
    allocs.erase(it);
  }
  void* host(const void* p, size_t bytes = 0) {
    const Alloc* a = find((uint64_t)p);
    if (!a) die("not a device pointer: %p", p);
    if ((uint64_t)p + bytes > a->addr + a->size) die("a host access past the end of its allocation");
    return (char*)a->buf.contents + ((uint64_t)p - a->addr);
  }

  // ---- the queue
  bool idle() { std::lock_guard<std::mutex> g(inflightMu); return !cb && pending.empty(); }
  void ensureEncoder() {
    if (enc) return;
    if (!cb) cb = [queue commandBufferWithUnretainedReferences];
    enc = [cb computeCommandEncoderWithDispatchType:MTLDispatchTypeSerial];
    std::vector<id<MTLResource>> all;
    all.reserve(allocs.size() + keep.size());
    for (auto& [_, a] : allocs) all.push_back(a.buf);
    for (auto& b : keep) all.push_back(b);
    // (not the graveyard's: released buffers are read by no new work, and one named resident by a command buffer still in
    // flight when the graveyard frees it is an "Invalid Resource" failure of that command buffer, though it never reads it)
    if (!all.empty()) [enc useResources:all.data() count:all.size() usage:MTLResourceUsageRead | MTLResourceUsageWrite];
  }
  void commit() {
    if (enc) { [enc endEncoding]; enc = nil; }
    if (!cb) return;
    if (!keep.empty()) {
      __block std::vector<id<MTLBuffer>> k = std::move(keep);
      keep.clear();
      [cb addCompletedHandler:^(id<MTLCommandBuffer>) { k.clear(); }];
    }
    long seq;
    { std::lock_guard<std::mutex> g(inflightMu); seq = ++committedSeq; pending.insert(seq); }
    [cb addCompletedHandler:^(id<MTLCommandBuffer> done) {
      if (done.error) {
        std::lock_guard<std::mutex> g(errorMu);
        if (gpuError.empty()) gpuError = done.error.localizedDescription.UTF8String;
      }
      { std::lock_guard<std::mutex> g(inflightMu); pending.erase(seq); }
      inflightDone.notify_all();
    }];
    [cb commit];
    ++stats.commits;
    bury();
    cb = nil;
    encoded = 0;
  }
  void bury() {               // the released buffers no command buffer in flight can read
    if (graveyard.empty()) return;
    long oldest;
    { std::lock_guard<std::mutex> g(inflightMu); oldest = pending.empty() ? LONG_MAX : *pending.begin(); }
    graveyard.erase(std::remove_if(graveyard.begin(), graveyard.end(), [&](auto& e) {
      if (e.first >= oldest) return false;
      buried -= e.second.length;
      return true;
    }), graveyard.end());
  }
  void sync() {
    std::lock_guard<std::recursive_mutex> l(mu);
    commit();
    ++stats.syncs;
    auto t0 = std::chrono::steady_clock::now();
    { std::unique_lock<std::mutex> g(inflightMu); inflightDone.wait(g, [&] { return pending.empty(); }); }
    stats.syncMs += std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - t0).count();
    bury();
    std::lock_guard<std::mutex> g(errorMu);
    if (!gpuError.empty()) die("the GPU failed: %s", gpuError.c_str());
  }

  // ---- kernels
  id<MTLLibrary> compile(const std::string& source, const std::string& what, bool tensor = false) {
    MTLCompileOptions* o = [MTLCompileOptions new];
    o.languageVersion = MTLLanguageVersion3_0;
    if (tensor) {
      if (@available(macOS 26.0, *)) o.languageVersion = MTLLanguageVersion4_0;
      else die("compiling %s: the tensor GEMM needs macOS 26", what.c_str());
    }
    o.fastMathEnabled = NO;
    NSError* e = nil;
    auto t0 = std::chrono::steady_clock::now();
    id<MTLLibrary> l = [dev newLibraryWithSource:[NSString stringWithUTF8String:source.c_str()] options:o error:&e];
    stats.compileMs += std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - t0).count();
    if (!l) die("compiling %s:\n%s", what.c_str(), e ? e.localizedDescription.UTF8String : "?");
    return l;
  }
  id<MTLComputePipelineState> pipelineOf(id<MTLLibrary> l, const std::string& name) {
    id<MTLFunction> f = [l newFunctionWithName:[NSString stringWithUTF8String:name.c_str()]];
    if (!f) die("no kernel %s", name.c_str());
    NSError* e = nil;
    id<MTLComputePipelineState> p = [dev newComputePipelineStateWithFunction:f error:&e];
    if (!p) die("%s: %s", name.c_str(), e ? e.localizedDescription.UTF8String : "?");
    return p;
  }
  id<MTLLibrary> portLib() {
    std::lock_guard<std::mutex> g(libMu);
    if (!lib) {
      if (!portSource) die("no kernel source (setSource)");
      lib = compile(portSource, "the " + portName + " kernels");
    }
    return lib;
  }
  // the pipelines by name (pipeMu: the precompiling thread inserts beside the encoding one)
  std::mutex pipeMu, specMu;
  std::shared_future<void> precompiling;
  id<MTLComputePipelineState> cached(const std::string& name) {
    std::lock_guard<std::mutex> g(pipeMu);
    auto it = pipelines.find(name);
    return it == pipelines.end() ? nil : it->second;
  }
  void remember(const std::string& name, id<MTLComputePipelineState> p) { std::lock_guard<std::mutex> g(pipeMu); pipelines[name] = p; }
  id<MTLComputePipelineState> kernel(const char* name) {
    if (id<MTLComputePipelineState> p = cached(name)) return p;
    id<MTLComputePipelineState> p = pipelineOf(portLib(), name);
    remember(name, p);
    return p;
  }
  std::string cacheDir() {
    const char* home = getenv("HOME");
    std::string base = std::string(home ? home : "/tmp") + "/.cache";
    mkdir(base.c_str(), 0755); mkdir((base + "/localfold").c_str(), 0755); mkdir((base + "/localfold/metal").c_str(), 0755);
    return base + "/localfold/metal";
  }
  void loadSpecs() {      // (specMu held)
    if (specsLoaded) return;
    specsLoaded = true;
    std::string name = "/" + specsName(portName.c_str());
    specsPath = cacheDir() + name;
    struct stat st;
    if (stat(specsPath.c_str(), &st) != 0) {     // a first run: the list a wheel ships beside the binary
      char exe[4096]; uint32_t size = sizeof exe;
      if (_NSGetExecutablePath(exe, &size) == 0) {
        std::string bundled = std::string(exe);
        bundled = bundled.substr(0, bundled.rfind('/')) + "/metal-specs" + name;
        std::ifstream src(bundled);
        if (src) { std::ofstream dst(specsPath); dst << src.rdbuf(); }
      }
    }
    std::ifstream in(specsPath);
    std::string line;
    while (std::getline(in, line)) {
      size_t tab = line.find('\t');
      if (tab == std::string::npos) continue;
      knownSpecs.insert(line.substr(0, tab));
      specDecls[line.substr(0, tab)] = line.substr(tab + 1);
    }
  }
  // every instance a previous run used, compiled on threads of their own while the caller loads weights - in parallel
  // chunks, the compiler being single-threaded
  void precompile() {
    std::vector<std::pair<std::string, std::string>> todo;
    {
      std::lock_guard<std::mutex> g(specMu);
      loadSpecs();
      for (auto& [n, d] : specDecls) if (!cached(n)) todo.push_back({n, d});
    }
    if (todo.empty()) return;
    precompiling = std::async(std::launch::async, [this, todo] {
      // (the tensor instances in libraries of their own: another source, another language version - and none on a GPU
      // without the units, where a cached list from an M5 names them)
      std::vector<std::pair<std::string, std::string>> groups[2];
      for (auto& t : todo) if (!isTensor(t.first)) groups[0].push_back(t); else if (tensorOps) groups[1].push_back(t);
      std::vector<std::thread> threads;
      for (int tensor = 0; tensor < 2; ++tensor) {
        const std::vector<std::pair<std::string, std::string>>* list = &groups[tensor];   // (groups outlives the threads)
        const size_t chunks = std::min<size_t>(tensor ? 4 : 8, (list->size() + 7) / 8);
        for (size_t c = 0; c < chunks; ++c)
          threads.emplace_back([this, list, chunks, c, tensor] { @autoreleasepool {
            std::string src = tensor ? TENSOR_SOURCE : GEMM_SOURCE;
            for (size_t i = c; i < list->size(); i += chunks) src += "\n" + (*list)[i].second;
            id<MTLLibrary> l = compile(src, "the cached instances", tensor);
            for (size_t i = c; i < list->size(); i += chunks) remember((*list)[i].first, pipelineOf(l, (*list)[i].first));
          } });
      }
      for (auto& t : threads) t.join();
    }).share();
  }
  static bool isTensor(const std::string& name) { return name.compare(0, 6, "gemmt_") == 0; }
  id<MTLComputePipelineState> instance(const std::string& name, const std::string& decl) {
    if (id<MTLComputePipelineState> p = cached(name)) return p;
    if (precompiling.valid()) { precompiling.wait(); if (id<MTLComputePipelineState> p = cached(name)) return p; }
    auto t0 = std::chrono::steady_clock::now();
    const bool tensor = isTensor(name);
    id<MTLComputePipelineState> p = pipelineOf(compile(std::string(tensor ? TENSOR_SOURCE : GEMM_SOURCE) + "\n" + decl + "\n", name, tensor), name);
    if (getenv("LOCALFOLD_METAL_VERBOSE"))
      fprintf(stderr, "metal: compiled %s in %.0f ms\n", name.c_str(),
              std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - t0).count());
    remember(name, p);
    std::lock_guard<std::mutex> g(specMu);
    loadSpecs();
    if (!knownSpecs.count(name)) {
      knownSpecs.insert(name); specDecls[name] = decl;
      std::ofstream out(specsPath, std::ios::app);
      out << name << "\t" << decl << "\n";
    }
    return p;
  }
  void dispatch(id<MTLComputePipelineState> pso, const void* args, size_t argBytes, Grid g, uint32_t threads, size_t smem,
                const char* label) {
    if (!g.x || !g.y || !g.z) return;
    if (threads > pso.maxTotalThreadsPerThreadgroup)
      die("a dispatch of %u threads a threadgroup to a kernel that takes at most %lu (%s)", threads,
          (unsigned long)pso.maxTotalThreadsPerThreadgroup, label ? label : "?");
    // LOCALFOLD_CHECK_ARGS=1: every 8-byte word of the arguments that points into a RELEASED buffer is a use after
    // release (debugging: the graveyard keeps it alive only until the work issued before the release is done)
    static const bool checkArgs = getenv("LOCALFOLD_CHECK_ARGS") != nullptr;
    if (checkArgs)
      for (size_t o = 0; o + 8 <= argBytes; o += 8) {
        uint64_t v; memcpy(&v, (const char*)args + o, 8);
        for (auto& [tag, b] : graveyard)
          if (v >= b.gpuAddress && v < b.gpuAddress + b.length)
            die("%s: argument word %zu points into a released buffer (%lu bytes)", label ? label : "?", o / 8, (unsigned long)b.length);
      }
    ensureEncoder();
    ++stats.dispatches;
    [enc setComputePipelineState:pso];
    if (argBytes <= 4096) [enc setBytes:args length:std::max<size_t>(argBytes, 4) atIndex:0];
    else {
      id<MTLBuffer> b = [dev newBufferWithBytes:args length:argBytes options:MTLResourceStorageModeShared];
      keep.push_back(b);
      [enc useResource:b usage:MTLResourceUsageRead];
      [enc setBuffer:b offset:0 atIndex:0];
    }
    if (smem) [enc setThreadgroupMemoryLength:(smem + 15) & ~(size_t)15 atIndex:0];
    [enc dispatchThreadgroups:MTLSizeMake(g.x, g.y, g.z) threadsPerThreadgroup:MTLSizeMake(threads, 1, 1)];
    // LOCALFOLD_SYNC_EACH=1: every dispatch waited for and checked, a failure named by its kernel (debugging)
    static const bool syncEach = getenv("LOCALFOLD_SYNC_EACH") != nullptr;
    if (syncEach) {
      id<MTLCommandBuffer> mine = cb;
      commit();
      [mine waitUntilCompleted];
      if (mine.error) die("the GPU failed in %s: %s", label ? label : "?", mine.error.localizedDescription.UTF8String);
      return;
    }
    static const bool commitEach = getenv("LOCALFOLD_COMMIT_EACH") != nullptr;
    if (commitEach) {                       // (each its own command buffer, unwaited: a failure named by its kernel)
      std::string lab = label ? label : "?";
      [cb addCompletedHandler:^(id<MTLCommandBuffer> done) {
        if (done.error) fprintf(stderr, "the GPU failed in %s: %s\n", lab.c_str(), done.error.localizedDescription.UTF8String);
      }];
      commit();
      return;
    }
    if (profileOn && label) {               // (a command buffer a dispatch: its GPU time is the kernel's)
      id<MTLCommandBuffer> mine = cb;
      commit();
      profiled.push_back({label, mine});
    } else if (++encoded >= 128) {
      commit();                             // (let the GPU start while the host encodes the rest)
    }
  }
};
Device& D() { static Device* d = new Device(); return *d; }
}  // namespace

// ---------------------------------------------------------------- memory
void* alloc(size_t bytes) { return D().alloc(bytes); }
void release(const void* p) { D().release(p); }
void* host(const void* p) { std::lock_guard<std::recursive_mutex> l(D().mu); return D().host(p); }
bool isDevice(const void* p) { std::lock_guard<std::recursive_mutex> l(D().mu); return D().find((uint64_t)p) != nullptr; }
size_t allocated() { return D().held; }
size_t peakAllocated() { return D().peak; }
size_t peakLive() { return D().peakLive; }
void resetPeak() { D().peak = D().held; }
void* scratchBytes(const std::string& name, size_t bytes) {
  Device& d = D();
  std::lock_guard<std::recursive_mutex> l(d.mu);
  auto it = d.scratch.find(name);
  if (it != d.scratch.end()) {
    if (it->second.second >= bytes) return it->second.first;
    d.release(it->second.first);
    d.scratch.erase(it);
  }
  void* p = d.alloc(std::max<size_t>(bytes, 16));
  d.scratch[name] = {p, bytes};
  return p;
}
void releaseScratch(std::initializer_list<const char*> prefixes) {
  Device& d = D();
  std::lock_guard<std::recursive_mutex> l(d.mu);
  for (auto it = d.scratch.begin(); it != d.scratch.end();) {
    bool match = prefixes.size() == 0;
    for (const char* p : prefixes) match |= it->first.rfind(p, 0) == 0;
    if (match) { d.release(it->second.first); it = d.scratch.erase(it); }
    else ++it;
  }
}
size_t scratchHeld() { size_t s = 0; for (auto& [k, v] : D().scratch) s += v.second; return s; }
std::vector<std::pair<std::string, size_t>> scratchList() {
  std::vector<std::pair<std::string, size_t>> v;
  for (auto& [k, s] : D().scratch) v.push_back({k, s.second});
  return v;
}
// a file mapped without a copy: the GPU reads the page cache (the shard decode), and nothing counts against the device
void* mapFile(const std::string& path, size_t* bytes) {
  Device& d = D();
  int fd = open(path.c_str(), O_RDONLY);
  if (fd < 0) die("cannot read %s", path.c_str());
  struct stat st; fstat(fd, &st);
  size_t page = (size_t)getpagesize(), n = ((size_t)st.st_size + 2 + page - 1) / page * page;
  void* p = mmap(nullptr, n, PROT_READ | PROT_WRITE, MAP_PRIVATE, fd, 0);
  close(fd);
  if (p == MAP_FAILED) die("cannot map %s", path.c_str());
  std::lock_guard<std::recursive_mutex> l(d.mu);
  id<MTLBuffer> b = [d.dev newBufferWithBytesNoCopy:p length:n options:MTLResourceStorageModeShared
                                        deallocator:^(void* q, NSUInteger len) { munmap(q, len); }];
  if (!b) die("cannot map %s for the GPU", path.c_str());
  uint64_t addr = b.gpuAddress;
  d.allocs[addr] = {b, addr, n};
  if (d.enc) [d.enc useResource:b usage:MTLResourceUsageRead];
  *bytes = (size_t)st.st_size;
  return (void*)addr;
}
void unmapFile(void* p) {
  Device& d = D();
  std::lock_guard<std::recursive_mutex> l(d.mu);
  auto it = d.allocs.find((uint64_t)p);
  if (it == d.allocs.end()) die("unmapFile of a pointer that is not a mapping");
  if (!d.idle()) { d.graveyard.push_back({d.committedSeq + (d.cb ? 1 : 0), it->second.buf}); d.buried += it->second.buf.length; }
  d.allocs.erase(it);
}
Grid grid1d(size_t n, uint32_t threads) {
  size_t groups = (n + threads - 1) / threads;
  if (groups <= 65535) return {(uint32_t)groups, 1, 1};
  return {65535, (uint32_t)((groups + 65534) / 65535), 1};
}
void fill(void* p, int byte, size_t bytes) {
  if (!bytes) return;
  Device& d = D();
  std::lock_guard<std::recursive_mutex> l(d.mu);
  d.host(p, bytes);
  if (d.idle()) { memset(d.host(p), byte, bytes); return; }
  FillArgs a{(uchar*)p, bytes, (uint)(byte & 255), 0};
  run1d("lf_fill", (((uint64_t)p & 15) == 0 ? std::max<size_t>(bytes / 16, 16) : bytes), a);
}
void padZero(half* planes, size_t count, int n, int np) {
  if (np <= n || !count) return;
  const size_t per = (size_t)np * np - (size_t)n * n;
  run1d("lf_pad_zero", count * per, PadZeroArgs{planes, (uint64_t)count, (uint)n, (uint)np});
}
void copy(void* dst, const void* src, size_t bytes) {
  if (!bytes) return;
  CopyArgs a{(uchar*)dst, (const uchar*)src, bytes};
  run1d("lf_copy", ((((uint64_t)dst | (uint64_t)src) & 15) == 0 ? std::max<size_t>(bytes / 16, 16) : bytes), a);
}
void copy2d(void* dst, size_t dpitch, const void* src, size_t spitch, size_t width, size_t height) {
  if (!width || !height) return;
  Copy2DArgs a{(uchar*)dst, (const uchar*)src, dpitch, spitch, width, height};
  run1d("lf_copy2d", width * height, a);
}
void upload(void* dst, const void* src, size_t bytes) {
  if (!bytes) return;
  Device& d = D();
  std::lock_guard<std::recursive_mutex> l(d.mu);
  void* h = d.host(dst, bytes);
  if (d.idle()) { memcpy(h, src, bytes); return; }
  // staged: the bytes now, the copy in stream order
  id<MTLBuffer> stage = [d.dev newBufferWithBytes:src length:bytes options:MTLResourceStorageModeShared];
  if (!stage) die("out of memory staging a %zu-byte upload", bytes);
  ++d.stats.staged;
  d.ensureEncoder();
  [d.enc useResource:stage usage:MTLResourceUsageRead];
  d.keep.push_back(stage);
  copy(dst, (const void*)stage.gpuAddress, bytes);
}
void download(void* dst, const void* src, size_t bytes) {
  if (!bytes) return;
  Device& d = D();
  d.sync();
  std::lock_guard<std::recursive_mutex> l(d.mu);
  memcpy(dst, d.host(src, bytes), bytes);
}
void sync() { D().sync(); }

// ---------------------------------------------------------------- kernels
std::string specsName(const char* port) {
  char name[96]; snprintf(name, sizeof name, "native-%s-%016zx.specs", port,
                          std::hash<std::string>()(std::string(GEMM_SOURCE) + TENSOR_SOURCE));
  return name;
}
void setSource(const char* portName, const char* source) {
  Device& d = D();
  d.portName = portName; d.portSource = source;
  // the port's kernels, and the GEMM instances a previous run used, compiled on threads of their own while the caller
  // loads weights
  std::thread([] { @autoreleasepool { D().portLib(); } }).detach();
  d.precompile();
}
void dispatch(const char* kernel, const void* args, size_t argBytes, Grid groups, uint32_t threads, size_t smem, const char* label) {
  Device& d = D();
  id<MTLComputePipelineState> p = d.kernel(kernel);
  std::lock_guard<std::recursive_mutex> l(d.mu);
  d.dispatch(p, args, argBytes, groups, threads, smem, label ? label : kernel);
}
void dispatchInstance(const std::string& name, const std::string& decl, const void* args, size_t argBytes, Grid groups,
                      uint32_t threads, size_t smem, const char* label) {
  Device& d = D();
  id<MTLComputePipelineState> p = d.instance(name, decl);
  std::lock_guard<std::recursive_mutex> l(d.mu);
  d.dispatch(p, args, argBytes, groups, threads, smem, label ? label : name.c_str());
}
void precompile() { D().precompile(); }

// ---------------------------------------------------------------- GEMM
int GEMM_EXTRA_EP = 0;
namespace {
// The matrix units' GEMM (gemm_tensor.metal): half operands, any output, every epilogue. LOCALFOLD_GEMM_TENSOR=0 keeps
// lf_gemm (the control); read at every call, as the bench's arms set it.
bool tensorWanted() {
  const char* e = getenv("LOCALFOLD_GEMM_TENSOR");
  return D().tensorOps && !(e && !strcmp(e, "0"));
}
void gemmTensorRun(DT tc_, GemmArgs a, int batch, bool accFloat, const char* label) {
  static const bool floatAcc = getenv("LOCALFOLD_GEMM_FLOAT_ACC") && strcmp(getenv("LOCALFOLD_GEMM_FLOAT_ACC"), "0") != 0;
  // a half output takes a half destination even where the caller asked for float accumulation: the matrix units sum a
  // whole run wider than half and round once on the way out (6MRR's and 5CAJ's folds unchanged to the PDB's 0.001 A;
  // 512 x 65025 x 128 with a bias 0.86 ms against 1.41 into a float destination - the float tile's register cost)
  const bool hacc = !floatAcc && tc_ == F16;
  const bool tri = a.epilogue & 256;
  const bool plain = !tri && (a.epilogue & ~6) == 0 && a.alpha == 1.f && a.beta == 0.f;
  // the tile: TM rows along n by TN columns along m. A short n (up to 128) in one tile row, rounded up to 16, 64 columns
  // where the weight is wide enough to fill the GPU (3072 x 80 x 768: 0.064 ms at 80 x 64 against 0.078 at 80 x 128) and
  // 32 where not (768 x 80 x 768: 0.062 against 0.075); a taller n 64 x 128 (512 x 68121 x 128 half: 0.93 ms against
  // 1.20 at 64 x 64; 4096 square 12.0 TFLOP/s against 9.5). Measured on an M5 (8-core GPU), interleaved.
  int tm = a.n <= 128 ? (a.n + 15) / 16 * 16 : 64, tn = a.n <= 128 ? (a.m >= 40 * 64 ? 64 : 32) : (a.m >= 128 ? 128 : 64);
  if (const char* t = getenv("LOCALFOLD_GEMM_TILE")) sscanf(t, "%dx%d", &tm, &tn);
  const bool triReg = tri && (a.epilogue & 512);
  if (triReg) { tm = 64; tn = 128; }      // (the layout lf_tri_quarters wrote: 32 channels a tile)
  // the general epilogues in registers, 4 columns at a time (LOCALFOLD_GEMM_VEC=0 the control): where the tile is
  // 64 rows and everything the epilogue touches is 4-element aligned
  static const bool vecWanted = !getenv("LOCALFOLD_GEMM_VEC") || atoi(getenv("LOCALFOLD_GEMM_VEC")) != 0;
  auto al4 = [](uint64_t p, int64_t ld) { return p % 16 == 0 && ld % 4 == 0; };
  const bool vecEp = vecWanted && !plain && !tri && !(a.epilogue & (128 | 256)) && tm == 64 && a.m % 4 == 0 && !a.ptrs &&
                     al4(a.D, a.ldd) && al4(a.D + 0, a.sd) && (a.beta == 0.f && !(a.epilogue & 64) ? true : al4(a.C, a.ldc) && al4(a.C, a.sc)) &&
                     (!(a.epilogue & 64) || al4(a.aux, a.ldaux)) && (!(a.epilogue & 4) || a.bias % 16 == 0);
  if (vecEp && tn < 64) tn = 64;
  // (a staged epilogue holds the tile in threadgroup memory: 32 KB on Apple's GPUs, some of it the operation's own)
  while (!plain && !tri && !vecEp && tm * tn * (hacc ? 2 : 4) > 16384 && tn > 16) tn /= 2;
  if (tri && tn % 32) die("gemm: the triangle gate wants a tile 32 columns wide or more, not %d", tn);
  if (tm % 16 || tn % 16 || tm < 16 || tn < 16) die("gemm: no %d x %d tensor tile", tm, tn);
  const int ep = (tri ? 1 : 0) | (plain ? 2 : 0) | (hacc ? 8 : 0) | (triReg ? 16 : 0) | (vecEp ? 128 : 0);
  const char* tcs = tc_ == F32 ? "float" : "half";
  std::string targs = std::string("half, half, ") + tcs + ", " + std::to_string(tm) + ", " + std::to_string(tn) + ", " +
                      (a.ta ? "true" : "false") + ", " + (a.tb ? "true" : "false") + ", " + std::to_string(ep);
  std::string name = std::string("gemmt_hh") + (tc_ == F32 ? "f" : "h") + "_" + std::to_string(tm) + "x" + std::to_string(tn) +
                     "_" + (a.ta ? "T" : "N") + (a.tb ? "T" : "N") + "_e" + std::to_string(ep);
  std::string decl = "template [[host_name(\"" + name + "\")]] kernel void lf_gemm_tensor<" + targs + ">(constant GemmArgs&, uint3, uint);";
  Grid grid{(uint32_t)((a.m + tn - 1) / tn), (uint32_t)((a.n + tm - 1) / tm), (uint32_t)batch};
  std::string lab;
  if (D().profileOn) {
    char b[160]; snprintf(b, sizeof b, "%s %s %dx%dx%d%s", label ? label : "gemm", name.c_str() + 6, a.m, a.n, a.k, batch > 1 ? " batched" : "");
    lab = b;
  }
  dispatchInstance(name, decl, &a, sizeof a, grid, 128, 0, lab.empty() ? nullptr : lab.c_str());
}
void gemmRun(DT ta_, DT tb_, DT tc_, GemmArgs a, int batch, bool halfMma, bool accFloat, const char* label) {
  if (a.m <= 0 || a.n <= 0 || batch <= 0) return;
  ++D().stats.gemms;
  if (ta_ == F16 && tb_ == F16 && tensorWanted()) { gemmTensorRun(tc_, a, batch, accFloat, label); return; }
  // the tile: TR rows along n by TC columns along m. A short n (up to 128) in ONE tile row - every weight read once -
  // rounded up to 16; the columns then as many as keep a simdgroup's accumulators at 16 or fewer
  int tr = 64, tc = 64;
  // (80 rows take 64 columns too where there are 40 tiles of them: a simdgroup's 40 x 32 reloads fewer fragments a
  // multiply - 0.187 against 0.254 ms on 3072 x 80 x 768, 1.70 against 2.00 on 73728 x 80 x 384, interleaved - and
  // narrower weights keep 32, whose extra threadgroups win there: 0.102 against 0.118 ms on 768 x 80 x 768)
  if (a.n <= 128) { tr = (a.n + 15) / 16 * 16; tc = tr <= 64 || (tr <= 80 && a.m >= 40 * 64) ? 64 : 32; }
  else if (a.m <= 48) { tr = 64; tc = 32; }
  // 48-row tiles where 64 would waste over a tenth of the rows on padding and 48 wastes less
  if (a.n > 128 && tr == 64) {
    long pad64 = (long)((a.n + 63) / 64) * 64 - a.n, pad48 = (long)((a.n + 47) / 48) * 48 - a.n;
    if (pad64 * 10 > a.n && pad48 < pad64) tr = 48;
  }
  auto groups = [&](int c) { return (long)((a.m + c - 1) / c) * ((a.n + tr - 1) / tr) * batch; };
  while (tc > 16 && groups(tc) < 64) tc /= 2;
  // ...and 48-column tiles likewise (not SwiGLU's or the triangle gate's, whose epilogues pair 8-column blocks)
  if (tc == 64 && !(a.epilogue & (128 | 256))) {
    long pad64 = (long)((a.m + 63) / 64) * 64 - a.m, pad48 = (long)((a.m + 47) / 48) * 48 - a.m;
    if (pad64 * 10 > a.m && pad48 < pad64) tc = 48;
  }
  if ((a.epilogue & 128) && tc < 32) tc = 32;
  if (a.epilogue & 256) tc = 64;
  if (const char* t = getenv("LOCALFOLD_GEMM_TILE")) sscanf(t, "%dx%d", &tr, &tc);
  if (tr % 16 || tc % 16 || tr < 16 || tc < 16) die("gemm: no %d x %d tile", tr, tc);
  auto esize = [](DT t) { return t == F32 ? 4 : 2; };
  bool vec = !a.ptrs && a.lda % 8 == 0 && a.ldb % 8 == 0 && a.sa % 8 == 0 && a.sb % 8 == 0 &&
             a.A % (8 * esize(ta_)) == 0 && a.B % (8 * esize(tb_)) == 0;
  if (vec) a.biasType |= 256;
  int bk = (tc >= 48 && tr >= 48) || (tc == 32 && tr >= 80) ? 16 : 32;
  if (const char* e = getenv("LOCALFOLD_GEMM_BK")) bk = atoi(e);
  static const bool floatAcc = getenv("LOCALFOLD_GEMM_FLOAT_ACC") && strcmp(getenv("LOCALFOLD_GEMM_FLOAT_ACC"), "0") != 0;
  const bool hacc = !floatAcc && !accFloat && ta_ == F16 && tb_ == F16 && tc_ == F16;
  const bool hmma = halfMma && !(ta_ == F16 && tb_ == F16);     // (half staging of an f32 operand)
  auto mtype = [](DT t) { return t == F32 ? "float" : "half"; };
  int ep = (a.epilogue & 256 ? 1 : 0) | (hacc ? 8 : 0) | (hmma ? 32 : 0) | GEMM_EXTRA_EP;
  std::string targs = std::string(mtype(ta_)) + ", " + mtype(tb_) + ", " + mtype(tc_) + ", " + std::to_string(tr) + ", " +
                      std::to_string(tc) + ", " + (a.ta ? "true" : "false") + ", " + (a.tb ? "true" : "false") + ", " +
                      std::to_string(bk) + ", " + std::to_string(ep);
  auto tag = [](DT t) { return t == F32 ? "f" : "h"; };
  std::string name = std::string("gemm_") + tag(ta_) + tag(tb_) + tag(tc_) + "_" + std::to_string(tr) + "x" + std::to_string(tc) +
                     "_" + (a.ta ? "T" : "N") + (a.tb ? "T" : "N") + "_k" + std::to_string(bk) + "_e" + std::to_string(ep);
  std::string decl = "template [[host_name(\"" + name + "\")]] kernel void lf_gemm<" + targs + ">(constant GemmArgs&, uint3, uint, uint, uint);";
  Grid grid{(uint32_t)((a.m + tc - 1) / tc), (uint32_t)((a.n + tr - 1) / tr), (uint32_t)batch};
  std::string lab;
  if (D().profileOn) {
    char b[160]; snprintf(b, sizeof b, "%s %s %dx%dx%d%s", label ? label : "gemm", name.c_str() + 5, a.m, a.n, a.k, batch > 1 ? " batched" : "");
    lab = b;
  }
  dispatchInstance(name, decl, &a, sizeof a, grid, 128, 0, lab.empty() ? nullptr : lab.c_str());
}
}  // namespace
void gemm(const Gemm& g) {
  if (!g.rows || !g.out || g.batch <= 0) return;
  GemmArgs a{};
  a.A = (uint64_t)g.W; a.B = (uint64_t)g.X; a.C = (uint64_t)(g.Yin ? g.Yin : g.Y); a.D = (uint64_t)g.Y;
  a.m = g.out; a.n = (int)g.rows; a.k = g.in;
  a.lda = g.ldw ? g.ldw : (g.transW ? g.in : g.out);
  a.ldb = g.ldx ? g.ldx : (g.transX ? (int)g.rows : g.in);
  a.ldc = a.ldd = g.ldy ? g.ldy : g.out;
  a.ta = g.transW; a.tb = g.transX;
  a.sa = g.sw; a.sb = g.sx; a.sc = a.sd = g.sy;
  a.alpha = g.alpha; a.beta = g.beta;
  if (g.bias) { a.bias = (uint64_t)g.bias; a.epilogue |= 4; a.biasType = g.tbias == F16 ? 2 : 0; }
  if (g.relu) a.epilogue |= 2;
  if (g.gelu) a.epilogue |= 32;
  gemmRun(g.tw, g.tx, g.ty, a, g.batch, g.half, g.accFloat, g.label);
}
void gemmGatedAdd(const half* X, const half* W, const half* aux, float* pair, size_t rows, int in, int out, const float* bias) {
  GemmArgs a{};
  a.A = (uint64_t)W; a.B = (uint64_t)X; a.C = a.D = (uint64_t)pair;
  a.m = out; a.n = (int)rows; a.k = in; a.lda = out; a.ldb = in; a.ldc = a.ldd = out;
  a.epilogue = 64; a.alpha = 1.f;
  a.aux = (uint64_t)aux; a.ldaux = out;
  if (bias) { a.bias = (uint64_t)bias; a.epilogue |= 4; }
  gemmRun(F16, F16, F32, a, 1, false, false, "gated add");
}
void gemmSwiglu(const half* X, const half* Wpairs, half* gated, size_t rows, int in, int hidden) {
  if (hidden % 8) die("gemmSwiglu: a hidden width of %d is not a multiple of 8", hidden);
  GemmArgs a{};
  a.A = (uint64_t)Wpairs; a.B = (uint64_t)X; a.C = a.D = (uint64_t)gated;
  a.m = 2 * hidden; a.n = (int)rows; a.k = in; a.lda = 2 * hidden; a.ldb = in; a.ldc = a.ldd = hidden;
  a.epilogue = 128; a.alpha = 1.f;
  gemmRun(F16, F16, F16, a, 1, false, false, "swiglu");
}
void gemmTriGate(const half* X, const half* W, const float* mask, half* outA, half* outB, size_t r0, size_t rows, int C,
                 size_t pairs, int n, int np, const float* bias) {
  GemmArgs g{};
  g.A = (uint64_t)W; g.B = (uint64_t)X; g.C = g.D = (uint64_t)outA;
  g.m = 4 * C; g.n = (int)rows; g.k = C; g.lda = 4 * C; g.ldb = C; g.ldc = g.ldd = 4 * C;
  g.epilogue = 256; g.alpha = 1.f;
  g.aux = (uint64_t)mask; g.aux2 = (uint64_t)outA; g.aux3 = (uint64_t)outB;
  g.tgR0 = (int64_t)r0; g.tgPairs = (int64_t)pairs; g.tgN = n; g.tgNp = np; g.tgC = C;
  if (bias) { g.bias = (uint64_t)bias; g.epilogue |= 4; }
  // on the matrix units the weight in quarters (lf_tri_quarters, every call into one buffer - 0.01 ms, and no cache
  // keyed by an address a later model's weights may reuse) and the gate in registers (epilogue 512): no staging tile.
  // LOCALFOLD_TRI_REG=0 the control
  static const bool reg = !getenv("LOCALFOLD_TRI_REG") || atoi(getenv("LOCALFOLD_TRI_REG")) != 0;
  if (reg && C % 32 == 0 && tensorWanted()) {
    static half* qw = nullptr; static float* qb = nullptr; static size_t qC = 0;
    if ((size_t)C > qC) { qw = allocT<half>((size_t)C * 4 * C); qb = allocT<float>((size_t)4 * C); qC = C; }
    run1d("lf_tri_quarters", (size_t)C * 4 * C, TriQuartersArgs{W, qw, bias, bias ? qb : nullptr, (uint64_t)C, (uint)C, 0});
    g.A = (uint64_t)qw;
    if (bias) g.bias = (uint64_t)qb;
    g.epilogue |= 512;
  }
  gemmRun(F16, F16, F16, g, 1, false, false, "triangle gate");
}

// ---------------------------------------------------------------- attention
// The matrix units' kernels (gemm_tensor.metal) where they win: lf_attention_tensor3 (v3: the online softmax in
// registers, no threadgroup memory) from 48 keys; lf_attention_tensor (v1) where there is a q bias, from 168 keys.
// Measured on an M5 (8-core GPU), interleaved, H 4 x n rows, lf_attention / v2 / v3 ms:
// n 255 D 32 3.86 / 1.87 / 1.63, D 64 6.83 / 3.15 / 2.90, D 16 2.50 / 1.69 / 1.61; n 384 D 32 x 128 rows 4.31 / 1.93
// / 1.58; n 128 D 32 0.53 / 0.30 / 0.26; n 64 D 32 0.093 / 0.077 / 0.074; n 48 D 32 0.227 / 0.216 / 0.118; but n 32
// D 32 0.032 / 0.038 / 0.035 - lf_attention's registers below 48. (v1 against those: n 255 D 32 3.06, n 128 0.47.)
// The key tile 64 unless that leaves the last one half empty or less, and 32 at D 16 (n 255: 1.61 against 1.74)
static const int ATTN_TENSOR_MIN_N = 168;
void attention(const Attention& t) {
  if (!t.rows || !t.n) return;
  int W = t.heads * t.D;
  AttnArgs a{};
  a.qkvg = t.qkvg; a.out = t.out; a.bias = t.bias; a.mask = t.mask; a.qBias = t.qBias;
  a.posStride = t.posStride ? t.posStride : 4 * W;
  a.rowStride = t.rowStride ? t.rowStride : (int64_t)t.n * a.posStride;
  a.outPosStride = t.outPosStride ? t.outPosStride : W;
  a.outRowStride = t.outRowStride ? t.outRowStride : (int64_t)t.n * a.outPosStride;
  a.r0 = t.r0; a.n = t.n; a.heads = t.heads; a.biasStride = t.biasStride; a.scale = t.scale;
  a.maskB = t.maskB || t.maskK ? t.maskB : t.n; a.maskK = t.maskB || t.maskK ? t.maskK : 1;
  a.pad0 = GEMM_EXTRA_EP;      // (an experiment's switch: metal/bench)
  // LOCALFOLD_ATTN_TENSOR=0 keeps lf_attention, =1 takes a tensor kernel at any length (the bench's arms);
  // LOCALFOLD_ATTN_V2=0 keeps v1 where v3 would run, =1 v2, =3 v3 at any length; LOCALFOLD_ATTN_TILE=QxK the tile
  if (D().tensorOps && (t.D == 16 || t.D == 32 || t.D == 48 || t.D == 64)) {
    const char* e = getenv("LOCALFOLD_ATTN_TENSOR");
    const char* v2 = getenv("LOCALFOLD_ATTN_V2");
    // the version: LOCALFOLD_ATTN_V2 unset - v3 from 48 keys (where the tensor kernels are on); 0 - v1; 1 or 2 - v2
    // (no q bias: v1 there); 3 - v3
    const int mode = v2 ? atoi(v2) : -1;
    const bool tensorOn = !e || strcmp(e, "0") != 0;
    int ver = mode < 0 ? (tensorOn && t.n >= 48 ? 3 : 1) : mode == 0 ? 1 : mode < 3 ? 2 : 3;
    if (ver == 2 && t.qBias) ver = 1;
    const bool two = ver > 1;
    const bool on = e ? strcmp(e, "0") != 0 : two || (t.n >= ATTN_TENSOR_MIN_N && t.D >= 32);
    if (on) {
      int TQB = 64, TKT = 32;
      if (two) { TQB = 16; TKT = (t.n % 64 == 0 || t.n % 64 > 32) && !(ver == 3 && t.D == 16) ? 64 : 32; }   // (v2's first number: queries a simdgroup)
      if (const char* tt = getenv("LOCALFOLD_ATTN_TILE")) sscanf(tt, "%dx%d", &TQB, &TKT);
      const char* stem = ver == 3 ? (t.qBias ? "gemmt_attn3q_" : "gemmt_attn3_") : ver == 2 ? "gemmt_attn2_" : "gemmt_attn_";
      const char* fn = ver == 3 ? "lf_attention_tensor3<" : ver == 2 ? "lf_attention_tensor2<" : "lf_attention_tensor<";
      std::string name = std::string(stem) + std::to_string(t.D) + "_" + std::to_string(TQB) + "x" + std::to_string(TKT);
      std::string decl = "template [[host_name(\"" + name + "\")]] kernel void " + fn +
                         std::to_string(t.D) + ", " + std::to_string(TQB) + ", " + std::to_string(TKT) +
                         (ver == 3 ? (t.qBias ? ", true" : ", false") : "") + ">(constant AttnArgs&, uint3, uint, uint, uint);";
      const int qb = two ? 4 * TQB : TQB;
      dispatchInstance(name, decl, &a, sizeof a, Grid{(uint32_t)((t.n + qb - 1) / qb), (uint32_t)t.rows, (uint32_t)t.heads}, 128, 0,
                       "attention");
      return;
    }
  }
  const char* k = t.D == 8 ? "lf_attention_8" : t.D == 16 ? "lf_attention_16" : t.D == 24 ? "lf_attention_24" : t.D == 32 ? "lf_attention_32"
                : t.D == 48 ? "lf_attention_48" : t.D == 64 ? "lf_attention_64" : nullptr;
  if (!k) die("attention: no kernel for a head %d wide", t.D);
  if (t.rows > 65535 * 64) die("attention: %zu rows", t.rows);
  const int QB = 32;
  dispatch(k, &a, sizeof a, Grid{(uint32_t)((t.n + QB - 1) / QB), (uint32_t)t.rows, (uint32_t)t.heads}, 128, 0, "attention");
}

// ---------------------------------------------------------------- common kernels
static void layerNormRun(const float* x, const half* xh, float* y, half* yh, size_t rows, int C, const float* scale,
                         const float* offset, float eps, int ldx, int ldy) {
  if (!rows) return;
  LayerNormArgs a{x, xh, y, yh, scale, offset, rows, C, ldx ? ldx : C, ldy ? ldy : C, eps};
  // a simdgroup a row, eight a threadgroup
  size_t groups = (rows + 7) / 8;
  Grid g = groups <= 65535 ? Grid{(uint32_t)groups, 1, 1} : Grid{65535, (uint32_t)((groups + 65534) / 65535), 1};
  int v = (C / 4 + 31) / 32;
  const bool wide = getenv("LOCALFOLD_LN_WIDE") != nullptr;     // (the control: every row in the widest kernel)
  const char* k = C % 4 || C > 1536 ? "lf_layernorm" : wide || v > 8 ? "lf_layernorm4_12" : v > 4 ? "lf_layernorm4_8"
                : v > 2 ? "lf_layernorm4_4" : v > 1 ? "lf_layernorm4_2" : "lf_layernorm4_1";
  dispatch(k, &a, sizeof a, g, 256, 0, "layernorm");
}
void layerNorm(const float* x, float* y, size_t rows, int C, const float* s, const float* o, float eps, int ldx, int ldy) {
  layerNormRun(x, nullptr, y, nullptr, rows, C, s, o, eps, ldx, ldy);
}
void layerNorm(const float* x, half* y, size_t rows, int C, const float* s, const float* o, float eps, int ldx, int ldy) {
  layerNormRun(x, nullptr, nullptr, y, rows, C, s, o, eps, ldx, ldy);
}
void layerNorm(const half* x, half* y, size_t rows, int C, const float* s, const float* o, float eps, int ldx, int ldy) {
  layerNormRun(nullptr, x, nullptr, y, rows, C, s, o, eps, ldx, ldy);
}
void centerNorm(const float* prod, half* out, int L, int Lp, int C, const float* scale, const float* offset) {
  size_t P = (size_t)L * L;
  run(C % 8 || C > 256 ? "lf_center_norm_wide" : C > 128 || getenv("LOCALFOLD_LN_WIDE") ? "lf_center_norm_32" : "lf_center_norm_16", grid1d((P + 31) / 32, 1), 256, CenterNormArgs{prod, out, P, (uint)C, (uint)L, (uint)Lp, 0, scale, offset});
}
void toHalf(const float* x, half* y, size_t n) { run1d("lf_to_half", (n + 3) / 4, ConvArgs{x, y, n}); }
void toFloat(const half* x, float* y, size_t n) { run1d("lf_to_float", (n + 3) / 4, ConvBackArgs{x, y, n}); }
void add(float* y, const float* x, size_t n, float a) { run1d("lf_add", (n + 3) / 4, AddArgs{y, x, n, a, 0}); }
void addBias(float* y, const float* b, size_t rows, int C, int act) { run1d("lf_add_bias", rows * C, BiasArgs{y, b, rows, C, act}); }

// ---------------------------------------------------------------- profiling
bool profiling() { const char* e = getenv("LOCALFOLD_PROFILE"); return e && atoi(e); }
void profileStart() {
  Device& d = D();
  if (!profiling()) return;
  d.sync(); d.profiled.clear(); d.profileOn = true;
}
void profileReport(const char* stage, int top) {
  Device& d = D();
  if (!d.profileOn) return;
  d.sync(); d.profileOn = false;
  std::map<std::string, std::pair<double, int>> by;
  double total = 0;
  for (auto& [name, c] : d.profiled) {
    double ms = (c.GPUEndTime - c.GPUStartTime) * 1e3;
    by[name].first += ms; by[name].second += 1; total += ms;
  }
  std::vector<std::pair<std::string, std::pair<double, int>>> rows(by.begin(), by.end());
  std::sort(rows.begin(), rows.end(), [](auto& a, auto& b) { return a.second.first > b.second.first; });
  printf("profile %s: %.1f ms of GPU time in %zu dispatches\n", stage, total, d.profiled.size());
  for (int i = 0; i < (int)rows.size() && i < top; ++i)
    printf("  %8.2f ms %5.1f%% %6d  %s\n", rows[i].second.first, 100 * rows[i].second.first / std::max(total, 1e-9),
           rows[i].second.second, rows[i].first.c_str());
  d.profiled.clear();
}
double now() { return std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count(); }
void printStats() {
  Device& d = D(); auto& s = d.stats;
  fprintf(stderr, "metal: peak %.2f GB, %ld dispatches (%ld GEMMs), %ld commits, %ld syncs %.0f ms waiting, %ld allocations, "
          "%ld staged uploads, compiling %.0f ms\n", d.peak / 1e9, s.dispatches, s.gemms, s.commits, s.syncs, s.syncMs,
          s.allocs, s.staged, s.compileMs);
}
}  // namespace mt
