// metal/core/core.h's implementation: the device, memory, the queue, kernels, the GEMM's dispatch.
#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#include "core.h"
#include "model.h"
#include <fcntl.h>
#include <sys/mman.h>
#include <unistd.h>
#include <mach-o/dyld.h>
#include <sys/stat.h>
#include <algorithm>
#include <atomic>
#include <chrono>
#include <climits>
#include <condition_variable>
#include <cstdarg>
#include <cstring>
#include <fstream>
#include <future>
#include <mutex>
#include <set>
#include <sstream>
#include <thread>
#include <unordered_map>

namespace mt {
extern const char* GEMM_SOURCE;             // args.h + gemm.metal (generated by metal/build.sh)

void die(const char* fmt, ...) {
  va_list ap; va_start(ap, fmt);
  fprintf(stderr, "localfold-metal: ");
  vfprintf(stderr, fmt, ap);
  fprintf(stderr, "\n");
  va_end(ap);
  fflush(stderr);
  std::exit(1);
}

namespace {
struct Alloc { id<MTLBuffer> buf; uint64_t addr; size_t size; };
struct Stats { double syncMs = 0, compileMs = 0; long dispatches = 0, commits = 0, syncs = 0, staged = 0, allocs = 0, gemms = 0; };

struct Device {
  std::recursive_mutex mu;
  id<MTLDevice> dev;
  id<MTLCommandQueue> queue;
  std::map<uint64_t, Alloc> allocs;
  size_t held = 0, peak = 0;
  id<MTLCommandBuffer> cb = nil;
  id<MTLComputeCommandEncoder> enc = nil;
  std::vector<id<MTLBuffer>> keep;           // staged and argument buffers, alive until this command buffer is done
  // released buffers, each alive until every command buffer committed up to its tag is done (Metal may complete a
  // later command buffer before an earlier one it sees no dependency on)
  std::vector<std::pair<long, id<MTLBuffer>>> graveyard;
  int encoded = 0;
  std::mutex inflightMu; std::condition_variable inflightDone; std::set<long> pending; long committedSeq = 0;
  std::mutex errorMu; std::string gpuError;
  // kernels
  std::string portName = "core";
  const char* portSource = nullptr;
  id<MTLLibrary> lib = nil;
  std::mutex libMu;
  std::unordered_map<std::string, id<MTLComputePipelineState>> pipelines;
  std::set<std::string> knownSpecs; std::string specsPath; bool specsLoaded = false;
  std::map<std::string, std::string> specDecls;
  // profiling
  bool profiling = getenv("LOCALFOLD_PROFILE") && atoi(getenv("LOCALFOLD_PROFILE"));
  bool profileOn = false;
  std::vector<std::pair<std::string, id<MTLCommandBuffer>>> profiled;
  Stats stats;
  // scratch
  std::map<std::string, std::pair<void*, size_t>> scratch;

  Device() {
    @autoreleasepool {
      NSArray<id<MTLDevice>>* devices = MTLCopyAllDevices();
      if (devices.count == 0) die("no Metal device");
      dev = devices[0];
      if (![dev supportsFamily:MTLGPUFamilyMetal3] || ![dev supportsFamily:MTLGPUFamilyApple7])
        die("this GPU (%s) is not an Apple-silicon GPU with Metal 3; LocalFold needs an M1 or later", dev.name.UTF8String);
      queue = [dev newCommandQueueWithMaxCommandBufferCount:64];
    }
  }

  // ---- memory
  const Alloc* find(uint64_t addr) {
    auto it = allocs.upper_bound(addr);
    if (it == allocs.begin()) return nullptr;
    --it;
    if (addr >= it->second.addr && addr < it->second.addr + std::max<size_t>(it->second.size, 1)) return &it->second;
    return nullptr;
  }
  void* alloc(size_t bytes) {
    std::lock_guard<std::recursive_mutex> l(mu);
    size_t n = std::max<size_t>((bytes + 255) & ~(size_t)255, 256);
    id<MTLBuffer> b = [dev newBufferWithLength:n options:MTLResourceStorageModeShared];
    if (!b) die("out of memory: %.2f GB asked for with %.2f GB held", bytes / 1e9, held / 1e9);
    ++stats.allocs;
    uint64_t addr = b.gpuAddress;
    allocs[addr] = {b, addr, n};
    held += n; peak = std::max(peak, held);
    if (enc) [enc useResource:b usage:MTLResourceUsageRead | MTLResourceUsageWrite];
    return (void*)addr;
  }
  void release(const void* p) {
    if (!p) return;
    std::lock_guard<std::recursive_mutex> l(mu);
    auto it = allocs.find((uint64_t)p);
    if (it == allocs.end()) die("release of a pointer that is not an allocation's start");
    held -= it->second.size;
    if (!idle()) graveyard.push_back({committedSeq + (cb ? 1 : 0), it->second.buf});   // (work issued may read it)
    allocs.erase(it);
  }
  void* host(const void* p, size_t bytes = 0) {
    const Alloc* a = find((uint64_t)p);
    if (!a) die("not a device pointer: %p", p);
    if ((uint64_t)p + bytes > a->addr + a->size) die("a host access past the end of its allocation");
    return (char*)a->buf.contents + ((uint64_t)p - a->addr);
  }

  // ---- the queue
  bool idle() { std::lock_guard<std::mutex> g(inflightMu); return !cb && pending.empty(); }
  void ensureEncoder() {
    if (enc) return;
    if (!cb) cb = [queue commandBufferWithUnretainedReferences];
    enc = [cb computeCommandEncoderWithDispatchType:MTLDispatchTypeSerial];
    std::vector<id<MTLResource>> all;
    all.reserve(allocs.size() + keep.size());
    for (auto& [_, a] : allocs) all.push_back(a.buf);
    for (auto& b : keep) all.push_back(b);
    for (auto& [t, b] : graveyard) all.push_back(b);
    if (!all.empty()) [enc useResources:all.data() count:all.size() usage:MTLResourceUsageRead | MTLResourceUsageWrite];
  }
  void commit() {
    if (enc) { [enc endEncoding]; enc = nil; }
    if (!cb) return;
    if (!keep.empty()) {
      __block std::vector<id<MTLBuffer>> k = std::move(keep);
      keep.clear();
      [cb addCompletedHandler:^(id<MTLCommandBuffer>) { k.clear(); }];
    }
    long seq;
    { std::lock_guard<std::mutex> g(inflightMu); seq = ++committedSeq; pending.insert(seq); }
    [cb addCompletedHandler:^(id<MTLCommandBuffer> done) {
      if (done.error) {
        std::lock_guard<std::mutex> g(errorMu);
        if (gpuError.empty()) gpuError = done.error.localizedDescription.UTF8String;
      }
      { std::lock_guard<std::mutex> g(inflightMu); pending.erase(seq); }
      inflightDone.notify_all();
    }];
    [cb commit];
    ++stats.commits;
    bury();
    cb = nil;
    encoded = 0;
  }
  void bury() {               // the released buffers no command buffer in flight can read
    if (graveyard.empty()) return;
    long oldest;
    { std::lock_guard<std::mutex> g(inflightMu); oldest = pending.empty() ? LONG_MAX : *pending.begin(); }
    graveyard.erase(std::remove_if(graveyard.begin(), graveyard.end(), [&](auto& e) { return e.first < oldest; }), graveyard.end());
  }
  void sync() {
    std::lock_guard<std::recursive_mutex> l(mu);
    commit();
    ++stats.syncs;
    auto t0 = std::chrono::steady_clock::now();
    { std::unique_lock<std::mutex> g(inflightMu); inflightDone.wait(g, [&] { return pending.empty(); }); }
    stats.syncMs += std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - t0).count();
    bury();
    std::lock_guard<std::mutex> g(errorMu);
    if (!gpuError.empty()) die("the GPU failed: %s", gpuError.c_str());
  }

  // ---- kernels
  id<MTLLibrary> compile(const std::string& source, const std::string& what) {
    MTLCompileOptions* o = [MTLCompileOptions new];
    o.languageVersion = MTLLanguageVersion3_0;
    o.fastMathEnabled = NO;
    NSError* e = nil;
    auto t0 = std::chrono::steady_clock::now();
    id<MTLLibrary> l = [dev newLibraryWithSource:[NSString stringWithUTF8String:source.c_str()] options:o error:&e];
    stats.compileMs += std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - t0).count();
    if (!l) die("compiling %s:\n%s", what.c_str(), e ? e.localizedDescription.UTF8String : "?");
    return l;
  }
  id<MTLComputePipelineState> pipelineOf(id<MTLLibrary> l, const std::string& name) {
    id<MTLFunction> f = [l newFunctionWithName:[NSString stringWithUTF8String:name.c_str()]];
    if (!f) die("no kernel %s", name.c_str());
    NSError* e = nil;
    id<MTLComputePipelineState> p = [dev newComputePipelineStateWithFunction:f error:&e];
    if (!p) die("%s: %s", name.c_str(), e ? e.localizedDescription.UTF8String : "?");
    return p;
  }
  id<MTLLibrary> portLib() {
    std::lock_guard<std::mutex> g(libMu);
    if (!lib) {
      if (!portSource) die("no kernel source (setSource)");
      lib = compile(portSource, "the " + portName + " kernels");
    }
    return lib;
  }
  // the pipelines by name (pipeMu: the precompiling thread inserts beside the encoding one)
  std::mutex pipeMu, specMu;
  std::shared_future<void> precompiling;
  id<MTLComputePipelineState> cached(const std::string& name) {
    std::lock_guard<std::mutex> g(pipeMu);
    auto it = pipelines.find(name);
    return it == pipelines.end() ? nil : it->second;
  }
  void remember(const std::string& name, id<MTLComputePipelineState> p) { std::lock_guard<std::mutex> g(pipeMu); pipelines[name] = p; }
  id<MTLComputePipelineState> kernel(const char* name) {
    if (id<MTLComputePipelineState> p = cached(name)) return p;
    id<MTLComputePipelineState> p = pipelineOf(portLib(), name);
    remember(name, p);
    return p;
  }
  std::string cacheDir() {
    const char* home = getenv("HOME");
    std::string base = std::string(home ? home : "/tmp") + "/.cache";
    mkdir(base.c_str(), 0755); mkdir((base + "/localfold").c_str(), 0755); mkdir((base + "/localfold/metal").c_str(), 0755);
    return base + "/localfold/metal";
  }
  void loadSpecs() {      // (specMu held)
    if (specsLoaded) return;
    specsLoaded = true;
    char name[96]; snprintf(name, sizeof name, "/native-%s-%016zx.specs", portName.c_str(), std::hash<std::string>()(GEMM_SOURCE));
    specsPath = cacheDir() + name;
    struct stat st;
    if (stat(specsPath.c_str(), &st) != 0) {     // a first run: the list a wheel ships beside the binary
      char exe[4096]; uint32_t size = sizeof exe;
      if (_NSGetExecutablePath(exe, &size) == 0) {
        std::string bundled = std::string(exe);
        bundled = bundled.substr(0, bundled.rfind('/')) + "/metal-specs" + name;
        std::ifstream src(bundled);
        if (src) { std::ofstream dst(specsPath); dst << src.rdbuf(); }
      }
    }
    std::ifstream in(specsPath);
    std::string line;
    while (std::getline(in, line)) {
      size_t tab = line.find('\t');
      if (tab == std::string::npos) continue;
      knownSpecs.insert(line.substr(0, tab));
      specDecls[line.substr(0, tab)] = line.substr(tab + 1);
    }
  }
  // every instance a previous run used, compiled on threads of their own while the caller loads weights - in parallel
  // chunks, the compiler being single-threaded
  void precompile() {
    std::vector<std::pair<std::string, std::string>> todo;
    {
      std::lock_guard<std::mutex> g(specMu);
      loadSpecs();
      for (auto& [n, d] : specDecls) if (!cached(n)) todo.push_back({n, d});
    }
    if (todo.empty()) return;
    precompiling = std::async(std::launch::async, [this, todo] {
      size_t chunks = std::min<size_t>(8, (todo.size() + 7) / 8);
      std::vector<std::thread> threads;
      for (size_t c = 0; c < chunks; ++c)
        threads.emplace_back([&, c] { @autoreleasepool {
          std::string src = GEMM_SOURCE;
          for (size_t i = c; i < todo.size(); i += chunks) src += "\n" + todo[i].second;
          id<MTLLibrary> l = compile(src, "the cached instances");
          for (size_t i = c; i < todo.size(); i += chunks) remember(todo[i].first, pipelineOf(l, todo[i].first));
        } });
      for (auto& t : threads) t.join();
    }).share();
  }
  id<MTLComputePipelineState> instance(const std::string& name, const std::string& decl) {
    if (id<MTLComputePipelineState> p = cached(name)) return p;
    if (precompiling.valid()) { precompiling.wait(); if (id<MTLComputePipelineState> p = cached(name)) return p; }
    auto t0 = std::chrono::steady_clock::now();
    id<MTLComputePipelineState> p = pipelineOf(compile(std::string(GEMM_SOURCE) + "\n" + decl + "\n", name), name);
    if (getenv("LOCALFOLD_METAL_VERBOSE"))
      fprintf(stderr, "metal: compiled %s in %.0f ms\n", name.c_str(),
              std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - t0).count());
    remember(name, p);
    std::lock_guard<std::mutex> g(specMu);
    loadSpecs();
    if (!knownSpecs.count(name)) {
      knownSpecs.insert(name); specDecls[name] = decl;
      std::ofstream out(specsPath, std::ios::app);
      out << name << "\t" << decl << "\n";
    }
    return p;
  }
  void dispatch(id<MTLComputePipelineState> pso, const void* args, size_t argBytes, Grid g, uint32_t threads, size_t smem,
                const char* label) {
    if (!g.x || !g.y || !g.z) return;
    if (threads > pso.maxTotalThreadsPerThreadgroup)
      die("a dispatch of %u threads a threadgroup to a kernel that takes at most %lu (%s)", threads,
          (unsigned long)pso.maxTotalThreadsPerThreadgroup, label ? label : "?");
    ensureEncoder();
    ++stats.dispatches;
    [enc setComputePipelineState:pso];
    if (argBytes <= 4096) [enc setBytes:args length:std::max<size_t>(argBytes, 4) atIndex:0];
    else {
      id<MTLBuffer> b = [dev newBufferWithBytes:args length:argBytes options:MTLResourceStorageModeShared];
      keep.push_back(b);
      [enc useResource:b usage:MTLResourceUsageRead];
      [enc setBuffer:b offset:0 atIndex:0];
    }
    if (smem) [enc setThreadgroupMemoryLength:(smem + 15) & ~(size_t)15 atIndex:0];
    [enc dispatchThreadgroups:MTLSizeMake(g.x, g.y, g.z) threadsPerThreadgroup:MTLSizeMake(threads, 1, 1)];
    if (profileOn && label) {               // (a command buffer a dispatch: its GPU time is the kernel's)
      id<MTLCommandBuffer> mine = cb;
      commit();
      profiled.push_back({label, mine});
    } else if (++encoded >= 128) {
      commit();                             // (let the GPU start while the host encodes the rest)
    }
  }
};
Device& D() { static Device* d = new Device(); return *d; }
}  // namespace

// ---------------------------------------------------------------- memory
void* alloc(size_t bytes) { return D().alloc(bytes); }
void release(const void* p) { D().release(p); }
void* host(const void* p) { std::lock_guard<std::recursive_mutex> l(D().mu); return D().host(p); }
bool isDevice(const void* p) { std::lock_guard<std::recursive_mutex> l(D().mu); return D().find((uint64_t)p) != nullptr; }
size_t allocated() { return D().held; }
size_t peakAllocated() { return D().peak; }
void resetPeak() { D().peak = D().held; }
void* scratchBytes(const std::string& name, size_t bytes) {
  Device& d = D();
  std::lock_guard<std::recursive_mutex> l(d.mu);
  auto it = d.scratch.find(name);
  if (it != d.scratch.end()) {
    if (it->second.second >= bytes) return it->second.first;
    d.release(it->second.first);
    d.scratch.erase(it);
  }
  void* p = d.alloc(std::max<size_t>(bytes, 16));
  d.scratch[name] = {p, bytes};
  return p;
}
void releaseScratch(std::initializer_list<const char*> prefixes) {
  Device& d = D();
  std::lock_guard<std::recursive_mutex> l(d.mu);
  for (auto it = d.scratch.begin(); it != d.scratch.end();) {
    bool match = prefixes.size() == 0;
    for (const char* p : prefixes) match |= it->first.rfind(p, 0) == 0;
    if (match) { d.release(it->second.first); it = d.scratch.erase(it); }
    else ++it;
  }
}
size_t scratchHeld() { size_t s = 0; for (auto& [k, v] : D().scratch) s += v.second; return s; }
std::vector<std::pair<std::string, size_t>> scratchList() {
  std::vector<std::pair<std::string, size_t>> v;
  for (auto& [k, s] : D().scratch) v.push_back({k, s.second});
  return v;
}
// a file mapped without a copy: the GPU reads the page cache (the shard decode), and nothing counts against the device
void* mapFile(const std::string& path, size_t* bytes) {
  Device& d = D();
  int fd = open(path.c_str(), O_RDONLY);
  if (fd < 0) die("cannot read %s", path.c_str());
  struct stat st; fstat(fd, &st);
  size_t page = (size_t)getpagesize(), n = ((size_t)st.st_size + 2 + page - 1) / page * page;
  void* p = mmap(nullptr, n, PROT_READ | PROT_WRITE, MAP_PRIVATE, fd, 0);
  close(fd);
  if (p == MAP_FAILED) die("cannot map %s", path.c_str());
  std::lock_guard<std::recursive_mutex> l(d.mu);
  id<MTLBuffer> b = [d.dev newBufferWithBytesNoCopy:p length:n options:MTLResourceStorageModeShared
                                        deallocator:^(void* q, NSUInteger len) { munmap(q, len); }];
  if (!b) die("cannot map %s for the GPU", path.c_str());
  uint64_t addr = b.gpuAddress;
  d.allocs[addr] = {b, addr, n};
  if (d.enc) [d.enc useResource:b usage:MTLResourceUsageRead];
  *bytes = (size_t)st.st_size;
  return (void*)addr;
}
void unmapFile(void* p) {
  Device& d = D();
  std::lock_guard<std::recursive_mutex> l(d.mu);
  auto it = d.allocs.find((uint64_t)p);
  if (it == d.allocs.end()) die("unmapFile of a pointer that is not a mapping");
  if (!d.idle()) d.graveyard.push_back({d.committedSeq + (d.cb ? 1 : 0), it->second.buf});
  d.allocs.erase(it);
}
Grid grid1d(size_t n, uint32_t threads) {
  size_t groups = (n + threads - 1) / threads;
  if (groups <= 65535) return {(uint32_t)groups, 1, 1};
  return {65535, (uint32_t)((groups + 65534) / 65535), 1};
}
void fill(void* p, int byte, size_t bytes) {
  if (!bytes) return;
  Device& d = D();
  std::lock_guard<std::recursive_mutex> l(d.mu);
  d.host(p, bytes);
  if (d.idle()) { memset(d.host(p), byte, bytes); return; }
  FillArgs a{(uchar*)p, bytes, (uint)(byte & 255), 0};
  run1d("lf_fill", (((uint64_t)p & 15) == 0 ? std::max<size_t>(bytes / 16, 16) : bytes), a);
}
void copy(void* dst, const void* src, size_t bytes) {
  if (!bytes) return;
  CopyArgs a{(uchar*)dst, (const uchar*)src, bytes};
  run1d("lf_copy", ((((uint64_t)dst | (uint64_t)src) & 15) == 0 ? std::max<size_t>(bytes / 16, 16) : bytes), a);
}
void copy2d(void* dst, size_t dpitch, const void* src, size_t spitch, size_t width, size_t height) {
  if (!width || !height) return;
  Copy2DArgs a{(uchar*)dst, (const uchar*)src, dpitch, spitch, width, height};
  run1d("lf_copy2d", width * height, a);
}
void upload(void* dst, const void* src, size_t bytes) {
  if (!bytes) return;
  Device& d = D();
  std::lock_guard<std::recursive_mutex> l(d.mu);
  void* h = d.host(dst, bytes);
  if (d.idle()) { memcpy(h, src, bytes); return; }
  // staged: the bytes now, the copy in stream order
  id<MTLBuffer> stage = [d.dev newBufferWithBytes:src length:bytes options:MTLResourceStorageModeShared];
  if (!stage) die("out of memory staging a %zu-byte upload", bytes);
  ++d.stats.staged;
  d.ensureEncoder();
  [d.enc useResource:stage usage:MTLResourceUsageRead];
  d.keep.push_back(stage);
  copy(dst, (const void*)stage.gpuAddress, bytes);
}
void download(void* dst, const void* src, size_t bytes) {
  if (!bytes) return;
  Device& d = D();
  d.sync();
  std::lock_guard<std::recursive_mutex> l(d.mu);
  memcpy(dst, d.host(src, bytes), bytes);
}
void sync() { D().sync(); }

// ---------------------------------------------------------------- kernels
void setSource(const char* portName, const char* source) {
  Device& d = D();
  d.portName = portName; d.portSource = source;
  // the port's kernels, and the GEMM instances a previous run used, compiled on threads of their own while the caller
  // loads weights
  std::thread([] { @autoreleasepool { D().portLib(); } }).detach();
  d.precompile();
}
void dispatch(const char* kernel, const void* args, size_t argBytes, Grid groups, uint32_t threads, size_t smem, const char* label) {
  Device& d = D();
  id<MTLComputePipelineState> p = d.kernel(kernel);
  std::lock_guard<std::recursive_mutex> l(d.mu);
  d.dispatch(p, args, argBytes, groups, threads, smem, label ? label : kernel);
}
void dispatchInstance(const std::string& name, const std::string& decl, const void* args, size_t argBytes, Grid groups,
                      uint32_t threads, size_t smem, const char* label) {
  Device& d = D();
  id<MTLComputePipelineState> p = d.instance(name, decl);
  std::lock_guard<std::recursive_mutex> l(d.mu);
  d.dispatch(p, args, argBytes, groups, threads, smem, label ? label : name.c_str());
}
void precompile() { D().precompile(); }

// ---------------------------------------------------------------- GEMM
namespace {
void gemmRun(DT ta_, DT tb_, DT tc_, GemmArgs a, int batch, bool halfMma, bool accFloat, const char* label) {
  if (a.m <= 0 || a.n <= 0 || batch <= 0) return;
  ++D().stats.gemms;
  // the tile: TR rows along n by TC columns along m. A short n (up to 128) in ONE tile row - every weight read once -
  // rounded up to 16; the columns then as many as keep a simdgroup's accumulators at 16 or fewer
  int tr = 64, tc = 64;
  if (a.n <= 128) { tr = (a.n + 15) / 16 * 16; tc = tr <= 64 ? 64 : 32; }
  else if (a.m <= 48) { tr = 64; tc = 32; }
  // 48-row tiles where 64 would waste over a tenth of the rows on padding and 48 wastes less
  if (a.n > 128 && tr == 64) {
    long pad64 = (long)((a.n + 63) / 64) * 64 - a.n, pad48 = (long)((a.n + 47) / 48) * 48 - a.n;
    if (pad64 * 10 > a.n && pad48 < pad64) tr = 48;
  }
  auto groups = [&](int c) { return (long)((a.m + c - 1) / c) * ((a.n + tr - 1) / tr) * batch; };
  while (tc > 16 && groups(tc) < 64) tc /= 2;
  // ...and 48-column tiles likewise (not SwiGLU's or the triangle gate's, whose epilogues pair 8-column blocks)
  if (tc == 64 && !(a.epilogue & (128 | 256))) {
    long pad64 = (long)((a.m + 63) / 64) * 64 - a.m, pad48 = (long)((a.m + 47) / 48) * 48 - a.m;
    if (pad64 * 10 > a.m && pad48 < pad64) tc = 48;
  }
  if ((a.epilogue & 128) && tc < 32) tc = 32;
  if (a.epilogue & 256) tc = 64;
  if (const char* t = getenv("LOCALFOLD_GEMM_TILE")) sscanf(t, "%dx%d", &tr, &tc);
  if (tr % 16 || tc % 16 || tr < 16 || tc < 16) die("gemm: no %d x %d tile", tr, tc);
  auto esize = [](DT t) { return t == F32 ? 4 : 2; };
  bool vec = !a.ptrs && a.lda % 8 == 0 && a.ldb % 8 == 0 && a.sa % 8 == 0 && a.sb % 8 == 0 &&
             a.A % (8 * esize(ta_)) == 0 && a.B % (8 * esize(tb_)) == 0;
  if (vec) a.biasType |= 256;
  int bk = (tc >= 48 && tr >= 48) || (tc == 32 && tr >= 80) ? 16 : 32;
  static const bool floatAcc = getenv("LOCALFOLD_GEMM_FLOAT_ACC") && strcmp(getenv("LOCALFOLD_GEMM_FLOAT_ACC"), "0") != 0;
  const bool hacc = !floatAcc && !accFloat && ta_ == F16 && tb_ == F16 && tc_ == F16;
  const bool hmma = halfMma && !(ta_ == F16 && tb_ == F16);     // (half staging of an f32 operand)
  auto mtype = [](DT t) { return t == F32 ? "float" : "half"; };
  int ep = (a.epilogue & 256 ? 1 : 0) | (hacc ? 8 : 0) | (hmma ? 32 : 0);
  std::string targs = std::string(mtype(ta_)) + ", " + mtype(tb_) + ", " + mtype(tc_) + ", " + std::to_string(tr) + ", " +
                      std::to_string(tc) + ", " + (a.ta ? "true" : "false") + ", " + (a.tb ? "true" : "false") + ", " +
                      std::to_string(bk) + ", " + std::to_string(ep);
  auto tag = [](DT t) { return t == F32 ? "f" : "h"; };
  std::string name = std::string("gemm_") + tag(ta_) + tag(tb_) + tag(tc_) + "_" + std::to_string(tr) + "x" + std::to_string(tc) +
                     "_" + (a.ta ? "T" : "N") + (a.tb ? "T" : "N") + "_k" + std::to_string(bk) + "_e" + std::to_string(ep);
  std::string decl = "template [[host_name(\"" + name + "\")]] kernel void lf_gemm<" + targs + ">(constant GemmArgs&, uint3, uint, uint, uint);";
  Grid grid{(uint32_t)((a.m + tc - 1) / tc), (uint32_t)((a.n + tr - 1) / tr), (uint32_t)batch};
  std::string lab;
  if (D().profileOn) {
    char b[160]; snprintf(b, sizeof b, "%s %s %dx%dx%d%s", label ? label : "gemm", name.c_str() + 5, a.m, a.n, a.k, batch > 1 ? " batched" : "");
    lab = b;
  }
  dispatchInstance(name, decl, &a, sizeof a, grid, 128, 0, lab.empty() ? nullptr : lab.c_str());
}
}  // namespace
void gemm(const Gemm& g) {
  if (!g.rows || !g.out || g.batch <= 0) return;
  GemmArgs a{};
  a.A = (uint64_t)g.W; a.B = (uint64_t)g.X; a.C = (uint64_t)(g.Yin ? g.Yin : g.Y); a.D = (uint64_t)g.Y;
  a.m = g.out; a.n = (int)g.rows; a.k = g.in;
  a.lda = g.ldw ? g.ldw : (g.transW ? g.in : g.out);
  a.ldb = g.ldx ? g.ldx : (g.transX ? (int)g.rows : g.in);
  a.ldc = a.ldd = g.ldy ? g.ldy : g.out;
  a.ta = g.transW; a.tb = g.transX;
  a.sa = g.sw; a.sb = g.sx; a.sc = a.sd = g.sy;
  a.alpha = g.alpha; a.beta = g.beta;
  if (g.bias) { a.bias = (uint64_t)g.bias; a.epilogue |= 4; a.biasType = g.tbias == F16 ? 2 : 0; }
  if (g.relu) a.epilogue |= 2;
  if (g.gelu) a.epilogue |= 32;
  gemmRun(g.tw, g.tx, g.ty, a, g.batch, g.half, g.accFloat, g.label);
}
void gemmGatedAdd(const half* X, const half* W, const half* aux, float* pair, size_t rows, int in, int out, const float* bias) {
  GemmArgs a{};
  a.A = (uint64_t)W; a.B = (uint64_t)X; a.C = a.D = (uint64_t)pair;
  a.m = out; a.n = (int)rows; a.k = in; a.lda = out; a.ldb = in; a.ldc = a.ldd = out;
  a.epilogue = 64; a.alpha = 1.f;
  a.aux = (uint64_t)aux; a.ldaux = out;
  if (bias) { a.bias = (uint64_t)bias; a.epilogue |= 4; }
  gemmRun(F16, F16, F32, a, 1, false, false, "gated add");
}
void gemmSwiglu(const half* X, const half* Wpairs, half* gated, size_t rows, int in, int hidden) {
  if (hidden % 8) die("gemmSwiglu: a hidden width of %d is not a multiple of 8", hidden);
  GemmArgs a{};
  a.A = (uint64_t)Wpairs; a.B = (uint64_t)X; a.C = a.D = (uint64_t)gated;
  a.m = 2 * hidden; a.n = (int)rows; a.k = in; a.lda = 2 * hidden; a.ldb = in; a.ldc = a.ldd = hidden;
  a.epilogue = 128; a.alpha = 1.f;
  gemmRun(F16, F16, F16, a, 1, false, false, "swiglu");
}
void gemmTriGate(const half* X, const half* W, const float* mask, half* outA, half* outB, size_t r0, size_t rows, int C,
                 size_t pairs, int n, int np, const float* bias) {
  GemmArgs g{};
  g.A = (uint64_t)W; g.B = (uint64_t)X; g.C = g.D = (uint64_t)outA;
  g.m = 4 * C; g.n = (int)rows; g.k = C; g.lda = 4 * C; g.ldb = C; g.ldc = g.ldd = 4 * C;
  g.epilogue = 256; g.alpha = 1.f;
  g.aux = (uint64_t)mask; g.aux2 = (uint64_t)outA; g.aux3 = (uint64_t)outB;
  g.tgR0 = (int64_t)r0; g.tgPairs = (int64_t)pairs; g.tgN = n; g.tgNp = np; g.tgC = C;
  if (bias) { g.bias = (uint64_t)bias; g.epilogue |= 4; }
  gemmRun(F16, F16, F16, g, 1, false, false, "triangle gate");
}

// ---------------------------------------------------------------- common kernels
static void layerNormRun(const float* x, const half* xh, float* y, half* yh, size_t rows, int C, const float* scale,
                         const float* offset, float eps, int ldx, int ldy) {
  if (!rows) return;
  LayerNormArgs a{x, xh, y, yh, scale, offset, rows, C, ldx ? ldx : C, ldy ? ldy : C, eps};
  // a simdgroup a row, eight a threadgroup
  size_t groups = (rows + 7) / 8;
  Grid g = groups <= 65535 ? Grid{(uint32_t)groups, 1, 1} : Grid{65535, (uint32_t)((groups + 65534) / 65535), 1};
  dispatch(C % 4 == 0 && C <= 1024 ? "lf_layernorm4" : "lf_layernorm", &a, sizeof a, g, 256, 0, "layernorm");
}
void layerNorm(const float* x, float* y, size_t rows, int C, const float* s, const float* o, float eps, int ldx, int ldy) {
  layerNormRun(x, nullptr, y, nullptr, rows, C, s, o, eps, ldx, ldy);
}
void layerNorm(const float* x, half* y, size_t rows, int C, const float* s, const float* o, float eps, int ldx, int ldy) {
  layerNormRun(x, nullptr, nullptr, y, rows, C, s, o, eps, ldx, ldy);
}
void layerNorm(const half* x, half* y, size_t rows, int C, const float* s, const float* o, float eps, int ldx, int ldy) {
  layerNormRun(nullptr, x, nullptr, y, rows, C, s, o, eps, ldx, ldy);
}
void toHalf(const float* x, half* y, size_t n) { run1d("lf_to_half", (n + 3) / 4, ConvArgs{x, y, n}); }
void toFloat(const half* x, float* y, size_t n) { run1d("lf_to_float", (n + 3) / 4, ConvBackArgs{x, y, n}); }
void add(float* y, const float* x, size_t n, float a) { run1d("lf_add", (n + 3) / 4, AddArgs{y, x, n, a, 0}); }
void addBias(float* y, const float* b, size_t rows, int C, int act) { run1d("lf_add_bias", rows * C, BiasArgs{y, b, rows, C, act}); }

// ---------------------------------------------------------------- profiling
bool profiling() { return D().profiling; }
void profileStart() {
  Device& d = D();
  if (!d.profiling) return;
  d.sync(); d.profiled.clear(); d.profileOn = true;
}
void profileReport(const char* stage, int top) {
  Device& d = D();
  if (!d.profileOn) return;
  d.sync(); d.profileOn = false;
  std::map<std::string, std::pair<double, int>> by;
  double total = 0;
  for (auto& [name, c] : d.profiled) {
    double ms = (c.GPUEndTime - c.GPUStartTime) * 1e3;
    by[name].first += ms; by[name].second += 1; total += ms;
  }
  std::vector<std::pair<std::string, std::pair<double, int>>> rows(by.begin(), by.end());
  std::sort(rows.begin(), rows.end(), [](auto& a, auto& b) { return a.second.first > b.second.first; });
  printf("profile %s: %.1f ms of GPU time in %zu dispatches\n", stage, total, d.profiled.size());
  for (int i = 0; i < (int)rows.size() && i < top; ++i)
    printf("  %8.2f ms %5.1f%% %6d  %s\n", rows[i].second.first, 100 * rows[i].second.first / std::max(total, 1e-9),
           rows[i].second.second, rows[i].first.c_str());
  d.profiled.clear();
}
double now() { return std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count(); }
void printStats() {
  Device& d = D(); auto& s = d.stats;
  fprintf(stderr, "metal: peak %.2f GB, %ld dispatches (%ld GEMMs), %ld commits, %ld syncs %.0f ms waiting, %ld allocations, "
          "%ld staged uploads, compiling %.0f ms\n", d.peak / 1e9, s.dispatches, s.gemms, s.commits, s.syncs, s.syncMs,
          s.allocs, s.staged, s.compileMs);
}
}  // namespace mt
