// The CUDA runtime, cuBLAS and cuBLASLt on Metal (declared in lfcuda.h).
//
// Memory: every allocation is one shared MTLBuffer and its device pointer is the buffer's GPU address, so the
// ports' pointer arithmetic, structs of pointers and arrays of pointers all hold as they are. Unified memory
// makes the same bytes the host's, through the buffer's contents.
//
// Order: every stream is the one queue, and every dispatch goes into the current compute encoder, which runs its
// dispatches serially - CUDA's stream order. A device-to-host copy waits for the queue; a host-to-device copy
// writes in place when the queue is idle and otherwise stages its bytes and copies them in order on the GPU.
//
// Kernels: the port's translated source (cu2metal.py) compiled from source, one explicit instantiation per
// specialisation a launch asks for. Specialisations seen before (a cache beside the weights) are compiled together
// up front; a new one costs a compile of its own and is remembered.
#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#include "lfcuda.h"
#include <mach-o/dyld.h>
#include <sys/stat.h>
#include <algorithm>
#include <atomic>
#include <chrono>
#include <climits>
#include <condition_variable>
#include <fstream>
#include <map>
#include <mutex>
#include <set>
#include <sstream>
#include <sys/stat.h>
#include <sys/sysctl.h>
#include <thread>
#include <unordered_map>

namespace lf {
// (the port's translation: lfport.mm, generated by metal/build.sh)
extern const KernelInfo PORT_KERNELS[];
extern const int PORT_KERNEL_COUNT;
extern const char* PORT_SOURCE;
extern const char* PORT_NAME;
extern const char* RUNTIME_SOURCE;
}

namespace {
[[noreturn]] void die(const std::string& what) {
  fprintf(stderr, "localfold-metal: %s\n", what.c_str());
  fflush(stderr);
  std::exit(1);
}

struct Alloc { id<MTLBuffer> buf; uint64_t addr; size_t size; };

struct Op {        // a captured graph's step
  int kind;        // 0 dispatch, 1 copy, 2 fill
  id<MTLComputePipelineState> pso; std::vector<unsigned char> args; MTLSize grid, block; size_t smem;
  uint64_t dst, src; size_t bytes; int value;
  std::vector<id<MTLBuffer>> keep;
  std::string label;
};

struct Runtime {
  std::recursive_mutex mu;
  id<MTLDevice> dev;
  id<MTLCommandQueue> queue;
  id<MTLLibrary> runtimeLib;
  std::map<uint64_t, Alloc> allocs;
  size_t allocated = 0, peak = 0;
  id<MTLCommandBuffer> cb = nil;
  id<MTLComputeCommandEncoder> enc = nil;
  std::vector<id<MTLBuffer>> cbKeep;           // released when the command buffer is done
  id<MTLCommandBuffer> lastCommitted = nil;
  int encoded = 0, encodedInEncoder = 0;
  // a graph capture belongs to the thread that began it (cudaStreamCaptureModeThreadLocal, the mode every port uses):
  // another thread's work - a weight upload beside a warm-up - runs as it is, not into that thread's graph. It was
  // global, so an upload issued during the warm-up sampler's capture went into the graph and its event records were
  // dropped, and the decode buffer they guarded was overwritten before its decode ran: ESMFold2's folding weights
  // came out wrong a few times in a hundred (1QYS 13.5 A or NaN against 0.865), under load or on a slow first run
  bool captureActive = false; std::thread::id captureThread;
  bool capturingHere() const { return captureActive && std::this_thread::get_id() == captureThread; }
  // the command buffers committed and not yet complete, by commit order (their completion handlers remove them)
  std::mutex inflightMu; std::condition_variable inflightDone; std::set<long> pending; long committedSeq = 0;
  std::mutex gpuErrorMu; std::string gpuError;   // the first command buffer to fail (commit's completion handler)
  std::vector<Op>* capture = nullptr;
  std::unordered_map<std::string, id<MTLComputePipelineState>> pipelines;
  std::map<std::string, id<MTLComputePipelineState>> runtimePipelines;
  std::set<std::string> knownSpecs;
  std::string specsPath;
  bool specsLoaded = false;
  // LOCALFOLD_METAL_STATS: where the host's time goes (printed at exit)
  struct Stats { double launchMs = 0, syncMs = 0, compileMs = 0; long launches = 0, syncs = 0, staged = 0, encoders = 0,
                 directCopies = 0, commits = 0, allocs = 0, commitsThreshold = 0, commitsEvent = 0, idleChecks = 0, graphLaunches = 0, graphOps = 0, dispatches = 0, captures = 0, capturedOps = 0, copies = 0, fills = 0, gemms = 0, memsetCalls = 0, memcpyCalls = 0; } stats;
  bool statsOn = getenv("LOCALFOLD_METAL_STATS") != nullptr;
  bool untracked = getenv("LF_UNTRACKED") != nullptr;
  // profiling: GPU time per kernel name
  bool profiling = false;
  std::map<std::string, std::pair<double, int>> profile;
  std::vector<std::pair<std::string, id<MTLCommandBuffer>>> profiled;

  Runtime() {
    @autoreleasepool {
      NSArray<id<MTLDevice>>* devices = MTLCopyAllDevices();
      if (devices.count == 0) die("no Metal device");
      dev = devices[0];
      if (![dev supportsFamily:MTLGPUFamilyMetal3] || ![dev supportsFamily:MTLGPUFamilyApple7])
        die(std::string("this GPU (") + dev.name.UTF8String + ") is not an Apple-silicon GPU with Metal 3; LocalFold needs an M1 or later");
      queue = [dev newCommandQueueWithMaxCommandBufferCount:64];
      runtimeLib = compile(lf::RUNTIME_SOURCE, "the runtime's kernels");
    }
  }

  id<MTLLibrary> compile(const std::string& source, const std::string& what) {
    MTLCompileOptions* o = [MTLCompileOptions new];
    o.languageVersion = MTLLanguageVersion3_0;
    o.fastMathEnabled = NO;
    NSError* e = nil;
    id<MTLLibrary> lib = [dev newLibraryWithSource:[NSString stringWithUTF8String:source.c_str()] options:o error:&e];
    if (!lib) die("compiling " + what + ":\n" + (e ? e.localizedDescription.UTF8String : "?"));
    return lib;
  }

  // ---- memory
  const Alloc* find(uint64_t addr) {
    auto it = allocs.upper_bound(addr);
    if (it == allocs.begin()) return nullptr;
    --it;
    if (addr >= it->second.addr && addr < it->second.addr + std::max<size_t>(it->second.size, 1)) return &it->second;
    return nullptr;
  }
  void* host(const void* device) {
    const Alloc* a = find((uint64_t)device);
    if (!a) return nullptr;
    return (char*)a->buf.contents + ((uint64_t)device - a->addr);
  }
  void* host(const void* device, size_t bytes, const char* what) {
    const Alloc* a = find((uint64_t)device);
    if (!a) die(std::string(what) + ": not a device pointer");
    if ((uint64_t)device + bytes > a->addr + a->size) die(std::string(what) + ": past the end of its allocation");
    return (char*)a->buf.contents + ((uint64_t)device - a->addr);
  }
  void* malloc_(size_t bytes) {
    std::lock_guard<std::recursive_mutex> l(mu);
    size_t n = std::max<size_t>((bytes + 255) & ~(size_t)255, 256);
    id<MTLBuffer> b = [dev newBufferWithLength:n options:MTLResourceStorageModeShared |
                       (untracked ? MTLResourceHazardTrackingModeUntracked : 0)];
    ++stats.allocs;
    if (!b) return nullptr;
    uint64_t addr = b.gpuAddress;
    allocs[addr] = {b, addr, bytes};
    allocated += n; peak = std::max(peak, allocated);
    if (enc) [enc useResource:b usage:MTLResourceUsageRead | MTLResourceUsageWrite];
    return (void*)addr;
  }
  void free_(void* p) {
    if (!p) return;
    std::lock_guard<std::recursive_mutex> l(mu);
    auto it = allocs.find((uint64_t)p);
    if (it == allocs.end()) return;
    allocated -= std::max<size_t>((it->second.size + 255) & ~(size_t)255, 256);
    cbKeep.push_back(it->second.buf);           // (alive until the work that may use it is done)
    allocs.erase(it);
  }

  // ---- the queue
  void ensureEncoder() {
    if (enc) return;
    if (!cb) cb = [queue commandBufferWithUnretainedReferences];
    enc = [cb computeCommandEncoderWithDispatchType:MTLDispatchTypeSerial];
    ++stats.encoders;
    encodedInEncoder = 0;
    std::vector<id<MTLResource>> all;
    all.reserve(allocs.size());
    for (auto& [_, a] : allocs) all.push_back(a.buf);
    if (!all.empty()) [enc useResources:all.data() count:all.size() usage:MTLResourceUsageRead | MTLResourceUsageWrite];
  }
  void commit() {
    if (enc) { [enc endEncoding]; enc = nil; }
    if (!cb) return;
    if (!cbKeep.empty()) {
      __block std::vector<id<MTLBuffer>> keep = std::move(cbKeep);
      cbKeep.clear();
      [cb addCompletedHandler:^(id<MTLCommandBuffer>) { keep.clear(); }];
    }
    // every command buffer reports a failure, not only the last before a sync: one committed mid-stream (every 256
    // dispatches) that fails - out of memory under another process's load, the GPU's watchdog - skips its work, and
    // unchecked the fold would carry on from the skipped work's buffers as if it had run
    long seq;
    { std::lock_guard<std::mutex> g(inflightMu); seq = ++committedSeq; pending.insert(seq); }
    [cb addCompletedHandler:^(id<MTLCommandBuffer> done) {
      if (done.error) {
        std::lock_guard<std::mutex> g(gpuErrorMu);
        if (gpuError.empty()) gpuError = done.error.localizedDescription.UTF8String;
      }
      { std::lock_guard<std::mutex> g(inflightMu); pending.erase(seq); }
      inflightDone.notify_all();
    }];
    [cb commit];
    ++stats.commits;
    lastCommitted = cb;
    cb = nil;
    encoded = 0;
  }
  void sync() {
    std::lock_guard<std::recursive_mutex> l(mu);
    commit();
    ++stats.syncs;
    if (lastCommitted) {
      auto t0 = std::chrono::steady_clock::now();
      [lastCommitted waitUntilCompleted];
      stats.syncMs += std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - t0).count();
      if (lastCommitted.error) die(std::string("the GPU failed: ") + lastCommitted.error.localizedDescription.UTF8String);
      lastCommitted = nil;
    }
    // ...and EVERY command buffer done, not just the last: Metal may finish one it sees no dependency on before an
    // earlier one, and a host read after a sync must see all of them
    waitThrough(LONG_MAX);
    std::lock_guard<std::mutex> g(gpuErrorMu);
    if (!gpuError.empty()) die("the GPU failed: " + gpuError);
  }
  // idle: nothing encoded and nothing in flight - every committed command buffer completed (the last alone completing
  // says nothing of an earlier one Metal ran beside it), so a host write straight into a buffer cannot race the GPU
  bool idle() { std::lock_guard<std::mutex> g(inflightMu); return !cb && pending.empty(); }
  // every command buffer committed at or before `seq` complete (an event's wait: the work before its record)
  void waitThrough(long seq) {
    std::unique_lock<std::mutex> g(inflightMu);
    inflightDone.wait(g, [&] { return pending.empty() || *pending.begin() > seq; });
  }

  // a runtime kernel that is a template (the GEMM): its explicit instantiation compiled with the runtime's source on
  // first use, as the port's kernels are
  id<MTLComputePipelineState> runtimeInstance(const std::string& host, const std::string& decl) {
    auto it = runtimePipelines.find(host);
    if (it != runtimePipelines.end()) return it->second;
    auto t0 = std::chrono::steady_clock::now();
    id<MTLLibrary> lib = compile(std::string(lf::RUNTIME_SOURCE) + "\n" + decl + "\n", host);
    stats.compileMs += std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - t0).count();
    id<MTLComputePipelineState> p = pipelineOf(lib, host);
    runtimePipelines[host] = p;
    return p;
  }
  id<MTLComputePipelineState> runtimePipeline(const std::string& name) {
    auto it = runtimePipelines.find(name);
    if (it != runtimePipelines.end()) return it->second;
    id<MTLFunction> f = [runtimeLib newFunctionWithName:[NSString stringWithUTF8String:name.c_str()]];
    if (!f) die("no runtime kernel " + name);
    NSError* e = nil;
    id<MTLComputePipelineState> p = [dev newComputePipelineStateWithFunction:f error:&e];
    if (!p) die("runtime kernel " + name + ": " + e.localizedDescription.UTF8String);
    runtimePipelines[name] = p;
    return p;
  }
  void dispatch(id<MTLComputePipelineState> pso, const void* args, size_t argBytes, MTLSize grid, MTLSize block,
                size_t smem, const std::string& label = "") {
    if (grid.width == 0 || grid.height == 0 || grid.depth == 0) return;
    if (capturingHere()) {
      Op op{}; op.kind = 0; op.pso = pso; op.args.assign((const unsigned char*)args, (const unsigned char*)args + argBytes);
      op.grid = grid; op.block = block; op.smem = smem; op.label = label;
      capture->push_back(std::move(op));
      return;
    }
    // a pipeline's thread limit falls as its kernel takes registers, and Metal does not run a dispatch past it - no error,
    // the output left as it was - so the dispatch is refused here, naming the kernel
    if (block.width * block.height * block.depth > pso.maxTotalThreadsPerThreadgroup)
      die("a dispatch of " + std::to_string(block.width * block.height * block.depth) + " threads a threadgroup to a kernel that takes at most " +
          std::to_string(pso.maxTotalThreadsPerThreadgroup) + (label.empty() ? std::string("") : " (" + label + ")"));
    ensureEncoder();
    ++stats.dispatches;
    [enc setComputePipelineState:pso];
    if (argBytes <= 4096) [enc setBytes:args length:std::max<size_t>(argBytes, 4) atIndex:0];
    else {
      id<MTLBuffer> b = [dev newBufferWithBytes:args length:argBytes options:MTLResourceStorageModeShared];
      if (!b) die("out of memory for a kernel's arguments (" + std::to_string(argBytes) + " bytes)");
      cbKeep.push_back(b);
      [enc setBuffer:b offset:0 atIndex:0];
    }
    [enc setThreadgroupMemoryLength:std::max<size_t>((smem + 15) & ~(size_t)15, 16) atIndex:0];
    // (untracked buffers: the order between this dispatch and the last is the barrier's)
    if (encodedInEncoder++ && untracked) [enc memoryBarrierWithScope:MTLBarrierScopeBuffers];
    [enc dispatchThreadgroups:grid threadsPerThreadgroup:block];
    if (profiling && !label.empty()) {      // (a command buffer a dispatch: its GPU time is the kernel's)
      id<MTLCommandBuffer> mine = cb;
      commit();
      profiled.push_back({label, mine});
    } else if (++encoded >= 256) {
      ++stats.commitsThreshold;
      commit();                             // (let the GPU start while the host encodes the rest)
    }
  }
  void copy(uint64_t dst, uint64_t src, size_t bytes) {
    ++stats.copies;
    struct { uint64_t dst, src, bytes; } a = {dst, src, bytes};
    size_t threads = ((dst | src) & 15) == 0 ? std::max<size_t>(bytes / 16, 16) : bytes;
    size_t groups = (threads + 255) / 256;
    MTLSize grid = groups > 65535 ? MTLSizeMake(65535, (groups + 65534) / 65535, 1) : MTLSizeMake(groups, 1, 1);
    if (capturingHere()) {
      Op op{}; op.kind = 1; op.dst = dst; op.src = src; op.bytes = bytes; capture->push_back(op); return;
    }
    dispatch(runtimePipeline("lf_copy"), &a, sizeof a, grid, MTLSizeMake(256, 1, 1), 0);
  }
  void fill(uint64_t dst, int value, size_t bytes) {
    ++stats.fills;
    struct { uint64_t dst, bytes; uint32_t value; uint32_t pad; } a = {dst, bytes, (uint32_t)value, 0};
    size_t threads = (dst & 15) == 0 ? std::max<size_t>(bytes / 16, 16) : bytes;
    size_t groups = (threads + 255) / 256;
    MTLSize grid = groups > 65535 ? MTLSizeMake(65535, (groups + 65534) / 65535, 1) : MTLSizeMake(groups, 1, 1);
    if (capturingHere()) {
      Op op{}; op.kind = 2; op.dst = dst; op.bytes = bytes; op.value = value; capture->push_back(op); return;
    }
    dispatch(runtimePipeline("lf_fill"), &a, sizeof a, grid, MTLSizeMake(256, 1, 1), 0);
  }

  // ---- the port's kernels
  void loadSpecs() {
    if (specsLoaded) return;
    specsLoaded = true;
    const char* home = getenv("HOME");
    std::string dir = std::string(home ? home : "/tmp") + "/.cache/localfold/metal";
    mkdir((std::string(home ? home : "/tmp") + "/.cache").c_str(), 0755);
    mkdir((std::string(home ? home : "/tmp") + "/.cache/localfold").c_str(), 0755);
    mkdir(dir.c_str(), 0755);
    size_t h = std::hash<std::string>()(lf::PORT_SOURCE);
    char name[64]; snprintf(name, sizeof name, "/%s-%016zx.specs", lf::PORT_NAME, h);
    specsPath = dir + name;
    // a first run: the list a wheel ships beside the binary (bin/metal-specs/<port>-<hash>.specs, the specialisations
    // its build's folds used), so even a first fold compiles its kernels up front and in parallel
    struct stat st;
    if (stat(specsPath.c_str(), &st) != 0) {
      char exe[4096]; uint32_t size = sizeof exe;
      if (_NSGetExecutablePath(exe, &size) == 0) {
        std::string bundled = std::string(exe);
        bundled = bundled.substr(0, bundled.rfind('/')) + "/metal-specs" + name;
        std::ifstream src(bundled);
        if (src) { std::ofstream dst(specsPath); dst << src.rdbuf(); }
      }
    }
    std::ifstream in(specsPath);
    std::string line, inst;
    std::vector<std::string> names;
    while (std::getline(in, line)) {
      size_t tab = line.find('\t');
      if (tab == std::string::npos) continue;
      knownSpecs.insert(line.substr(0, tab));
      names.push_back(line.substr(0, tab));
      inst += line.substr(tab + 1) + "\n";
    }
    if (names.empty()) return;
    // every specialisation a previous run used, in one library (and in parallel chunks: the compiler is single-threaded)
    size_t chunks = std::min<size_t>(8, (names.size() + 15) / 16);
    std::vector<std::string> parts(chunks);
    std::vector<std::vector<std::string>> partNames(chunks);
    {
      std::istringstream lines(inst);
      size_t k = 0;
      while (std::getline(lines, line)) { parts[k % chunks] += line + "\n"; partNames[k % chunks].push_back(names[k]); ++k; }
    }
    // ...and each chunk's pipelines made on its own thread too: a pipeline is where the GPU's own compiler runs, and on
    // a cold system cache that was most of an AF3 first fold's ~10 s of compiling, one pipeline at a time
    std::vector<std::vector<id<MTLComputePipelineState>>> made(chunks);
    std::vector<std::thread> threads;
    for (size_t c = 0; c < chunks; ++c)
      threads.emplace_back([&, c] { @autoreleasepool {
        id<MTLLibrary> lib = compile(std::string(lf::PORT_SOURCE) + parts[c], "the cached kernels");
        for (auto& n : partNames[c]) made[c].push_back(pipelineOf(lib, n));
      } });
    for (auto& t : threads) t.join();
    for (size_t c = 0; c < chunks; ++c)
      for (size_t i = 0; i < partNames[c].size(); ++i) pipelines[partNames[c][i]] = made[c][i];
  }
  id<MTLComputePipelineState> pipelineOf(id<MTLLibrary> lib, const std::string& host) {
    id<MTLFunction> f = [lib newFunctionWithName:[NSString stringWithUTF8String:host.c_str()]];
    if (!f) die("no compiled kernel " + host);
    NSError* e = nil;
    id<MTLComputePipelineState> p = [dev newComputePipelineStateWithFunction:f error:&e];
    if (!p) die(host + ": " + (e ? e.localizedDescription.UTF8String : "?"));
    return p;
  }
  id<MTLComputePipelineState> kernel(int index, const std::string& targs) {
    const lf::KernelInfo& k = lf::PORT_KERNELS[index];
    std::string host = k.structName;
    host += "__" + targs;
    for (char& c : host) if (!isalnum((unsigned char)c) && c != '_') c = '_';
    auto it = pipelines.find(host);
    if (it != pipelines.end()) return it->second;
    loadSpecs();
    it = pipelines.find(host);
    if (it != pipelines.end()) return it->second;
    if (k.status == 2) die(std::string("kernel ") + k.name + " has no Metal translation yet (it is " +
                           "inline PTX or uses a construct cu2metal.py cannot translate) and nothing overrides it");
    std::string inst = std::string("template [[host_name(\"") + host + "\")]] kernel void " + k.name + "<" + targs +
                       ">(constant " + k.structName + "<" + targs + ">&, threadgroup char*, uint3, uint3, uint3, uint3, uint, uint, uint);";
    auto t0 = std::chrono::steady_clock::now();
    id<MTLLibrary> lib = compile(std::string(lf::PORT_SOURCE) + "\n" + inst + "\n", std::string("kernel ") + k.name + "<" + targs + ">");
    stats.compileMs += std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - t0).count();
    id<MTLComputePipelineState> p = pipelineOf(lib, host);
    if (getenv("LOCALFOLD_METAL_VERBOSE"))
      fprintf(stderr, "metal: compiled %s<%s> in %.0f ms\n", k.name, targs.c_str(),
              std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - t0).count());
    pipelines[host] = p;
    if (!knownSpecs.count(host)) {
      knownSpecs.insert(host);
      std::ofstream out(specsPath, std::ios::app);
      out << host << "\t" << inst << "\n";
    }
    return p;
  }
};

// LOCALFOLD_METAL_SPECS_NAME=1: print this binary's specialisation list's file name and exit (python/build_wheel_macos.sh)
__attribute__((constructor)) static void printSpecsName() {
  if (!getenv("LOCALFOLD_METAL_SPECS_NAME")) return;
  printf("%s-%016zx.specs\n", lf::PORT_NAME, std::hash<std::string>()(lf::PORT_SOURCE));
  exit(0);
}
Runtime& R() {
  static Runtime* r = [] {
    Runtime* rt = new Runtime();
    if (rt->statsOn) atexit([] {
      auto& s = R().stats;
      fprintf(stderr, "metal stats: %ld launches %.1f ms encoding, %ld syncs %.1f ms waiting, %ld commits, %ld encoders, "
              "%ld staged copies, %ld allocations, %zu live, compiles %.0f ms; commits by threshold %ld, by event %ld; %ld dispatches, %ld graph launches of %ld ops, %ld captures of %ld ops; copies %ld fills %ld gemms %ld memcpy %ld memset %ld\n", s.launches, s.launchMs, s.syncs, s.syncMs,
              s.commits, s.encoders, s.staged, s.allocs, R().allocs.size(), s.compileMs, s.commitsThreshold, s.commitsEvent, s.dispatches, s.graphLaunches, s.graphOps, s.captures, s.capturedOps, s.copies, s.fills, s.gemms, s.memcpyCalls, s.memsetCalls);
    });
    return rt;
  }();
  return *r;
}
thread_local lf::Launch CURRENT;
thread_local cudaError_t LAST_ERROR = cudaSuccess;
}  // namespace

namespace lf {
void setLaunchRaw(dim3 grid, dim3 block, size_t smem) { CURRENT = {grid, block, smem}; }
void launch(int index, std::initializer_list<std::string> targs, KArgs& args) {
  Runtime& r = R();
  std::lock_guard<std::recursive_mutex> l(r.mu);
  auto t0 = std::chrono::steady_clock::now();
  struct Done { Runtime& r; std::chrono::steady_clock::time_point t0;
    ~Done() { ++r.stats.launches; r.stats.launchMs += std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - t0).count(); } } done{r, t0};
  std::string ta;
  for (auto& t : targs) ta += (ta.empty() ? "" : ", ") + t;
  if (ta.empty()) ta = "0";
  id<MTLComputePipelineState> pso = r.kernel(index, ta);
  Launch L = CURRENT;
  static bool trace = getenv("LOCALFOLD_METAL_TRACE") != nullptr;
  if (trace) {
    static std::set<std::string> seen;
    std::string key = std::string(PORT_KERNELS[index].name) + "<" + ta + ">";
    if (seen.insert(key).second) fprintf(stderr, "trace: %s grid %u,%u,%u block %u,%u,%u smem %zu\n", key.c_str(),
                                         L.grid.x, L.grid.y, L.grid.z, L.block.x, L.block.y, L.block.z, L.smem);
  }
  // (an overridden kernel lays out its own threadgroup memory within the device's: the host asked for the CUDA layout)
  if (PORT_KERNELS[index].status == 1) L.smem = std::min<size_t>(L.smem, r.dev.maxThreadgroupMemoryLength - pso.staticThreadgroupMemoryLength);
  size_t threads = (size_t)L.block.x * L.block.y * L.block.z;
  if (threads > pso.maxTotalThreadsPerThreadgroup)
    die(std::string("kernel ") + PORT_KERNELS[index].name + "<" + ta + "> launched with " + std::to_string(threads) +
        " threads a block; this GPU runs it with at most " + std::to_string(pso.maxTotalThreadsPerThreadgroup));
  if (pso.staticThreadgroupMemoryLength + L.smem > r.dev.maxThreadgroupMemoryLength)
    die(std::string("kernel ") + PORT_KERNELS[index].name + "<" + ta + "> needs " +
        std::to_string(pso.staticThreadgroupMemoryLength + L.smem) + " bytes of threadgroup memory; this GPU has " +
        std::to_string(r.dev.maxThreadgroupMemoryLength));
  r.dispatch(pso, args.bytes.data(), args.bytes.size(), MTLSizeMake(L.grid.x, L.grid.y, L.grid.z),
             MTLSizeMake(L.block.x, L.block.y, L.block.z), L.smem, (r.profiling || r.capturingHere()) ? std::string(PORT_KERNELS[index].name) : "");
}
void* hostView(const void* device) { return R().host(device); }
void profileStart() {
  Runtime& r = R(); r.sync(); r.profile.clear(); r.profiled.clear(); r.profiling = true;
}
void profileStop(int top) {
  Runtime& r = R(); r.sync(); r.profiling = false;
  double total = 0;
  for (auto& [name, c] : r.profiled) {
    double ms = (c.GPUEndTime - c.GPUStartTime) * 1e3;
    r.profile[name].first += ms; r.profile[name].second += 1; total += ms;
  }
  std::vector<std::pair<std::string, std::pair<double, int>>> rows(r.profile.begin(), r.profile.end());
  std::sort(rows.begin(), rows.end(), [](auto& a, auto& b) { return a.second.first > b.second.first; });
  printf("profile: %.1f ms of GPU time in %zu dispatches (each its own command buffer: an upper bound)\n", total, r.profiled.size());
  for (int i = 0; i < (int)rows.size() && i < top; ++i)
    printf("  %8.2f ms %5.1f%% %6d  %s\n", rows[i].second.first, 100 * rows[i].second.first / std::max(total, 1e-9),
           rows[i].second.second, rows[i].first.c_str());
  r.profiled.clear();
}
}  // namespace lf

// ---------------------------------------------------------------- the runtime API
cudaError_t cudaMalloc(void** p, size_t bytes) {
  *p = R().malloc_(bytes);
  return *p ? cudaSuccess : (LAST_ERROR = cudaErrorMemoryAllocation);
}
cudaError_t cudaFree(void* p) { R().free_(p); return cudaSuccess; }
cudaError_t cudaMallocAsync(void** p, size_t bytes, cudaStream_t) { return cudaMalloc(p, bytes); }
cudaError_t cudaMallocFromPoolAsync(void** p, size_t bytes, cudaMemPool_t, cudaStream_t) { return cudaMalloc(p, bytes); }
cudaError_t cudaFreeAsync(void* p, cudaStream_t) { return cudaFree(p); }
cudaError_t cudaMallocHost(void** p, size_t bytes) {
  *p = nullptr;
  return posix_memalign(p, 16384, std::max<size_t>(bytes, 1)) == 0 ? cudaSuccess : cudaErrorMemoryAllocation;
}
cudaError_t cudaHostAlloc(void** p, size_t bytes, unsigned) { return cudaMallocHost(p, bytes); }
cudaError_t cudaFreeHost(void* p) { free(p); return cudaSuccess; }

static cudaMemcpyKind resolveKind(void* dst, const void* src, cudaMemcpyKind kind) {
  if (kind != cudaMemcpyDefault) return kind;
  bool d = R().find((uint64_t)dst), s = R().find((uint64_t)src);
  return d ? (s ? cudaMemcpyDeviceToDevice : cudaMemcpyHostToDevice) : (s ? cudaMemcpyDeviceToHost : cudaMemcpyHostToHost);
}
cudaError_t cudaMemcpyAsync(void* dst, const void* src, size_t bytes, cudaMemcpyKind kind, cudaStream_t) {
  if (bytes == 0) return cudaSuccess;
  Runtime& r = R();
  std::lock_guard<std::recursive_mutex> l(r.mu);
  ++r.stats.memcpyCalls;
  kind = resolveKind(dst, src, kind);
  switch (kind) {
    case cudaMemcpyHostToHost: memcpy(dst, src, bytes); break;
    case cudaMemcpyDeviceToHost:
      if (r.capturingHere()) die("a device-to-host copy inside a captured graph");
      r.sync();
      memcpy(dst, r.host(src, bytes, "cudaMemcpy source"), bytes);
      break;
    case cudaMemcpyHostToDevice:
      if (!r.capturingHere() && r.idle()) { memcpy(r.host(dst, bytes, "cudaMemcpy destination"), src, bytes); break; }
      {   // staged: the bytes now, the copy in stream order
        id<MTLBuffer> stage = [r.dev newBufferWithBytes:src length:bytes options:MTLResourceStorageModeShared];
        // (a nil one has GPU address 0, and the copy would read zeros there in silence: a fold of the wrong input)
        if (!stage) die("out of memory staging a " + std::to_string(bytes) + "-byte copy to the device");
        ++r.stats.staged;
        r.host(dst, bytes, "cudaMemcpy destination");
        if (r.capturingHere()) {
          Op op{}; op.kind = 1; op.dst = (uint64_t)dst; op.src = stage.gpuAddress; op.bytes = bytes; op.keep.push_back(stage);
          r.capture->push_back(op);
        } else {
          r.ensureEncoder();
          [r.enc useResource:stage usage:MTLResourceUsageRead];
          r.cbKeep.push_back(stage);
          r.copy((uint64_t)dst, stage.gpuAddress, bytes);
        }
      }
      break;
    default:
      r.host(dst, bytes, "cudaMemcpy destination"); r.host(src, bytes, "cudaMemcpy source");
      r.copy((uint64_t)dst, (uint64_t)src, bytes);
  }
  return cudaSuccess;
}
cudaError_t cudaMemcpy(void* dst, const void* src, size_t bytes, cudaMemcpyKind kind) {
  cudaMemcpyAsync(dst, src, bytes, kind, nullptr);
  kind = resolveKind(dst, src, kind);
  if (kind == cudaMemcpyHostToDevice || kind == cudaMemcpyDeviceToDevice) {}   // (ordered; nothing on the host waits)
  return cudaSuccess;
}
static void copy2d(void* dst, size_t dpitch, const void* src, size_t spitch, size_t width, size_t height, int value, bool fill) {
  Runtime& r = R();
  std::lock_guard<std::recursive_mutex> l(r.mu);
  if (width == 0 || height == 0) return;
  r.host(dst, (height - 1) * dpitch + width, "cudaMemcpy2D destination");
  if (!fill) r.host(src, (height - 1) * spitch + width, "cudaMemcpy2D source");
  struct { uint64_t dst, src, dpitch, spitch, width, height; uint32_t value, fill; } a =
    {(uint64_t)dst, (uint64_t)src, dpitch, spitch, width, height, (uint32_t)value, fill ? 1u : 0u};
  MTLSize grid = MTLSizeMake((width + 255) / 256, std::min<size_t>(height, 65535), (height + 65534) / 65535);
  r.dispatch(r.runtimePipeline("lf_copy2d"), &a, sizeof a, grid, MTLSizeMake(256, 1, 1), 0);
}
cudaError_t cudaMemcpy2DAsync(void* dst, size_t dpitch, const void* src, size_t spitch, size_t width, size_t height,
                              cudaMemcpyKind kind, cudaStream_t s) {
  kind = resolveKind(dst, src, kind);
  if (kind == cudaMemcpyDeviceToDevice) { copy2d(dst, dpitch, src, spitch, width, height, 0, false); return cudaSuccess; }
  for (size_t r = 0; r < height; ++r)       // (host on one side: row by row, each as a 1-D copy does)
    cudaMemcpyAsync((char*)dst + r * dpitch, (const char*)src + r * spitch, width, kind, s);
  return cudaSuccess;
}
cudaError_t cudaMemsetAsync(void* p, int value, size_t bytes, cudaStream_t) {
  if (bytes == 0) return cudaSuccess;
  Runtime& r = R();
  ++r.stats.memsetCalls;
  std::lock_guard<std::recursive_mutex> l(r.mu);
  void* h = r.host(p, bytes, "cudaMemset");
  if (!r.capturingHere() && r.idle()) { memset(h, value, bytes); return cudaSuccess; }
  r.fill((uint64_t)p, value, bytes);
  return cudaSuccess;
}
cudaError_t cudaMemset(void* p, int value, size_t bytes) { return cudaMemsetAsync(p, value, bytes, nullptr); }
cudaError_t cudaMemset2DAsync(void* p, size_t pitch, int value, size_t width, size_t height, cudaStream_t) {
  copy2d(p, pitch, nullptr, 0, width, height, value, true);
  return cudaSuccess;
}
cudaError_t cudaMemGetInfo(size_t* free, size_t* total) {
  Runtime& r = R();
  size_t t = r.dev.recommendedMaxWorkingSetSize, used = r.dev.currentAllocatedSize;
  *total = t; *free = used < t ? t - used : 0;
  return cudaSuccess;
}
cudaError_t cudaGetDevice(int* d) { *d = 0; return cudaSuccess; }
cudaError_t cudaSetDevice(int) { return cudaSuccess; }
cudaError_t cudaGetDeviceCount(int* n) { *n = 1; return cudaSuccess; }
static int gpuCores() {
  // (the number of GPU cores: IOKit's gpu-core-count; an estimate from the working set where it is not readable)
  static int cores = [] {
    int c = 0;
    if (const char* e = getenv("LOCALFOLD_GPU_CORES")) c = atoi(e);
    if (!c) {
      FILE* p = popen("ioreg -rc AGXAccelerator -d1 2>/dev/null | grep -o '\"gpu-core-count\" = [0-9]*' | grep -o '[0-9]*$'", "r");
      if (p) { if (fscanf(p, "%d", &c) != 1) c = 0; pclose(p); }
    }
    return c > 0 ? c : 8;
  }();
  return cores;
}
cudaError_t cudaDeviceGetAttribute(int* v, cudaDeviceAttr a, int) {
  switch (a) {
    case cudaDevAttrMultiProcessorCount: *v = gpuCores(); break;
    // (a T4's - sm_75: the ports' register-staged paths, no cp.async, no bf16 tensor-core GEMMs)
    case cudaDevAttrComputeCapabilityMajor: *v = 7; break;
    case cudaDevAttrComputeCapabilityMinor: *v = 5; break;
    case cudaDevAttrMaxSharedMemoryPerBlockOptin:
    case cudaDevAttrMaxSharedMemoryPerBlock: *v = (int)R().dev.maxThreadgroupMemoryLength; break;
    case cudaDevAttrMaxSharedMemoryPerMultiprocessor: *v = 65536; break;
    case cudaDevAttrMaxThreadsPerBlock: *v = 1024; break;
    case cudaDevAttrL2CacheSize: *v = 8 << 20; break;
    default: *v = 0;
  }
  return cudaSuccess;
}
cudaError_t cudaDeviceSynchronize() { R().sync(); return cudaSuccess; }
cudaError_t cudaDeviceReset() { R().sync(); return cudaSuccess; }
cudaError_t cudaStreamSynchronize(cudaStream_t) { R().sync(); return cudaSuccess; }
cudaError_t cudaStreamCreate(cudaStream_t* s) { *s = (cudaStream_t)0x10; return cudaSuccess; }
cudaError_t cudaStreamCreateWithFlags(cudaStream_t* s, unsigned) { *s = (cudaStream_t)0x10; return cudaSuccess; }
cudaError_t cudaStreamDestroy(cudaStream_t) { return cudaSuccess; }
cudaError_t cudaStreamWaitEvent(cudaStream_t, cudaEvent_t, unsigned) { return cudaSuccess; }
cudaError_t cudaStreamQuery(cudaStream_t) { return R().idle() ? cudaSuccess : cudaErrorNotReady; }

struct LfEvent_ { id<MTLCommandBuffer> cb = nil; double host = 0; long seq = 0; };   // seq: the commits before it
cudaError_t cudaEventCreate(cudaEvent_t* e) { *e = new LfEvent_(); return cudaSuccess; }
cudaError_t cudaEventCreateWithFlags(cudaEvent_t* e, unsigned) { return cudaEventCreate(e); }
cudaError_t cudaEventRecord(cudaEvent_t e, cudaStream_t) {
  Runtime& r = R();
  std::lock_guard<std::recursive_mutex> l(r.mu);
  if (r.capturingHere()) return cudaSuccess;
  ++r.stats.commitsEvent;
  r.commit();
  e->cb = r.lastCommitted;
  { std::lock_guard<std::mutex> g(r.inflightMu); e->seq = r.committedSeq; }
  e->host = std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count();
  return cudaSuccess;
}
cudaError_t cudaEventSynchronize(cudaEvent_t e) {
  if (e->cb) [e->cb waitUntilCompleted];
  R().waitThrough(e->seq);                   // (and every command buffer committed before it)
  return cudaSuccess;
}
cudaError_t cudaEventQuery(cudaEvent_t e) {
  Runtime& r = R();
  std::lock_guard<std::mutex> g(r.inflightMu);
  return r.pending.empty() || *r.pending.begin() > e->seq ? cudaSuccess : cudaErrorNotReady;
}
cudaError_t cudaEventElapsedTime(float* ms, cudaEvent_t a, cudaEvent_t b) {
  cudaEventSynchronize(a); cudaEventSynchronize(b);
  // (the GPU's end of the work before each: the time the queue took between them)
  double ta = a->cb ? a->cb.GPUEndTime : a->host, tb = b->cb ? b->cb.GPUEndTime : b->host;
  if (!a->cb || !b->cb) { ta = a->host; tb = b->host; }
  *ms = (float)((tb - ta) * 1e3);
  if (*ms < 0) *ms = 0;
  return cudaSuccess;
}
cudaError_t cudaEventDestroy(cudaEvent_t e) { delete e; return cudaSuccess; }
cudaError_t cudaGetLastError() { cudaError_t e = LAST_ERROR; LAST_ERROR = cudaSuccess; return e; }
cudaError_t cudaPeekAtLastError() { return LAST_ERROR; }
const char* cudaGetErrorString(cudaError_t e) {
  switch (e) {
    case cudaSuccess: return "no error";
    case cudaErrorMemoryAllocation: return "out of memory";
    case cudaErrorNotReady: return "not ready";
    default: return "invalid value";
  }
}
const char* cudaGetErrorName(cudaError_t e) { return cudaGetErrorString(e); }

struct LfGraph_ { std::vector<Op> ops; };
cudaError_t cudaStreamBeginCapture(cudaStream_t, cudaStreamCaptureMode) {
  Runtime& r = R();
  std::lock_guard<std::recursive_mutex> l(r.mu);
  r.captureActive = true; r.captureThread = std::this_thread::get_id();
  r.capture = new std::vector<Op>();
  return cudaSuccess;
}
cudaError_t cudaStreamEndCapture(cudaStream_t, cudaGraph_t* g) {
  Runtime& r = R();
  std::lock_guard<std::recursive_mutex> l(r.mu);
  r.captureActive = false;
  ++r.stats.captures; r.stats.capturedOps += r.capture->size();
  *g = new LfGraph_{std::move(*r.capture)};
  delete r.capture; r.capture = nullptr;
  return cudaSuccess;
}
cudaError_t cudaStreamIsCapturing(cudaStream_t, cudaStreamCaptureStatus* s) {
  *s = R().capturingHere() ? cudaStreamCaptureStatusActive : cudaStreamCaptureStatusNone;
  return cudaSuccess;
}
// (an executable graph is its own copy: the ports destroy the graph once it is instantiated)
cudaError_t cudaGraphInstantiate(cudaGraphExec_t* exec, cudaGraph_t g, unsigned long long) { *exec = new LfGraph_(*g); return cudaSuccess; }
cudaError_t cudaGraphInstantiate(cudaGraphExec_t* exec, cudaGraph_t g, cudaGraphNode_t*, char*, size_t) { *exec = new LfGraph_(*g); return cudaSuccess; }
cudaError_t cudaGraphLaunch(cudaGraphExec_t exec, cudaStream_t) {
  Runtime& r = R();
  std::lock_guard<std::recursive_mutex> l(r.mu);
  ++r.stats.graphLaunches; r.stats.graphOps += exec->ops.size();
  for (auto& op : exec->ops) {
    if (op.kind == 0) r.dispatch(op.pso, op.args.data(), op.args.size(), op.grid, op.block, op.smem, r.profiling ? op.label : "");
    else if (op.kind == 1) {
      if (!op.keep.empty()) { r.ensureEncoder(); for (auto& k : op.keep) [r.enc useResource:k usage:MTLResourceUsageRead]; }
      r.copy(op.dst, op.src, op.bytes);
    } else r.fill(op.dst, op.value, op.bytes);
  }
  return cudaSuccess;
}
cudaError_t cudaGraphExecDestroy(cudaGraphExec_t e) { delete e; return cudaSuccess; }
cudaError_t cudaGraphDestroy(cudaGraph_t g) { delete g; return cudaSuccess; }

struct LfMemPool_ { int unused; };
cudaError_t cudaMemPoolCreate(cudaMemPool_t* p, const cudaMemPoolProps*) { *p = new LfMemPool_(); return cudaSuccess; }
cudaError_t cudaDeviceGetDefaultMemPool(cudaMemPool_t* p, int) { static LfMemPool_ pool; *p = &pool; return cudaSuccess; }
cudaError_t cudaMemPoolSetAttribute(cudaMemPool_t, cudaMemPoolAttr, void*) { return cudaSuccess; }
cudaError_t cudaMemPoolGetAttribute(cudaMemPool_t, cudaMemPoolAttr a, void* v) {
  // (nothing is held idle: an allocation is freed when the port frees it)
  *(uint64_t*)v = (a == cudaMemPoolAttrReservedMemCurrent || a == cudaMemPoolAttrUsedMemCurrent) ? R().allocated : 0;
  return cudaSuccess;
}
cudaError_t cudaMemPoolTrimTo(cudaMemPool_t, size_t) { return cudaSuccess; }
cudaError_t lfSymbolAddress(void** p, const void* host, size_t bytes) {
  static std::map<const void*, void*> copies;
  Runtime& r = R();
  std::lock_guard<std::recursive_mutex> l(r.mu);
  auto it = copies.find(host);
  if (it == copies.end()) {
    void* d = r.malloc_(bytes);
    r.sync();
    memcpy(r.host(d), host, bytes);
    it = copies.emplace(host, d).first;
  }
  *p = it->second;
  return cudaSuccess;
}

// ---------------------------------------------------------------- cuBLAS
struct LfBlas_ { int unused; };
cublasStatus_t cublasCreate(cublasHandle_t* h) { *h = new LfBlas_(); return CUBLAS_STATUS_SUCCESS; }
cublasStatus_t cublasDestroy(cublasHandle_t h) { delete h; return CUBLAS_STATUS_SUCCESS; }
cublasStatus_t cublasSetStream(cublasHandle_t, cudaStream_t) { return CUBLAS_STATUS_SUCCESS; }
cublasStatus_t cublasSetWorkspace(cublasHandle_t, void*, size_t) { return CUBLAS_STATUS_SUCCESS; }
cublasStatus_t cublasSetMathMode(cublasHandle_t, cublasMath_t) { return CUBLAS_STATUS_SUCCESS; }

namespace {
const char* typeTag(cudaDataType t) {
  switch (t) {
    case CUDA_R_32F: return "f32";
    case CUDA_R_16F: return "f16";
    case CUDA_R_16BF: return "bf16";
    default: die("a GEMM of an unsupported data type " + std::to_string((int)t));
  }
}
struct GemmArgs {
  uint64_t A, B, C, D, bias;
  int64_t sa, sb, sc, sd;
  int32_t m, n, k, lda, ldb, ldc, ldd;
  int32_t ta, tb, ptrs, epilogue, biasType;
  float alpha, beta;
  uint64_t aux = 0; int32_t ldaux = 0, auxPad = 0;
  uint64_t aux2 = 0, aux3 = 0; int64_t tgR0 = 0, tgPairs = 0; int32_t tgN = 0, tgNp = 0, tgC = 0, tgPad = 0;
};
double hostElement(cudaDataType t, const void* base, size_t i) {
  if (t == CUDA_R_32F) return ((const float*)base)[i];
  if (t == CUDA_R_16F) return (float)((const __half*)base)[i];
  return (float)((const __nv_bfloat16*)base)[i];
}
void gemmCheck(cudaDataType ta_, cudaDataType tb_, cudaDataType tc_, const GemmArgs& a, int batch, const std::vector<unsigned char>& cBefore);
void gemm(cudaDataType ta_, cudaDataType tb_, cudaDataType tc_, GemmArgs a, int batch) {
  if (a.m <= 0 || a.n <= 0 || batch <= 0) return;
  Runtime& r = R();
  std::lock_guard<std::recursive_mutex> l(r.mu);
  // LOCALFOLD_CHECK_GEMM=<calls>: the first calls recomputed on the host (sampled entries, double) and compared
  static int checks = getenv("LOCALFOLD_CHECK_GEMM") ? atoi(getenv("LOCALFOLD_CHECK_GEMM")) : 0;
  bool check = checks > 0 && !r.capturingHere() && (!a.ptrs || a.beta == 0.f) && !(a.epilogue & (64 | 128 | 256));
  std::vector<unsigned char> cBefore;
  if (check) {
    --checks;
    r.sync();
    size_t es = tc_ == CUDA_R_32F ? 4 : 2;
    size_t span = ((size_t)(batch - 1) * a.sc + (size_t)(a.n - 1) * a.ldc + a.m) * es;
    cBefore.resize(span);
    if (a.beta != 0.f) memcpy(cBefore.data(), r.host((void*)a.C), span);
  }
  struct Run { cudaDataType ta_, tb_, tc_; GemmArgs a; int batch; bool check; std::vector<unsigned char>* cb; Runtime& r;
    ~Run() { if (check) { r.sync(); gemmCheck(ta_, tb_, tc_, a, batch, *cb); } } } run{ta_, tb_, tc_, a, batch, check, &cBefore, r};
  ++r.stats.gemms;
  // the tile: 64 x 64, or narrower along a short side (more threadgroups for a skinny product)
  // the tile: TR rows along n by TC columns along m. A short n (up to 128) in ONE tile row - every weight read once -
  // rounded up to 16; the columns then as many as keep a simdgroup's accumulators at 16 or fewer (TR/16 x TC/16)
  int tr = 64, tc = 64;
  if (a.n <= 128) {
    tr = (a.n + 15) / 16 * 16;
    tc = tr <= 64 ? 64 : 32;
  } else if (a.m <= 48) {
    tr = 64; tc = 32;
  }
  // a 48-row tile where 64-row tiles would waste over a tenth of the rows on padding and 48 wastes less: 272 rows (AF3's
  // diffusion at 255 tokens) are 320 in 64s and 288 in 48s - 0.91-0.96x the time there, 0.87x at 140 rows, and neutral
  // where it does not apply. An 80-row tile lost (1.06-1.16x at 4624 rows), and so did 48 for a 2% saving (1000 rows)
  if (a.n > 128 && tr == 64) {
    long pad64 = (long)((a.n + 63) / 64) * 64 - a.n, pad48 = (long)((a.n + 47) / 48) * 48 - a.n;
    if (pad64 * 10 > a.n && pad48 < pad64) tr = 48;
  }
  // too few threadgroups for the device: narrower columns
  auto groups = [&](int c) { return (long)((a.m + c - 1) / c) * ((a.n + tr - 1) / tr) * batch; };
  while (tc > 16 && groups(tc) < 64) tc /= 2;
  int bm = tc, bn = tr;
  auto esize = [](cudaDataType t) { return t == CUDA_R_32F ? 4 : 2; };
  bool vec = !a.ptrs && a.lda % 8 == 0 && a.ldb % 8 == 0 && (a.sa % 8 == 0) && (a.sb % 8 == 0) &&
             a.A % (8 * esize(ta_)) == 0 && a.B % (8 * esize(tb_)) == 0;
  if (vec) a.biasType |= 256;
  if (getenv("LF_GEMM_DEBUG")) fprintf(stderr, "gemm %dx%dx%d ta %d tb %d tile %dx%d vec %d batch %d\n", a.m, a.n, a.k, a.ta, a.tb, tr, tc, (int)vec, batch);
  auto mtype = [](cudaDataType t) { return t == CUDA_R_32F ? "float" : t == CUDA_R_16F ? "half" : "lf_bf16s"; };
  // the k step: 16 for a whole 64 x 64 tile, 32 otherwise. Measured interleaved (AB=1 metal/tools/bench-gemm) on an M2:
  // 16 is 0.73-0.85x the time on the triangle's tall K-128 projections (512 x 68121 x 128), 0.83-0.89x on the pair
  // track's 2048 x 4624 x 256 and 256 x 4624 x 1024, 0.84x on a 4096-cube - half the threadgroup memory, more tiles
  // resident to hide the loads - and 1.09x on a 64 x 32 tile, 1.08-1.21x on the 16-column ones
  int bk = tc == 64 && tr >= 48 ? 16 : 32;
  if (const char* k = getenv("LOCALFOLD_GEMM_BK")) bk = atoi(k) == 16 ? 16 : 32;       // (an arm: 16 or 32 everywhere)
  // an all-half GEMM accumulates in half: 0.85x the time on the trunk's K-128 projections (512, 128 and 1024 x 68121 x
  // 128, interleaved on an M2) for a relRMS of 1.7e-3 against 2.4e-4 - bfloat16's rounding, the precision AF3 runs at.
  // Accumulating each k step in half and adding it to a float accumulator (6.6e-4) won nothing. A GEMM writing float
  // (a residual) keeps float. LOCALFOLD_GEMM_FLOAT_ACC=1 is the control arm.
  static const bool floatAcc = getenv("LOCALFOLD_GEMM_FLOAT_ACC") != nullptr;
  // (not a float output, even at k <= 128: 0.94x on the residual's GEMMs, and IntelliFold-2 and ESMFold2 overflowed
  // one of them to inf and crashed downstream)
  const bool hacc = !floatAcc && ta_ == CUDA_R_16F && tb_ == CUDA_R_16F && tc_ == CUDA_R_16F;
  std::string targs = std::string(mtype(ta_)) + ", " + mtype(tb_) + ", " + mtype(tc_) + ", " + std::to_string(tr) + ", " +
                      std::to_string(tc) + ", " + (a.ta ? "true" : "false") + ", " + (a.tb ? "true" : "false") + ", " + std::to_string(bk) + ", " + std::to_string((a.epilogue & 256 ? 1 : 0) | (hacc ? 8 : 0));
  std::string name = std::string("lf_gemm_") + typeTag(ta_) + "_" + typeTag(tb_) + "_" + typeTag(tc_) + "_" +
                     std::to_string(tr) + "x" + std::to_string(tc) + "_" + (a.ta ? "T" : "N") + (a.tb ? "T" : "N") + (bk == 32 ? "" : "_k" + std::to_string(bk)) + (a.epilogue & 256 ? "_trigate" : "") + (hacc ? "_h" : "");
  if (getenv("LF_GEMM_DEBUG")) fprintf(stderr, "  -> %s\n", name.c_str());
  std::string decl = "template [[host_name(\"" + name + "\")]] kernel void lf_gemm<" + targs + ">(constant GemmArgs&, uint3, uint, uint, uint);";
  MTLSize grid = MTLSizeMake((a.m + bm - 1) / bm, (a.n + bn - 1) / bn, batch);
  char label[96]; snprintf(label, sizeof label, "gemm %s %dx%dx%d%s", name.c_str() + 8, a.m, a.n, a.k, batch > 1 ? " batched" : "");
  r.dispatch(r.runtimeInstance(name, decl), &a, sizeof a, grid, MTLSizeMake(128, 1, 1), 0, (r.profiling || r.capturingHere()) ? std::string(label) : "");
}
}  // namespace
// pair[r][o] += aux[r][o] * sigmoid(sum_k X[r][k] W[k][o]): a gate's GEMM adding its gated product into an f32 residual in
// its own epilogue, where cuBLAS's ports write the gate and add it in a pass of their own (metal/af3/patch)
void lf::gemmGatedAdd(const void* X, const void* W, const void* aux, float* pair, size_t rows, int in, int out) {
  GemmArgs a{(uint64_t)W, (uint64_t)X, (uint64_t)pair, (uint64_t)pair, 0, 0, 0, 0, 0, out, (int)rows, in, out, in, out, out,
             0, 0, 0, 64, 0, 1.f, 0.f};
  a.aux = (uint64_t)aux; a.ldaux = out;
  gemm(CUDA_R_16F, CUDA_R_16F, CUDA_R_32F, a, 1);
}
// gated[r][k] = silu(a) b, (a, b) = (X W)[r][2k, 2k+1]: W's columns interleaved a_0 b_0 a_1 b_1 ... (metal/af3/patch)
void lf::gemmSwiglu(const void* X, const void* Wpairs, void* gated, size_t rows, int in, int hidden) {
  GemmArgs a{(uint64_t)Wpairs, (uint64_t)X, (uint64_t)gated, (uint64_t)gated, 0, 0, 0, 0, 0, 2 * hidden, (int)rows, in,
             2 * hidden, in, hidden, hidden, 0, 0, 0, 128, 0, 1.f, 0.f};
  gemm(CUDA_R_16F, CUDA_R_16F, CUDA_R_16F, a, 1);
}
// the triangle's projection and gate in one GEMM: a[c][q], b[c][q] (channel-major over the padded positions) from
// X [rows][C] and W [C][4C] with channel c's (pa, pb, ga, gb) at columns 4c..4c+3 (metal/af3/pairtrack.cuh.patch)
void lf::gemmTriGate(const void* X, const void* W, const float* mask, void* a, void* b, size_t r0, size_t rows, int C,
                     size_t pairs, int n, int np) {
  GemmArgs g{(uint64_t)W, (uint64_t)X, (uint64_t)a, (uint64_t)a, 0, 0, 0, 0, 0, 4 * C, (int)rows, C, 4 * C, C, 4 * C,
             4 * C, 0, 0, 0, 256, 0, 1.f, 0.f};
  g.aux = (uint64_t)mask; g.aux2 = (uint64_t)a; g.aux3 = (uint64_t)b;
  g.tgR0 = (int64_t)r0; g.tgPairs = (int64_t)pairs; g.tgN = n; g.tgNp = np; g.tgC = C;
  gemm(CUDA_R_16F, CUDA_R_16F, CUDA_R_16F, g, 1);
}
namespace {
float scalar(const void* p, cublasComputeType_t compute) {
  if (compute == CUBLAS_COMPUTE_16F) return (float)*(const __half*)p;
  return *(const float*)p;
}
}  // namespace

namespace {
void gemmCheck(cudaDataType ta_, cudaDataType tb_, cudaDataType tc_, const GemmArgs& g, int batch, const std::vector<unsigned char>& cBefore) {
  Runtime& r = R();
  const void* A = r.host((void*)g.A); const void* B = r.host((void*)g.B); const void* D = r.host((void*)g.D);
  double err = 0, nrm = 0; int bad = 0;
  uint64_t seed = 12345;
  for (int s = 0; s < 64; ++s) {
    seed = seed * 6364136223846793005ull + 1442695040888963407ull;
    int z = (int)((seed >> 33) % batch), i = (int)((seed >> 13) % g.m), j = (int)((seed >> 40) % g.n);
    if (g.ptrs) {   // the operands through the device arrays of pointers, batch z's own (strides 0)
      A = r.host((void*)((const uint64_t*)r.host((void*)g.A))[z]);
      B = r.host((void*)((const uint64_t*)r.host((void*)g.B))[z]);
      D = r.host((void*)((const uint64_t*)r.host((void*)g.D))[z]);
      z = 0;
    }
    double v = 0;
    for (int k = 0; k < g.k; ++k) {
      size_t ai = (size_t)z * g.sa + (g.ta ? (size_t)k + (size_t)i * g.lda : (size_t)i + (size_t)k * g.lda);
      size_t bi = (size_t)z * g.sb + (g.tb ? (size_t)j + (size_t)k * g.ldb : (size_t)k + (size_t)j * g.ldb);
      v += hostElement(ta_, A, ai) * hostElement(tb_, B, bi);
    }
    v *= g.alpha;
    size_t ci = (size_t)z * g.sc + (size_t)i + (size_t)j * g.ldc;
    if (g.beta != 0.f) v += g.beta * hostElement(tc_, cBefore.data(), ci);
    if (g.epilogue & 4) v += (g.biasType & 255) == 2 ? (double)(float)((const __half*)r.host((void*)g.bias))[i] : ((const float*)r.host((void*)g.bias))[i];
    if (g.epilogue & 2) v = std::max(v, 0.0);
    size_t di = (size_t)z * g.sd + (size_t)i + (size_t)j * g.ldd;
    double got = hostElement(tc_, D, di);
    if (!std::isfinite(got)) ++bad;
    err += (got - v) * (got - v); nrm += v * v;
  }
  fprintf(stderr, "  gemm check %s%s%s %dx%dx%d ta %d tb %d batch %d alpha %g beta %g epi %d: relRMS %.3e%s\n", typeTag(ta_), typeTag(tb_),
          typeTag(tc_), g.m, g.n, g.k, g.ta, g.tb, batch, g.alpha, g.beta, g.epilogue, std::sqrt(err / std::max(nrm, 1e-300)), bad ? " NONFINITE" : "");
}
}  // namespace
cublasStatus_t cublasSgemm(cublasHandle_t, cublasOperation_t ta, cublasOperation_t tb, int m, int n, int k,
                           const float* alpha, const float* A, int lda, const float* B, int ldb, const float* beta, float* C, int ldc) {
  GemmArgs a{(uint64_t)A, (uint64_t)B, (uint64_t)C, (uint64_t)C, 0, 0, 0, 0, 0, m, n, k, lda, ldb, ldc, ldc,
             ta != CUBLAS_OP_N, tb != CUBLAS_OP_N, 0, 0, 0, *alpha, *beta};
  gemm(CUDA_R_32F, CUDA_R_32F, CUDA_R_32F, a, 1);
  return CUBLAS_STATUS_SUCCESS;
}
cublasStatus_t cublasSgemmStridedBatched(cublasHandle_t, cublasOperation_t ta, cublasOperation_t tb, int m, int n, int k,
                                         const float* alpha, const float* A, int lda, long long sa, const float* B, int ldb,
                                         long long sb, const float* beta, float* C, int ldc, long long sc, int batch) {
  GemmArgs a{(uint64_t)A, (uint64_t)B, (uint64_t)C, (uint64_t)C, 0, sa, sb, sc, sc, m, n, k, lda, ldb, ldc, ldc,
             ta != CUBLAS_OP_N, tb != CUBLAS_OP_N, 0, 0, 0, *alpha, *beta};
  gemm(CUDA_R_32F, CUDA_R_32F, CUDA_R_32F, a, batch);
  return CUBLAS_STATUS_SUCCESS;
}
cublasStatus_t cublasGemmEx(cublasHandle_t, cublasOperation_t ta, cublasOperation_t tb, int m, int n, int k,
                            const void* alpha, const void* A, cudaDataType ta_, int lda, const void* B, cudaDataType tb_, int ldb,
                            const void* beta, void* C, cudaDataType tc_, int ldc, cublasComputeType_t compute, cublasGemmAlgo_t) {
  GemmArgs a{(uint64_t)A, (uint64_t)B, (uint64_t)C, (uint64_t)C, 0, 0, 0, 0, 0, m, n, k, lda, ldb, ldc, ldc,
             ta != CUBLAS_OP_N, tb != CUBLAS_OP_N, 0, 0, 0, scalar(alpha, compute), scalar(beta, compute)};
  gemm(ta_, tb_, tc_, a, 1);
  return CUBLAS_STATUS_SUCCESS;
}
cublasStatus_t cublasGemmStridedBatchedEx(cublasHandle_t, cublasOperation_t ta, cublasOperation_t tb, int m, int n, int k,
                                          const void* alpha, const void* A, cudaDataType ta_, int lda, long long sa,
                                          const void* B, cudaDataType tb_, int ldb, long long sb, const void* beta,
                                          void* C, cudaDataType tc_, int ldc, long long sc, int batch,
                                          cublasComputeType_t compute, cublasGemmAlgo_t) {
  GemmArgs a{(uint64_t)A, (uint64_t)B, (uint64_t)C, (uint64_t)C, 0, sa, sb, sc, sc, m, n, k, lda, ldb, ldc, ldc,
             ta != CUBLAS_OP_N, tb != CUBLAS_OP_N, 0, 0, 0, scalar(alpha, compute), scalar(beta, compute)};
  gemm(ta_, tb_, tc_, a, batch);
  return CUBLAS_STATUS_SUCCESS;
}
cublasStatus_t cublasGemmBatchedEx(cublasHandle_t, cublasOperation_t ta, cublasOperation_t tb, int m, int n, int k,
                                   const void* alpha, const void* const A[], cudaDataType ta_, int lda,
                                   const void* const B[], cudaDataType tb_, int ldb, const void* beta,
                                   void* const C[], cudaDataType tc_, int ldc, int batch,
                                   cublasComputeType_t compute, cublasGemmAlgo_t) {
  GemmArgs a{(uint64_t)A, (uint64_t)B, (uint64_t)C, (uint64_t)C, 0, 0, 0, 0, 0, m, n, k, lda, ldb, ldc, ldc,
             ta != CUBLAS_OP_N, tb != CUBLAS_OP_N, 1, 0, 0, scalar(alpha, compute), scalar(beta, compute)};
  gemm(ta_, tb_, tc_, a, batch);
  return CUBLAS_STATUS_SUCCESS;
}
cublasStatus_t cublasSscal(cublasHandle_t, int n, const float* alpha, float* x, int incx) {
  Runtime& r = R();
  std::lock_guard<std::recursive_mutex> l(r.mu);
  struct { uint64_t x; int32_t n, inc; float alpha; } a = {(uint64_t)x, n, incx, *alpha};
  r.dispatch(r.runtimePipeline("lf_scal"), &a, sizeof a, MTLSizeMake((n + 255) / 256, 1, 1), MTLSizeMake(256, 1, 1), 0);
  return CUBLAS_STATUS_SUCCESS;
}

// ---------------------------------------------------------------- cuBLASLt
struct LfLt_ { int unused; };
struct LfLtPref_ { int unused; };
cublasStatus_t cublasLtCreate(cublasLtHandle_t* h) { *h = new LfLt_(); return CUBLAS_STATUS_SUCCESS; }
cublasStatus_t cublasLtDestroy(cublasLtHandle_t h) { delete h; return CUBLAS_STATUS_SUCCESS; }
cublasStatus_t cublasLtMatmulDescCreate(cublasLtMatmulDesc_t* d, cublasComputeType_t compute, cudaDataType scale) {
  *d = new LfLtDesc(); (*d)->compute = compute; (*d)->scale = scale; return CUBLAS_STATUS_SUCCESS;
}
cublasStatus_t cublasLtMatmulDescDestroy(cublasLtMatmulDesc_t d) { delete d; return CUBLAS_STATUS_SUCCESS; }
cublasStatus_t cublasLtMatmulDescSetAttribute(cublasLtMatmulDesc_t d, cublasLtMatmulDescAttributes_t a, const void* v, size_t) {
  switch (a) {
    case CUBLASLT_MATMUL_DESC_TRANSA: d->ta = *(const int*)v; break;
    case CUBLASLT_MATMUL_DESC_TRANSB: d->tb = *(const int*)v; break;
    case CUBLASLT_MATMUL_DESC_EPILOGUE: d->epilogue = *(const int*)v; break;
    case CUBLASLT_MATMUL_DESC_BIAS_POINTER: d->bias = *(const void* const*)v; break;
    case CUBLASLT_MATMUL_DESC_BIAS_DATA_TYPE: d->biasType = *(const int*)v; break;
    default: break;
  }
  return CUBLAS_STATUS_SUCCESS;
}
cublasStatus_t cublasLtMatrixLayoutCreate(cublasLtMatrixLayout_t* l, cudaDataType type, uint64_t rows, uint64_t cols, int64_t ld) {
  *l = new LfLtLayout(); (*l)->type = type; (*l)->rows = rows; (*l)->cols = cols; (*l)->ld = ld;
  return CUBLAS_STATUS_SUCCESS;
}
cublasStatus_t cublasLtMatrixLayoutDestroy(cublasLtMatrixLayout_t l) { delete l; return CUBLAS_STATUS_SUCCESS; }
cublasStatus_t cublasLtMatrixLayoutSetAttribute(cublasLtMatrixLayout_t l, cublasLtMatrixLayoutAttribute_t a, const void* v, size_t) {
  switch (a) {
    case CUBLASLT_MATRIX_LAYOUT_BATCH_COUNT: l->batch = *(const int*)v; break;
    case CUBLASLT_MATRIX_LAYOUT_STRIDED_BATCH_OFFSET: l->stride = *(const long long*)v; break;
    case CUBLASLT_MATRIX_LAYOUT_ORDER: l->order = *(const int*)v; break;
    case CUBLASLT_MATRIX_LAYOUT_LD: l->ld = *(const long long*)v; break;
    default: break;
  }
  return CUBLAS_STATUS_SUCCESS;
}
cublasStatus_t cublasLtMatmulPreferenceCreate(cublasLtMatmulPreference_t* p) { *p = new LfLtPref_(); return CUBLAS_STATUS_SUCCESS; }
cublasStatus_t cublasLtMatmulPreferenceDestroy(cublasLtMatmulPreference_t p) { delete p; return CUBLAS_STATUS_SUCCESS; }
cublasStatus_t cublasLtMatmulPreferenceSetAttribute(cublasLtMatmulPreference_t, cublasLtMatmulPreferenceAttributes_t, const void*, size_t) {
  return CUBLAS_STATUS_SUCCESS;
}
cublasStatus_t cublasLtMatmulAlgoGetHeuristic(cublasLtHandle_t, cublasLtMatmulDesc_t, cublasLtMatrixLayout_t, cublasLtMatrixLayout_t,
                                              cublasLtMatrixLayout_t, cublasLtMatrixLayout_t, cublasLtMatmulPreference_t,
                                              int requested, cublasLtMatmulHeuristicResult_t* out, int* got) {
  if (requested > 0) { memset(out, 0, sizeof *out); out[0].state = CUBLAS_STATUS_SUCCESS; *got = 1; } else *got = 0;
  return CUBLAS_STATUS_SUCCESS;
}
cublasStatus_t cublasLtMatmulAlgoConfigGetAttribute(const cublasLtMatmulAlgo_t*, cublasLtMatmulAlgoConfigAttributes_t a,
                                                    void* v, size_t n, size_t* written) {
  memset(v, 0, n);
  if (a == CUBLASLT_ALGO_CONFIG_TILE_ID && n >= 4) *(int*)v = CUBLASLT_MATMUL_TILE_128x128;
  if (written) *written = n;
  return CUBLAS_STATUS_SUCCESS;
}
cublasStatus_t cublasLtMatmul(cublasLtHandle_t, cublasLtMatmulDesc_t d, const void* alpha, const void* A, cublasLtMatrixLayout_t la,
                              const void* B, cublasLtMatrixLayout_t lb, const void* beta, const void* C, cublasLtMatrixLayout_t lc,
                              void* D, cublasLtMatrixLayout_t ld, const cublasLtMatmulAlgo_t*, void*, size_t, cudaStream_t) {
  if (la->order || lb->order || lc->order || ld->order) die("cuBLASLt with a row-major layout");
  int m = (int)ld->rows, n = (int)ld->cols, k = d->ta ? (int)la->rows : (int)la->cols;
  int epi = d->epilogue == CUBLASLT_EPILOGUE_RELU ? 2 : d->epilogue == CUBLASLT_EPILOGUE_BIAS ? 4
          : d->epilogue == CUBLASLT_EPILOGUE_RELU_BIAS ? 6 : d->epilogue == CUBLASLT_EPILOGUE_GELU ? 32
          : d->epilogue == CUBLASLT_EPILOGUE_GELU_BIAS ? 36 : 0;
  int biasType = d->biasType ? d->biasType : ld->type;
  GemmArgs a{(uint64_t)A, (uint64_t)B, (uint64_t)C, (uint64_t)D, (uint64_t)d->bias, la->stride, lb->stride, lc->stride, ld->stride,
             m, n, k, (int)la->ld, (int)lb->ld, (int)lc->ld, (int)ld->ld, d->ta != 0, d->tb != 0, 0, epi, biasType,
             scalar(alpha, (cublasComputeType_t)d->compute), scalar(beta, (cublasComputeType_t)d->compute)};
  if ((cudaDataType)lc->type != (cudaDataType)ld->type && *(const float*)beta != 0.f) die("cuBLASLt with C and D of different types");
  gemm((cudaDataType)la->type, (cudaDataType)lb->type, (cudaDataType)ld->type, a, std::max(ld->batch, 1));
  return CUBLAS_STATUS_SUCCESS;
}
